### ISSUE TITLE
功能已经能实现跨页了么？包括双栏情况下的跨页

### ISSUE THREAD

**Issue by hushidong** [lvjr/tabularray#1]
如题：功能已经能实现跨页了么？包括双栏情况下的跨页

**Comment by lvjr** [comment]
跨页表格在计划中，等基本功能稳定后再实现。可以在这里先讨论目前的跨页宏包比如 `supertabular` 和 `longtable` 的优点和缺点，供后面实现时参考。

**Comment by hushidong** [comment]
从功能层面看，根据我之前的经验，目前的方法能够实现大多数的需求，但有两个主要的问题是：一是分栏情况下的跨页表格实现的并不好（或者就没有完整实现）；二是目前各种功能的实现需要的宏包较多，表的列格式，表的宽高设计，表内跨列，跨行，斜线表头，表的框线，表的单元的装饰等等都来源于不同的宏包。

我的希望是能够有一个宏包来实现表格的所有功能，并解决分栏跨页表格的问题，那么这个将是一个非常大的突破。当然这也是一个很大的工程。加油！

**Comment by lvjr** [comment]
除了斜线表头和跨页表格，上面的功能基本已经在 tabularray 里实现。tabularray 不依赖任何其他表格宏包，它的目标就是替代全部这些旧有的宏包。

**Comment by lvjr** [comment]
我已将这个 Issue 拆分成两个（#8， #9），并改用英语描述，以方便和其他人交流。这个 Issue 就先关闭了。

**Comment by lvjr** [comment]
最新版本 2021L 已完整实现斜线表头和跨页表格。

**Comment by hushidong** [comment]
感谢付出！ 前一段还跟老王聊，你这个工作是国内对latex社区的重要贡献，从国际角度看不比ctex的贡献小。国内真正原创的解决普遍问题的宏包没有多少。 hzzmail ***@***.*** 签名由 网易邮箱大师 定制 在2021年07月01日 10:41，lvjr 写道： 最新版本 2021L 已完整实现斜线表头和跨页表格。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
