### ISSUE TITLE
longtblr captions

### ISSUE THREAD

**Issue by c-alpha** [lvjr/tabularray#103]
In my document style, I use the `caption` package with the following setup:
```latex
\RequirePackage{caption}
\captionsetup{font=singlespacing, labelfont=bf, textfont=it, margin=2cm, format=hang}
\captionsetup[figure]{position=below}
\captionsetup[table]{position=above}
```
Which produces for instance:
<img width="282" alt="Screenshot 2021-09-11 at 00 35 31 " src="https://user-images.githubusercontent.com/2213269/132924740-557dcaf7-eb1a-461f-ba0b-b1445f34f00d.png">

It seems that `longtblr` does not use the `\caption` command to produce captions? When I put
```latex
\begin{longtblr}[
	     caption  = {the second caption text},
	   ]
```
in my document, then I get this:
<img width="282" alt="Screenshot 2021-09-11 at 00 35 56 " src="https://user-images.githubusercontent.com/2213269/132925055-cc79e447-b0e1-49f6-8fd3-172dd1ae97c3.png">
No bold, no italics.

I also use the `polyglossia` package to get "table", "figure", etc. in other languages. Again, the caption label generated by `longtblr` is always "Table", regardless of the active `polyglossia` language.

**So I guess my plea is to modify `longtblr` to make use of the `\caption` command, and the `caption` package.** This would add the benefit, that - without any further work on the part of the user - `longtblr` captions would behave exactly the same as all other captions in terms of styling using the `caption` package, and in terms of automatic translation of the caption labels using the `polyglossia` or `babel` packages.

The `caption` package provides some features to support the implementation of the `longtable` package. I think you could readily make use of at least some of them. Less code for you to write and maintain... 😉 

Also, some of `longtblr`'s caption templates would perhaps no longer be needed when using the `\caption` command? Again, less code for you...

On a loosely related note:
```latex
\DefTblrTemplate{contfoot-text}{default}{\GetTranslation{longtab-cont-on-nextpg}}
\DefTblrTemplate{contfoot-text}{default}{\it (alpha beta gamma)}
\DefTblrTemplate{contfoot-text}{default}{alpha beta gamma}
```
removes all whitespace in all three cases (i.e. renders as "alphabetagamma").

**Comment by lvjr** [comment]
Use translated `Table` name from `polyglossia` is easy: we only need to modify one line of code in `tabularray.sty`.

```latex
\documentclass{article}

\usepackage{longtable}
\usepackage{tabularray}

\usepackage{polyglossia} % Need XeTeX or LuaTeX
\setmainlanguage{french}

%\DefTblrTemplate{caption-tag}{normal}{Table\hspace{0.25em}\thetable}     %% Old
\DefTblrTemplate{caption-tag}{normal}{\tablename\hspace{0.25em}\thetable} %% New
\SetTblrTemplate{caption-tag}{normal}

\begin{document}

\begin{longtable}{lll}
  \caption{Longtable Caption} \\
  Alpha   & Beta  & Gamma  \\
  Epsilon & Zeta  & Eta    \\
  Iota    & Kappa & Lambda \\
\end{longtable}

\begin{longtblr}[
  caption  = {Longtblr Caption},
]{lll}
  Alpha   & Beta  & Gamma  \\
  Epsilon & Zeta  & Eta    \\
  Iota    & Kappa & Lambda \\
\end{longtblr}

\end{document} 
```

![image](https://user-images.githubusercontent.com/4239949/132939885-41def79d-3360-4a46-b08a-3887b4248939.png)

**Comment by lvjr** [comment]
Use translated `Table` name from `polyglossia` is easy: we only need to modify one line of code in `tabularray.sty`.

```latex
\documentclass{article}

\usepackage{longtable}
\usepackage{tabularray}

\usepackage{polyglossia} % Need XeTeX or LuaTeX
\setmainlanguage{french}

%\DefTblrTemplate{caption-tag}{normal}{Table\hspace{0.25em}\thetable}     %% Old
\DefTblrTemplate{caption-tag}{normal}{\tablename\hspace{0.25em}\thetable} %% New
\SetTblrTemplate{caption-tag}{normal}

\begin{document}

\begin{longtable}{lll}
  \caption{Longtable Caption} \\
  Alpha   & Beta  & Gamma  \\
  Epsilon & Zeta  & Eta    \\
  Iota    & Kappa & Lambda \\
\end{longtable}

\begin{longtblr}[
  caption  = {Longtblr Caption},
]{lll}
  Alpha   & Beta  & Gamma  \\
  Epsilon & Zeta  & Eta    \\
  Iota    & Kappa & Lambda \\
\end{longtblr}

\end{document} 
```

![image](https://user-images.githubusercontent.com/4239949/132939885-41def79d-3360-4a46-b08a-3887b4248939.png)

**Comment by lvjr** [comment]
You can use `\SetTblrStyle` command to change the styles of a caption.

```latex
\documentclass{article}

\usepackage{longtable}
\usepackage{tabularray}

\usepackage{caption}
\captionsetup{font=singlespacing, labelfont=bf, textfont=it, margin=2cm, format=hang}
\captionsetup[figure]{position=below}
\captionsetup[table]{position=above}

\SetTblrStyle{caption-tag}{font=\bfseries}
\SetTblrStyle{caption-text}{font=\itshape}

\begin{document}

\begin{longtable}{lll}
  \caption{Longtable Caption} \\
  Alpha   & Beta  & Gamma  \\
  Epsilon & Zeta  & Eta    \\
  Iota    & Kappa & Lambda \\
\end{longtable}

\begin{longtblr}[
  caption  = {Longtblr Caption},
]{lll}
  Alpha   & Beta  & Gamma  \\
  Epsilon & Zeta  & Eta    \\
  Iota    & Kappa & Lambda \\
\end{longtblr}

\end{document} 
```

**Comment by lvjr** [comment]
You can use `\SetTblrStyle` command to change the styles of a caption.

```latex
\documentclass{article}

\usepackage{longtable}
\usepackage{tabularray}

\usepackage{caption}
\captionsetup{font=singlespacing, labelfont=bf, textfont=it, margin=2cm, format=hang}
\captionsetup[figure]{position=below}
\captionsetup[table]{position=above}

\SetTblrStyle{caption-tag}{font=\bfseries}
\SetTblrStyle{caption-text}{font=\itshape}

\begin{document}

\begin{longtable}{lll}
  \caption{Longtable Caption} \\
  Alpha   & Beta  & Gamma  \\
  Epsilon & Zeta  & Eta    \\
  Iota    & Kappa & Lambda \\
\end{longtable}

\begin{longtblr}[
  caption  = {Longtblr Caption},
]{lll}
  Alpha   & Beta  & Gamma  \\
  Epsilon & Zeta  & Eta    \\
  Iota    & Kappa & Lambda \\
\end{longtblr}

\end{document} 
```

**Comment by lvjr** [comment]
Also, you can redefine `firsthead` template to make use of  `\captionof` command from `caption` package.

Note that `tabularray` follows `threeparttable` and `threeparttablex` packages where caption width is tha same as table width.

```latex
\documentclass{article}

\usepackage{longtable}
\usepackage{tabularray}

\usepackage{caption}
\captionsetup{font=singlespacing, labelfont=bf, textfont=it, format=hang}
\captionsetup[figure]{position=below}
\captionsetup[table]{position=above}

\DefTblrTemplate{firsthead}{default}{\captionof{table}{\InsertTblrText{caption}}}

\begin{document}

\begin{longtblr}[
  caption  = {Longtblr Long Caption Caption Caption Caption Caption Caption Caption},
]{lll}
\hline
  Alpha   & Beta  & Gamma  & Alpha   & Beta  & Gamma  \\
  Epsilon & Zeta  & Eta    & Epsilon & Zeta  & Eta    \\
  Iota    & Kappa & Lambda & Iota    & Kappa & Lambda \\
\hline
\end{longtblr}

\end{document}
```

![image](https://user-images.githubusercontent.com/4239949/132942084-b0abf8e4-84f4-4cbc-a1ad-d4b7a8fddc7d.png)

**Comment by c-alpha** [comment]
> Using translated `Table` name from `polyglossia` is easy: we only need to modify one line of code in `tabularray.sty`.

Cool, it seems as easy as I had hoped it could be. So I take it this will be in the next release? 😉

**Comment by c-alpha** [comment]
> You can use `\SetTblrStyle` command to change the styles of a caption.

> Also, you can redefine firsthead template to make use of `\captionof` command from `caption` package.

Would you perhaps feel inclined to make this automatic? You would need to detect whether the `caption` package is available, and if yes, apply the styles and use `\captionof`. If the `caption` package is not available, use the defaults as are today.

That would be super-cool, because it would make `longtblr` behave like any other table in terms of caption. One less thing for users to scratch their heads about... 😉 

What do you think?

**Comment by c-alpha** [comment]
> [...]
> On a loosely related note:
> 
> ```latex
> \DefTblrTemplate{contfoot-text}{default}{\GetTranslation{longtab-cont-on-nextpg}}
> \DefTblrTemplate{contfoot-text}{default}{\it (alpha beta gamma)}
> \DefTblrTemplate{contfoot-text}{default}{alpha beta gamma}
> ```
> 
> removes all whitespace in all three cases (i.e. renders as "alphabetagamma").

I rest my case on this one. Of course I need to `\ExplSyntaxOff` before using `\DeclareTranslation`. My bad.

**Comment by c-alpha** [comment]
> ```latex
> \DefTblrTemplate{firsthead}{default}{\captionof{table}{\InsertTblrText{caption}}}
> ```

Shouldn't that be the starred version, i.e. `\captionof*`? The unstarred version increments the table counter?

When I substitute `\captionof*` in the above line, I get no "Table 4.2" label at all, but no error message either.

**Comment by lvjr** [comment]
> Would you perhaps feel inclined to make this automatic? You would need to detect whether the caption package is available, and if yes, apply the styles and use \captionof. If the caption package is not available, use the defaults as are today.

> Shouldn't that be the starred version, i.e. \captionof*? The unstarred version increments the table counter?
> When I substitute \captionof* in the above line, I get no "Table 4.2" label at all, but no error message either.

In fact, `caption` package is large with plenty of options. I can not make table titles of `tabularray` behave the same as those of `caption` package. Therefore I decided not to spend my limited time on this. Users should always use `\SetTblrStyle` and `\DefTblrTemplate` to get what they need. Sorry.

**Comment by lvjr** [comment]
> Cool, it seems as easy as I had hoped it could be. So I take it this will be in the next release? 

I added it in the above commit.

**Comment by c-alpha** [comment]
> [...]
> In fact, `caption` package is large with plenty of options. I can not make table titles of `tabularray` behave the same as those of `caption` package in every case. Therefore I decided not to spend my limited time on this. Users should always use `\SetTblrStyle` and `\DefTblrTemplate` to get what they need. Sorry.

Fair enough. Many thanks for solving the translation problem!
