### ISSUE TITLE
`empty` setting

### ISSUE THREAD

**Issue by JDMCreator** [lvjr/tabularray#107]
It would be great to have an `empty` setting to set the content of empty cells.

**Comment by lvjr** [comment]
I can not understand why you need this.  Could you elaborate?

**Comment by JDMCreator** [comment]
Sometimes, when a cell is empty, an em dash (—) is inserted instead. This is useful in those cases.

**Comment by lvjr** [comment]
You can get it by using `cmd` option:

```latex
\documentclass{article}

\usepackage{tabularray}
\usepackage{ifthen}

\begin{document}

\newcommand{\myempty}[1]{\ifthenelse{\equal{#1}{}}{--}{#1}}

\begin{tblr}{cells={cmd=\myempty}}
  A & B &   \\
  D &   & F \\
\end{tblr}

\end{document}
```

![image](https://user-images.githubusercontent.com/4239949/133349971-8c03062a-e435-4d18-b5bf-f67c80e12005.png)
