### ISSUE TITLE
Problem with hline and table with more than 10 columns

### ISSUE THREAD

**Issue by cpierquet** [lvjr/tabularray#11]
Hi-, I've notices a problem with hlines in a tabular with more than 10 columns... the hline fills only the 1st column.
With brackets in the hline param it's ok  👍 
```
\begin{tblr}{hlines={0.45pt},vlines={0.45pt},hline{1-3}={1-{12}}{solid},columns={9mm,c}}
    $s_i$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$ & $9$ & $10$ & $11$ & $12$ \\
    $p_i$ & $\frac{1}{36}$ & $\frac{2}{36}$ & $\frac{3}{36}$ & $\frac{4}{36}$ & $\frac{5}{36}$ & $\frac{6}{36}$ & $\frac{5}{36}$ & $\frac{4}{36}$ & $\frac{3}{36}$ & $\frac{2}{36}$ & $\frac{1}{36}$ \\
\end{tblr}
```

**Comment by lvjr** [comment]
Thanks. I will fix this bug later.

**Comment by lvjr** [comment]
This bug should has been fixed. You may download the latest package file
https://github.com/lvjr/tabularray/raw/main/tabularray.sty
and test whether there are other problems.

**Comment by cpierquet** [comment]
Tks !!! Great job 👍
