### ISSUE TITLE
Adjusting leftpos/rightpos = -1 to trim a multi-column hline for only the leftmost/rightmost column

### ISSUE THREAD

**Issue by DAbidou** [lvjr/tabularray#110]
In this manual example
```
\begin{tblr}{
 hline{1,4} = {1}{-}{},
 hline{1,4} = {2}{-}{},
 hline{2,3} = {1}{-}{leftpos = -1, rightpos = -1},
 hline{2,3} = {2}{-}{leftpos = -1, rightpos = -1},
 vline{1,4} = {abovepos = 1, belowpos = 1},
}
 Alpha & Beta & Gamma \\
 Epsilon & Zeta & Eta \\
 Iota & Kappa & Lambda \\
\end{tblr}
```
![image](https://user-images.githubusercontent.com/19731193/133856363-ffb6119e-2309-4e59-99e7-716158ae39aa.png)

Is it possible for `leftpos` or `rightpos` to be enhanced or accompanied by a new option to make the trimming of `hline` happen at only the leftmost/rightmost columns not for every column so that the output doesn't have this intermittent `hline` with a separate segment at the floor of each cell?

**Comment by lvjr** [comment]
Use `endpos` option:
```latex
\begin{tblr}{
 hline{1,4} = {1}{-}{},
 hline{1,4} = {2}{-}{},
 hline{2,3} = {1}{-}{leftpos = -1, rightpos = -1, endpos},
 hline{2,3} = {2}{-}{leftpos = -1, rightpos = -1},
 vline{1,4} = {abovepos = 1, belowpos = 1},
}
 Alpha & Beta & Gamma \\
 Epsilon & Zeta & Eta \\
 Iota & Kappa & Lambda \\
\end{tblr}
```
![image](https://user-images.githubusercontent.com/4239949/133867891-f91bf64d-5b1f-4f58-b3d4-5e12e85a3b7b.png)
