### ISSUE TITLE
Trouble in treating url with number sign

### ISSUE THREAD

**Issue by atxy-blip** [lvjr/tabularray#113]
Hello! I attempted to add a url like `\href{https://www.google.com/get/noto/#sans-hans}{Source hans}` in one of the cells of `talltblr`. However, the number sign (#) contained would be misidentified as a parameter and cause a failed compilation. Also, follow a url with `\TblrNote` raises errors as well.

Could you please fix the compatibility issue with the `hyperref` package?

Many thanks.

**Comment by lvjr** [comment]
You may use `\#` instead of `#` inside `\href`. And you can not put `\href` inside `\TblrNote`.

```latex
\documentclass{article}

\usepackage{tabularray}
\usepackage{hyperref}

\begin{document}

\begin{tblr}{ll}
  Alpha & Beta \\
  Delta & Gamma\href{https://www.google.com/get/noto/\#sans-hans}{Source hans} \\
\end{tblr}

\bigskip

\begin{talltblr}[
  caption = {Table Title},
  note{a} = {\href{https://www.google.com/get/noto/\#sans-hans}{Source hans}},
]{
  hlines, colspec={XX}
}
  Alpha & Beta \\
  Delta & Gamma\TblrNote{a}
\end{talltblr}

\end{document}
```
PS: Better to provide some minimal code when opening an issue.

**Comment by atxy-blip** [comment]
Many thanks for the solution!

I will consider adding a MWE in all my future issues.
