### ISSUE TITLE
Last rows not showing when tblr contains truncated rows

### ISSUE THREAD

**Issue by gnotisauton** [lvjr/tabularray#114]
I noticed a bug in which the last (few) row(s) of the table are not appearing.
It seems to have to do with empty rows in the table.

Minimum failing example:
```
\begin{tblr}{cc}
this is & shown\\
\\
this is & not shown\\
\end{tblr}
```

Workaround:
```
\begin{tblr}{cc}
this is & shown\\
&\\
this is & not shown\\
\end{tblr}
```

I'm reporting this as a bug because the minimum failing example does show all rows in a {tabular} environment, and because it fails silently (my client noticed data was missing on my invoice).

**Comment by gnotisauton** [comment]
Some additional info for root cause analysis:
It seems that internal counters (X-Z for rows) do not reference the missing rows at the end. Styling row{Z} = {font={\bf}} would style the second (empty) row. It seems that truncated rows do not get counted in the internal row count.

**Comment by lvjr** [comment]
Thanks for reporting this bug. I will fix it later.

**Comment by lvjr** [comment]
This bug should has been fixed. You may download the latest package file
https://github.com/lvjr/tabularray/raw/main/tabularray.sty
and test whether there are other problems.
