### ISSUE TITLE
normalize `\DefAbcXyz` and `\NewAbcXyz` commands

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#115]
There has been more and more commands of the type `\DefAbcXyz` or `\NewAbcXyz`  added to this package.  I think it will be time to normalize their behaviors in version 2022: `\DefAbcXyz` should overwrite existing definition with a log message and `\NewAbcXyz` should throw an error if it has been defined before. And if possible we should provide both of `\DefAbcXyz` and `\NewAbcXyz`.

For `\NewColumnType` command this is a breaking change.

**Comment by FrankMittelbach** [comment]
I know that `\NewColumnType` is inconsistent with standard LaTex practice in this respect (which by the way is to use `\Declare...`not `\Def...`) but I would urge you to *not* alter the behavior in case of `\NewColumnType`. This is documented for more than 2 decades that it does overwrite (with a warning) existing declarations, so making this change it unnecessarily breaking a lot.

**Comment by lvjr** [comment]
Maybe mark it as deprecated and leave it as it is. Then try to find a new name for it.

**Comment by lvjr** [comment]
Sorry, I was very forgetful. I checked my code today and found that `\NewColumnType` and `\NewRowType` commands give warnings for existing definitions and don't overwrite them since the first public version of `tabularray`. It seems I have made the correct decision before. So I think I only need to change warnings to errors   and provide `\DefColumnType` and `\DefRowType` to users.

**Comment by FrankMittelbach** [comment]
Okay, for get my argument about `\NewColumnType`, the existing definition in other packages is all in lowercase, so there is no conflict unless you change the latter too, sorry for the noise.

But I still think it would be much more in line with existing code all over the place to go for `\Declare....` not `\Def...`

**Comment by lvjr** [comment]
I think `def` prefix is more popular than `declare` prefix among LaTeX packages. The very popular `beamer` package uses `def` prefix. And I have already used `\DefTblrTemplate` in `tabularray` package. So I think it is a good choice to stick to `def` prefix.

**Comment by u-fischer** [comment]
beamer has basically only one command here `\defbeamertemplate`, and that is all lowercase.  biblatex uses a lot of `\Declare...`  eg. `\DeclareBibliographyStrings`, `\Define...` is used too.

I'm not aware of another important package using `\Def` with an uppercase D and a search through the tex/latex folder of the texmf tree only gave a few hits and none of them I would take as a reference.

**Comment by FrankMittelbach** [comment]
To make my case, here is an excerpt from TLC3 index: more than one page with \Declare and *zero* entries with \Def
[tlc3-pages.pdf](https://github.com/lvjr/tabularray/files/7229514/tlc3-pages.pdf)
.

**Comment by lvjr** [comment]
It is unfair to only compare uppercase `Def` with `Declare`. Why should we ignore `def` and `define`? I don't think any of the above `Declare` commands is more popular than these three commands: 

- `\definecolor`
- `\define@key`
- `\defbeamertemplate`

But none of them is included in `tlc3-pages.pdf` file. So I think basically it is impossible to make a decision that everyone agrees with.

**Comment by FrankMittelbach** [comment]
`\define@key` is internal and not user facing, the other two are fairly old; basically in the 90' conventions have been lowercase commands but since then the conventions have been basically mixed case and not "Def" but "Declare" and that is what the LaTeX Project Team is promoting. Nobody hinders you do do whatever you like, all I'm saying it is not the recommended way forward these days.

**Comment by lvjr** [comment]
Like `\DeclareFontFamily` and its friends, `\define@key` is mainly for package writers.

Anyway, I can provide both `\Def` and `\Declare` commands. But I guess users will choose to use the former more than the latter.
