### ISSUE TITLE
tabularray doesn't save and restore counters

### ISSUE THREAD

**Issue by u-fischer** [lvjr/tabularray#116]
Commands which process their content more than once e.g. for measuring should take care to restore the counters. tabularray seems to miss that, in the following example the counter is increased by 6:

~~~~
\documentclass{article}
\usepackage{tabularray,amsmath,tabularx}
\newcounter{mycountertest}
\begin{document}
\themycountertest
\begin{align}
 align\refstepcounter{mycountertest}
\end{align}
 
\themycountertest 
 
\begin{tabularx}{4cm}{X}
 tabularx\refstepcounter{mycountertest}
\end{tabularx}
 
\themycountertest
 
\begin{tblr}{c}
 tblr \refstepcounter{mycountertest}\\
\end{tblr}
 
\themycountertest
\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/134542752-a7ec68d3-6657-4c32-8f7e-a45a4d328633.png)

The counters are stored in `\cl@@ckpt`.  `\savecounters@` in amsmath.sty is an example how to use it.

**Comment by davidcarlisle** [comment]
@u-fischer  this is a dup of #83

**Comment by u-fischer** [comment]
@davidcarlisle  oh yes ;-)

**Comment by u-fischer** [comment]
closing as duplicate of #83

**Comment by lvjr** [comment]
Also as a duplicate of issue #89.
