### ISSUE TITLE
"font=" does not work commulative

### ISSUE THREAD

**Issue by rolfn** [lvjr/tabularray#127]
In the following example I set `\sffamily` for all table cells. In addition, I set `\bfseries` for the first row. Apparently this doesn't work on top of `\sffamily` as one might expect. Instead, it first resets the font definition and only then does `\bfseries` take effect. Wouldn't it be better if it acted commulative?

```latex
\listfiles
\documentclass{article}
\usepackage{tabularray}
\begin{document}
\begin{tblr}{colspec={cccc},cells={font=\sffamily},
  row{1}={font=\bfseries}}
  Column 1 & Column 2 & Column 3 & Column 4 \\ \hline
  Alpha    & Beta     & Gamma    & Delta    \\
  Epsilon  & Zeta     & Eta      & Theta    \\
  Iota     & Kappa    & Lambda   & Mu       \\
  Nu       & Xi       & Omicron  & Pi       \\ 
\end{tblr}
\end{document}
```
Thanks in advance.

**Comment by lvjr** [comment]
Maybe we also need another `+font` key which adds font settings to the beginning.
