### ISSUE TITLE
Missing `\therownum` etc. 

### ISSUE THREAD

**Issue by rolfn** [lvjr/tabularray#129]
The counters `rownum`, `colnum`, `rowcount` and `colcount` are not defined by LaTeX's `\newcounter`. This means that e.g. the macro `\therownum` (LaTeX's default: `\@arabic\c@rownum`) is not defined. I think that the user expects this, however. What do you think?

**Comment by lvjr** [comment]
Yes, in version 2021P, these counters were defined by `\int_new:N` instead of `\newcounter` (see issue #89 for the reason). I will add macros `\therownum`, `\thecolnum`, etc back later.
