### ISSUE TITLE
wrong appearance of equation in math or dmath mode

### ISSUE THREAD

**Issue by Zarko1234** [lvjr/tabularray#137]
Please consider the following example:

    \documentclass[border=3.141592]{standalone}
    \usepackage{tabularray}
    \usepackage{bm} % boldface math

    \begin{document}
    \begin{tblr}{colspec={@{}   Q[l, $$] *{3}{Q[c]} @{}},
                 row{1}={font=\bfseries},
                 rowsep={0pt},
                 column{1}={font=\boldmath},
                 }
    n               & 1     & 2     & 3     \\
    y[n]=\sum       & text  & text  & text  \\
    y[n]{{}=\sum}   & text  & text  & text  \\
    \end{tblr}
    \end{document}

Why equation in the second table row is broken into two lines? I expect the same result as in the third table rows.   The same is happen when is used math or dmath mode.

**Edit:**
This happen only if is declared *column{1}={font=\boldmath}*. If it is deleted, formating of equation in the second row is correct. 

**Question:** Is there a way writing of equation with syntax used in the second table row will have the same result as it has in the third row?

![image](https://user-images.githubusercontent.com/89665526/138524495-1d04bcc1-2052-444d-af37-767779708653.png)

**Comment by lvjr** [comment]
This bug is due to the neglect of `font` option in measuring math cells. Now it is fixed.
