### ISSUE TITLE
@ expression not working as usual in math mode

### ISSUE THREAD

**Issue by GitPinkRabbit** [lvjr/tabularray#138]
This code below cannot set the correct space at both sides of `=`.

```latex
$ \begin{tblr}{r @{{}={}} l}
1 & 1
\end{tblr} $
```

And this code achieves the goal.

```latex
$ \begin{tblr}{r @{${}={}$} l}
1 & 1
\end{tblr} $
```

**Comment by GitPinkRabbit** [comment]
Is this a bug or a feature? @lvjr

**Comment by lvjr** [comment]
After comparing it with `array` environment, I think it is a bug.
```latex
$\begin{array}{r @{{}={}} l}
1 & 1
\end{array}$

$\begin{array}{r @{${}={}$} l}
1 & 1
\end{array}$
```

![image](https://user-images.githubusercontent.com/4239949/143264817-f036c411-4fc0-4379-bb9b-799418f21d3b.png)

**Comment by hvoss49** [comment]
> Am 24.11.2021 um 16:16 schrieb lvjr ***@***.***>:
> 
> 
> After comparing it with array environment, I think it is a bug.
> 
> $\begin{array}{r @{{}={}} l}
> 1 & 1
> \end{array}$
> 
> $\begin{array}{r @{${}={}$} l}

You get the correct output!  With the above line you leave the mathmode
write the = outside of math and start again the mathmode with the second $

$\begin{array}{r @{${}={}$} l}. Is the same as

$ 1 $ = $ 1 $

**Comment by lvjr** [comment]
This bug has been fixed.
