### ISSUE TITLE
support for \caption

### ISSUE THREAD

**Issue by albert-github** [lvjr/tabularray#14]
As far as I can see the following is not yet possible
```
\begin{tblr}{*{3}{|X[-1]}|}
\caption{Complex table}
...
```

with the tabu package this was possible like:
```
\begin{longtabu}spread 0pt [c]{*{3}{|X[-1]}|}
\caption{Complex table}
...
```

**Comment by lvjr** [comment]
It's planned to implement a `\caption` command and a `longtblr` environment. Maybe after the feature of table heads and foots.

**Comment by albert-github** [comment]
Isn't the longtblr environment already possible by means of e.g.:
```
\begin{tblr}{long,colspec={*{3}{|X[-1]}|}
```

**Comment by lvjr** [comment]
It's better to use a new environment name since the optional arguments are different (t/c/b vs l/c/r).

**Comment by c-alpha** [comment]
> It's planned to implement a `\caption` command and a `longtblr` environment. Maybe after the feature of table heads and foots.

I would concur with @lvjr that `\caption` would make sense for a `longtblr` environment only. For short tables, one can always use something along the lines of:
```latex
  \begin{table}
     \caption{foo bar\label{tab:foo}}
	\begin{tblr}{...}
          ...
        \end{tblr}
  \end{table}
```

**Comment by lvjr** [comment]
I decided to implement table captions in table heads and footnotes in table foots (see #12). Therefore I will close this issue and we can discuss the table head/foot in #12.
