### ISSUE TITLE
Span cells cause vlines to cross double hlines

### ISSUE THREAD

**Issue by fefrei** [lvjr/tabularray#141]
Consider a document like so:

```latex
\documentclass{article}

\usepackage{parskip}
\usepackage{xcolor}
\usepackage{tabularray}

\begin{document}

\begin{tblr}{colspec={XXXX}, hlines, vlines, hline{2}={2}{-}{solid}}
    A & \SetCell[c=2]{c} B & C & D \\
    E & F & G & H
\end{tblr}

\end{document}
```

The double hlines generally interrupt the vlines. However, where the span cells start and end, the vlines cross the double hlines:

![image](https://user-images.githubusercontent.com/3078885/139457134-f580cce6-3a99-42cb-b908-521eba749b25.png)

Reading through the manual, I didn't find any hint this is intended behavior (or a way to influence it), so I'm guessing this is a bug.

**Comment by lvjr** [comment]
The following is a quick workaround:
```latex
\begin{tblr}{
  colspec={XXXX}, hlines, vlines,
  hline{2}={2}{-}{solid},
  cell{1}{2} = {c=2}{c},
  vline{2,4} = {1}{-}{belowpos=0},
}
  A & B & C & D \\
  E & F & G & H
\end{tblr}
```
![image](https://user-images.githubusercontent.com/4239949/148055273-e1bd5364-9a50-4e7a-83f4-686810a5edca.png)

**Comment by lvjr** [comment]
A related issue was also reported here:

https://tex.stackexchange.com/questions/629000/why-the-vertical-line-in-the-tabularray-table-exceeds-the-horizontal-line
