### ISSUE TITLE
Chinese colon (中文冒号) problem

### ISSUE THREAD

**Issue by wx672** [lvjr/tabularray#142]
Hi, 

The output of the following MWE looks a bit strange. Every row seems align to head as shown in the attached *tmp.pdf* file. But if I change the Chinese colons (double-byte) to English ones (single-byte), the output looks good to me. Any ideas?

```latex
\documentclass[scheme=plain]{ctexart}

\usepackage{tabularray}

\begin{document}

\begin{tblr}{width=\linewidth, colspec={rX[c]rX[c]},%
    cell{1}{2}={c=3}{c},%
    hline{2}={2-4}{},%
    hline{3,4}={2,4}{}}
  论文(设计)题目：& Hello, world!\\
  学生姓名：       & Hello & 学号： & world \\
  学院：           & hello & 专业： & world \\
\end{tblr}

\end{document}
```

[tmp.pdf](https://github.com/lvjr/tabularray/files/7448641/tmp.pdf)

**Comment by lvjr** [comment]
See this issue is the same as #145, and there are more details there, I will close this issue.
