### ISSUE TITLE
tabularray doesn't nest in align

### ISSUE THREAD

**Issue by eg9** [lvjr/tabularray#143]
See https://tex.stackexchange.com/q/620981/4427

```
\documentclass{article}
\usepackage{mathtools}
\usepackage{tabularray}

\begin{document}
\begin{align*}
  \begin{tblr}{cc}
    a & b \\
    x_1 & x_2
  \end{tblr}
\end{align*}
\end{document}
```
This fails because `tblr` is not safely protected inside another alignment using `&` to separate columns.

Proposed fix: add ` \group_align_safe_begin:` and ` \group_align_safe_end:` in the appropriate places.

```
\NewDocumentCommand \NewTblrEnviron { m }
  {
    \tl_new:c { l__tblr_default_ #1 _outer_tl }
    \tl_set_eq:cN { l__tblr_default_ #1 _outer_tl } \l__tblr_initial_tblr_outer_tl
    \tl_new:c { l__tblr_default_ #1 _inner_tl }
    \NewDocumentEnvironment {#1} { O{c} m +b }
      {
        \group_align_safe_begin:
        \__tblr_environ_code:nnnn {#1} {##1} {##2} {##3}
      }
      { \group_align_safe_end: }
    %\ignorespaces
  }
```
The `\ignorespaces` token is out of place, unless you really expect users to do `\NewTblrEnviron` mid-paragraph.

**Comment by lvjr** [comment]
This bug has been fixed (also an `\ignorespaces` is removed).
