### ISSUE TITLE
Line breaking behavior of justified text

### ISSUE THREAD

**Issue by Sonja-K** [lvjr/tabularray#144]
Line breaking behavour in justified `Q` type cells in a `tblr` environment seems to differ from line breaking of the same text inside of a regular `p` type column onr inside of a `minipage`. Is this intended?

![dsgrdgdgdg](https://user-images.githubusercontent.com/30843621/140575468-2063a4b2-d887-4119-8fec-2a240fc7cc1a.png)

```
\documentclass{article}
\usepackage[ngerman]{babel}
\usepackage{tabularray}

\begin{document}
\begin{tblr}{@{}Q[j,6cm]}
 Abfall ätzender saurer anorganischer flüssiger Stoff, n.a.g. (Schwefelsäure, Eisensulfat-Lösung), 8, II, (E), umweltgefährdend
\end{tblr}

\begin{tabular}{@{}p{6cm}}
 Abfall ätzender saurer anorganischer flüssiger Stoff, n.a.g. (Schwefelsäure, Eisensulfat-Lösung), 8, II, (E), umweltgefährdend  
\end{tabular}

\begin{minipage}{6cm}
 Abfall ätzender saurer anorganischer flüssiger Stoff, n.a.g. (Schwefelsäure, Eisensulfat-Lösung), 8, II, (E), umweltgefährdend 
\end{minipage}
\end{document}
```

**Comment by hvoss49** [comment]
I cannot see it with up-to-date TeXLive

**Comment by Sonja-K** [comment]
I just updated my MiKTeX distribution and still get the differing line breaking behavior, albeit only if I compile using XeLaTeX.

**Comment by hvoss49** [comment]
Yes, it doesn't happen for `pdflatex` and `lualatex`
