### ISSUE TITLE
Extra empty line when line ends with a full-width punctuation

### ISSUE THREAD

**Issue by glatavento** [lvjr/tabularray#145]
Under specific conditions an additional blank line is added under cell when the cell ends with a full-width east asian punctuation.

MWE

```latex
\documentclass{ctexart}
\usepackage{tabularray}

\begin{document}
\begin{tblr}{colspec={X[l]},width=10.7em}
  \hline
  天地玄黄，宇宙洪荒   \\
  日月盈昃，辰宿列张。 \\
  寒来暑往，秋收冬藏， \\
  闺余成岁，律吕调阳 \\
  \hline
  Lore ipsum dolor sit，\\
  consectetur lllliiis llit, \\
  \hline
\end{tblr}
\end{document}
```

Output

![image](https://user-images.githubusercontent.com/76601050/140635629-40e99348-6282-4fda-be6f-1b2225a335de.png)

[tabularray.pdf](https://github.com/lvjr/tabularray/files/7491874/tabularray.pdf)

(built on linux with latest miktex)

**Comment by glatavento** [comment]
Some other test cases

LuaLaTeX + ltjarticle

```latex
\documentclass{ltjarticle}
\usepackage{tabularray}

\begin{document}
\begin{tblr}{colspec={X[l]},width=8.43em}
  \hline
  寿限無、寿限無。 \\
  五劫の擦り切れ， \\
  海砂利水魚の、 \\
  水行末、雲来末、\\
  \hline
  Lore ipsum dor，\\
  consectetur elit, \\
  \hline
\end{tblr}
\end{document}
```
![image](https://user-images.githubusercontent.com/76601050/140636620-1ac5c0ca-6225-4181-9e6c-eefa0ad5dc51.png)

LuaLaTeX + bxjsarticle

```latex
\documentclass[lualatex,ja=standard]{bxjsarticle}
\usepackage{tabularray}

\begin{document}
\begin{tblr}{colspec={X[l]},width=8.14em}
  \hline
  寿限無、寿限無。 \\
  五劫の擦り切れ， \\
  海砂利水魚の、 \\
  水行末、雲来末、\\
  \hline
  Lore ipslm dor，\\
  consectetur elit, \\
  \hline
\end{tblr}
\end{document}
```

XeLaTeX + bxjsarticle

```latex
\documentclass[xelatex,ja=standard]{bxjsarticle}
\usepackage{tabularray}

\begin{document}
\begin{tblr}{colspec={X[l]},width=8.13em}
  \hline
  寿限無、寿限無。 \\
  五劫の擦り切れ， \\
  海砂利水魚の、 \\
  水行末、雲来末、\\
  \hline
  Lore ipsum dor，\\
  consectetur elit, \\
  \hline
\end{tblr}
\end{document}
```

**Comment by wx672** [comment]
issue #142 is similar to this one.

**Comment by muzimuzhi** [comment]
@glatavento As a workaround, use a wider width.

With the default setting `colsep=6pt`, the max width of a cell content in your one-col tabular (`colspec={X[l]},width=10.7em`) is `10.7em - 2 * 6pt`, which is narrower than `日月盈昃，辰宿列张。`, but just a little wider than `日月盈昃，辰宿列张.` (`。` replaced with `.`).

Also not the `Overfull \hbox` bax box lines in `.log`.

**Comment by lvjr** [comment]
I tried the following test file with PDFLaTeX, XeLaTeX and LuaLaTeX:

```latex
\documentclass{ctexart}

\usepackage{tabularray}

\begin{document}

\tabcolsep=0pt
\begin{tabular}{l}
  \hline
  天地玄黄，宇宙洪荒   \\
  日月盈昃，辰宿列张。 \\
  寒来暑往，秋收冬藏， \\
  闺余成岁，律吕调阳 \\
  \hline
\end{tabular}
\qquad
\begin{tblr}{colsep=0pt,rowsep=0pt,colspec={l}}
  \hline
  天地玄黄，宇宙洪荒   \\
  日月盈昃，辰宿列张。 \\
  寒来暑往，秋收冬藏， \\
  闺余成岁，律吕调阳 \\
  \hline
\end{tblr}

\end{document}
```

With PDFLaTeX: 
![image](https://user-images.githubusercontent.com/4239949/150259475-0132db86-85d1-40b7-a151-5a749a23a464.png)

With XeLaTeX:
![image](https://user-images.githubusercontent.com/4239949/150259965-e311dd6c-cbd5-4d40-9dcf-84a8ecfc273a.png)

Wirh LuaLaTeX:
![image](https://user-images.githubusercontent.com/4239949/150260454-5a7f4421-1dde-4a26-b307-15d2f68ca4c2.png)

**Comment by lvjr** [comment]
As a workaround, adding `\kern-0,5em` after full-width punctuations will get the same result with PDFLaTeX, XeLaTeX and LuaLaTeX:

```latex
\documentclass{ctexart}

\usepackage{tabularray}

\begin{document}

\tabcolsep=0pt

\begin{tabular}{l}
  \hline
  天地玄黄，宇宙洪荒 \\
  日月盈昃，辰宿列张。\kern-0.5em \\
  寒来暑往，秋收冬藏，\kern-0.5em \\
  闺余成岁，律吕调阳 \\
  \hline
\end{tabular}
\qquad
\begin{tblr}{colsep=0pt,rowsep=0pt,colspec={l}}
  \hline
  天地玄黄，宇宙洪荒 \\
  日月盈昃，辰宿列张。\kern-0.5em \\
  寒来暑往，秋收冬藏，\kern-0.5em \\
  闺余成岁，律吕调阳 \\
  \hline
\end{tblr}

\bigskip

\begin{tblr}{colspec={X[l]},width=10.7em}
  \hline
  天地玄黄，宇宙洪荒 \\
  日月盈昃，辰宿列张。\kern-0.5em \\
  寒来暑往，秋收冬藏，\kern-0.5em \\
  闺余成岁，律吕调阳 \\
  \hline
  Lore ipsum dolor sit，\kern-0.5em \\
  consectetur lllliiis llit, \\
  \hline
\end{tblr}

\end{document}
```

![image](https://user-images.githubusercontent.com/4239949/150264758-89915051-4e0a-4dad-9fe5-91a5dac47a3a.png)

**Comment by qinglee** [comment]
Tabularray adds a pair of struts to the beginning and end of the cell text by default. Meanwhile, the full-width closing punctuation is always followed by a breakable glue in in CJK/xeCJK/LuaTeX-ja. So when the full-width closing punctuation is at the end of the cell, it may result in an unexpected blank line which contains a strutbox.

To avoid this unexpected breakpoint, we can set `appto=\unkern\unkern\unskip` with CJK, `appto=\unskip` with xeCJK and `appto=\ltjfakeboxbdd` with LuaTeX-ja to remove the glue after the punctuation at the end of a cell.

**Comment by lvjr** [comment]
Thanks! I think I need to add a new library `cjk` for these patches in `tabularray` package in a future release. It seems these patches can not solve the bug reported in issue #257?

**Comment by qinglee** [comment]
> Thanks! I think I need to add a new library `cjk` for these patches in `tabularray` package in a future release. It seems these patches can not fix the bug reported in issue #257?

To #257, we need an extra setting `preto=\ltjfakeparbegin` with LuaTex-ja. CJK is fine and the upcoming new version of xeCJK has fixed that issue.

**Comment by lvjr** [comment]
> To #257, we need an extra setting `preto=\ltjfakeparbegin` with LuaTex-ja. CJK is fine and the upcoming new version of xeCJK has fixed that issue.

Great. Now everything will be perfect.

**Comment by lvjr** [comment]
Maybe we can have an even better solution: it is possible that we don't need to add struts even if stretch>0, because in `tabularray` we can simply set internal data `@row-upper` and `@row-lower` to make minimal heights and depths for rows.

**Comment by qinglee** [comment]
> Maybe we can have an even better solution: it is possible that we don't need to add struts even if stretch>0, because in `tabularray` we can simply set internal data `@row-upper` and `@row-lower` to make minimal heights and depths for rows. See also issue #188.

Indeed, it would be more natural and elegant if we could manipulate cell boxes directly.
