### ISSUE TITLE
Add direct support for executing code per row, not per cell

### ISSUE THREAD

**Issue by muzimuzhi** [lvjr/tabularray#146]
Currently `rows={cmd={<code>}}` will execute `<code>` for every cell, but sometimes users only want `<code>` executed per row, not per cell (to avoid, e.g., the effect of `<code>` accumulates).

In [this TeX-SX answer](https://tex.stackexchange.com/a/621778) I gave an example on how this could be imitated with `col{Z}={cmd={...}}`, but a direct support would be much better.

**Comment by lvjr** [comment]
I think code execution should be implemented as some hooks to `tabularray`. There will be some hooking interfaces  provided to users in the future.

**Comment by lvjr** [comment]
With `functional` library, you can do conditional fomatting for rows (see #81).
