### ISSUE TITLE
Support `xcolor`'s color series

### ISSUE THREAD

**Issue by muzimuzhi** [lvjr/tabularray#147]
To color tables rows with a color series, `tabu` provides `\taburowcolors`, which is a wrapper of `xcolor`'s color series macros, with it's own codes to make the color series really "cycle" (see related discussion [here](https://github.com/latex3/xcolor/issues/9)).

`tabularray` need similar logics to support easier use of color series in setting row (maybe also column) colors. A first attempt which didn't touch any of `tabularray`'s internals (hence would be nothing to do with the final implementation) can be seen [in my TeX-SX answer](https://tex.stackexchange.com/a/621778).

**Comment by lvjr** [comment]
See also https://github.com/lvjr/tabularray/issues/74 for a more general idea about repeating row/column sytles.
