### ISSUE TITLE
Expand multiple commands

### ISSUE THREAD

**Issue by tobiasBora** [lvjr/tabularray#158]
First, thanks for this great package. If I want to expand multiple commands, like `\YES` and `\NO` to setup both the cell background color and the text of my cells, I need to use quite dirty hacks like these ones: https://tex.stackexchange.com/questions/617961/tabularray-expand-multiple-macros/617982#617982

Would it make sense to implement multi-command expansion directly in tabularray? (or at least document the hacks)

**Comment by lvjr** [comment]
See issue #77.
