### ISSUE TITLE
Background images

### ISSUE THREAD

**Issue by tobiasBora** [lvjr/tabularray#159]
In order to visually make difference between cells containing positive or negative values, I wanted to put behind my text an image (like a green tick or a red cross). I guess I can do that by inserting tikz into my cell, but I would need to be quite careful not to break the spacing or to handle lines with multiple columns.

Would it be possible to implement background images? Ideally it would be possible to have different modes, depending on whether I want to:

1. have an image of fixed size, positioned at the center of the cell and cropped if going out of the cell (ideally, one may be able to shift/scale the position in term of percentage of the cell, change the anchor...)
2. have an image stretched in both direction to fit the cell (even if I need to lose my aspect ratio)
3. have an image stretched in both direction, but maintaining the aspect ratio, ensuring the image fits inside the cell
4. have an image stretched in both direction, but maintaining the aspect ratio, ensuring the image fills all the cell
5. an "expert mode", where the user is just provided tikz anchors for the 4 corners of the cell, and then could do any drawing.

Thanks a lot!

**Comment by lvjr** [comment]
This will be addressed with tikz library (see issue #29).
