### ISSUE TITLE
Unwanted line break for some cell text

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#16]
In fixing issue #15, I found another issue:
````latex
\documentclass[11pt]{article}
\usepackage{tabularray}
\begin{document}
\begin{tblr}{ll}
\hline
Src-Addr & Dest-Addr \\
\hline
\end{tblr}
\end{document} 
````
![image](https://user-images.githubusercontent.com/4239949/120879630-678fbf80-c5f7-11eb-9ea8-cae637ac4186.png)

The result is correct if we change font size to `10pt` or `12pt`.

**Comment by lvjr** [comment]
It's a bug of XeTeX engine:
https://tex.stackexchange.com/questions/600010/unwanted-line-break-with-raggedleft-centering-or-raggedright
https://sourceforge.net/p/xetex/bugs/185/
We don't need to fix it here.

**Comment by lvjr** [comment]
With the latest package code, there is a wordaround for XeTeX users:
```latex
\makeatletter
\AddToHook{cmd/TblrAlignBoth/after}{\@rightskip=-1sp \rightskip=\@rightskip}
\AddToHook{cmd/TblrAlignLeft/after}{\@rightskip=-1sp plus 1fil \rightskip=\@rightskip}
\AddToHook{cmd/TblrAlignCenter/after}{\@rightskip=-1sp plus 1fil \rightskip=\@rightskip}
\AddToHook{cmd/TblrAlignRight/after}{\leftskip=-1sp plus 1fil}
\makeatother
```

And it doesn't break any existing test files.

```latex
\documentclass[11pt]{article}
\usepackage{tabularray}
\begin{document}

\begin{tblr}{jj}
\hline
Src-Addr & Dest-Addr \\
Src-Addr & Dest-Addr1111 \\
\hline
\end{tblr}

\begin{tblr}{ll}
\hline
Src-Addr & Dest-Addr \\
Src-Addr & Dest-Addr1111 \\
\hline
\end{tblr}

\begin{tblr}{cc}
\hline
Src-Addr & Dest-Addr \\
Src-Addr & Dest-Addr1111 \\
\hline
\end{tblr}

\begin{tblr}{rr}
\hline
Src-Addr & Dest-Addr \\
Src-Addr & Dest-Addr1111 \\
\hline
\end{tblr}

\bigskip
\makeatletter
\AddToHook{cmd/TblrAlignBoth/after}{\@rightskip=-1sp \rightskip=\@rightskip}
\AddToHook{cmd/TblrAlignLeft/after}{\@rightskip=-1sp plus 1fil \rightskip=\@rightskip}
\AddToHook{cmd/TblrAlignCenter/after}{\@rightskip=-1sp plus 1fil \rightskip=\@rightskip}
\AddToHook{cmd/TblrAlignRight/after}{\leftskip=-1sp plus 1fil}
\makeatother

\begin{tblr}{jj}
\hline
Src-Addr & Dest-Addr \\
Src-Addr & Dest-Addr1111 \\
\hline
\end{tblr}

\begin{tblr}{ll}
\hline
Src-Addr & Dest-Addr \\
Src-Addr & Dest-Addr1111 \\
\hline
\end{tblr}

\begin{tblr}{cc}
\hline
Src-Addr & Dest-Addr \\
Src-Addr & Dest-Addr1111 \\
\hline
\end{tblr}

\begin{tblr}{rr}
\hline
Src-Addr & Dest-Addr \\
Src-Addr & Dest-Addr1111 \\
\hline
\end{tblr}

\end{document} 
```
![image](https://user-images.githubusercontent.com/4239949/150117800-eac34a6c-1c5d-4201-ab31-712eac2a00f7.png)

**Comment by lvjr** [comment]
There were some discussions on this XeTeX bug on tex-live mail list:

https://tug.org/pipermail/tex-live/2024-January/thread.html

https://tug.org/pipermail/tex-live/2024-February/thread.html

**Comment by muzimuzhi** [comment]
> There were some discussions on this XeTeX bug on tex-live mail list:
> 
> https://tug.org/pipermail/tex-live/2024-January/thread.html
> 
> https://tug.org/pipermail/tex-live/2024-February/thread.html

Titled "Bug in 3.141592653-2.6-0.999995 (TeX Live 2023) with fontspec and tabularray?"

**Comment by lvjr** [comment]
> > There were some discussions on this XeTeX bug on tex-live mail list:
> > https://tug.org/pipermail/tex-live/2024-January/thread.html
> > https://tug.org/pipermail/tex-live/2024-February/thread.html
> 
> Titled "Bug in 3.141592653-2.6-0.999995 (TeX Live 2023) with fontspec and tabularray?"

Yes, and some one found a possible fix for the xetex bug.
