### ISSUE TITLE
Can I set odd columns from A to B?

### ISSUE THREAD

**Issue by syvshc** [lvjr/tabularray#160]
As this answer on TEX.SE: https://tex.stackexchange.com/a/624688/180617 

There is a line:

```
\cell{3, 5, 7, 9, 11, 13, 15, 17, 19}{1, 3, 4}  =   {c = 1, r = 2}{c},
```

Is there a way to write it like below?

```
\cell{odd, 3-Y}{1, 3, 4} = {c = 1, r = 2}{c}
```

or like tikz, I can write

```
\foreach \x in {3, 5, 7, ..., 19}
...
```

to get an odd list from 3 to 19. 

I think the latter is an enhance of the parameter of `odd` and `even`. Will there be a such function?

**Comment by lvjr** [comment]
See issue #105.  You will be able to write `odd[3]` and `odd[3-Y]` in the future.

**Comment by lvjr** [comment]
At this time, `odd` is defined as follows:
````latex
\NewChildSelector { odd }
  {
    \int_step_inline:nnnn {1} {2} { \l_tblr_childs_total_tl }
      { \clist_put_right:Nn \l_tblr_childs_clist {##1} }
  }
````
We need to make breaking change if a child selectors can accept an optional argument.

**Comment by syvshc** [comment]
> 

Thanks for your explain,

**Comment by lvjr** [comment]
By the way, you can omit `c=1` if a cell doesn't span multiple columns. It is enough to write `{r=2}{c}`.
