### ISSUE TITLE
How can I split a single cell to a sub-table without combining all other cells?

### ISSUE THREAD

**Issue by syvshc** [lvjr/tabularray#161]
As the title mentioned, if I want to make a table like this 

![image](https://user-images.githubusercontent.com/38098591/145698603-5cab8aeb-11d7-4eb2-a77a-f5783d10f19a.png)

I have to write these code:

```
 \documentclass{article}
\usepackage{tabularray}
\begin{document}
\begin{tblr}{
    hlines, vlines,
    cell{1, 2, 4}{odd} = {c = 2}{c},
    cell{3}{1, 3, 7} = {c = 2}{c},
}
    a & & b & & c & & e & \\
    a & & b & & c & & e & \\
    a & & b & & c & d & e & \\
    a & & b & & c & & e & \\
\end{tblr}
\end{document}
```

There are lots of unused `&`, and the `tblr`'s setting is a little bit complex. How can I just split the cell. Maybe there will be a command like `\SplitCell[c = 2, r = 1]{c}  c & d` ?

**Comment by lvjr** [comment]
You only need to write this:
```latex
\documentclass{article}
\usepackage{tabularray}
\begin{document}

\begin{tblr}{
    hlines, vlines,
    cell{1,2,4}{3} = {c = 2}{c},
}
    a & b & c &   & e \\
    a & b & c &   & e \\
    a & b & c & d & e \\
    a & b & c &   & e \\
\end{tblr}

\end{document}
```

**Comment by lvjr** [comment]
It is too complicated to add this option. Therefore I am not going to do it.

Another solution: set `rowsep = 0pt` and use a sub table:

```latex
\documentclass{article}
\usepackage{tabularray}
\begin{document}

\begin{tblr}{
    hlines, vlines, cells = {c}, rowsep = 0pt,
}
    a & b & c & e \\
    a & b & c & e \\
    a & b & \begin{tblr}{@{}c|c@{}} c & d \end{tblr} & e \\
    a & b & c & e \\
\end{tblr}

\end{document}
```

**Comment by syvshc** [comment]
Thanks, this is also a good solution. Thanks for the nice package :)
