### ISSUE TITLE
TblrLibrary `counter` makes wrong column align

### ISSUE THREAD

**Issue by syvshc** [lvjr/tabularray#162]
like https://github.com/lvjr/tabularray/discussions/83#discussioncomment-1309000

Here is my mwe

```tex
\documentclass{article}
\usepackage{tabularray}
\UseTblrLibrary{counter}
\begin{document}
\newcounter{mycnta}
\setcounter{mycnta}{8}
\newcommand{\mycnta}{\stepcounter{mycnta}\arabic{mycnta}}
\begin{tblr}{
    hlines, 
    vlines, 
    colspec={c}}
    \mycnta \\
    \mycnta \\
    \mycnta \\
\end{tblr}
\end{document}
```

output: 
![image](https://user-images.githubusercontent.com/38098591/146470882-8948499d-29c7-4b99-bc32-9cc27eea9b96.png)

as we can see, `9` is centering, but `10` and `11` are not

**Comment by lvjr** [comment]
It is a strange bug.

**Comment by lvjr** [comment]
This bug has been fixed.
