### ISSUE TITLE
Reset alternating row colors in `longtblr`

### ISSUE THREAD

**Issue by marvlg** [lvjr/tabularray#163]
This is a feature request inspired by this [post ](https://tex.stackexchange.com/questions/625772/how-to-reset-alternating-row-colors-using-xcolor-and-longtable) (originally not for `tabularray` package).

Is it possible to add an option `resetcoloring` to the `longtblr` environment, such that the meaning off `odd` and `even` rows resets after a pagebreak?

**Comment by lvjr** [comment]
I have already give a solution to the post: 

https://tex.stackexchange.com/questions/625772/how-to-reset-alternating-row-colors-using-xcolor-and-longtable/627362#627362
