### ISSUE TITLE
Systematic control of page breaks

### ISSUE THREAD

**Issue by Glenwing** [lvjr/tabularray#165]
Right now, we can manually prevent a page break after a specific row by adding the asterisk at the end, like `\\*`. However, it would be useful to have a way of systematically specifying not to break after certain rows, something like `rows{even} = {nobreak}`.

My use case for this is controlling page breaks in relation to row shading. For instance, in the attached example, the first row of data is white, but after the page break, the first data row is shaded, which looks odd since the header is also shaded, so there are two shaded rows consecutively. I would like for the first row on each page (after the header) to always be white, so it does not interrupt the light-dark-light-dark flow of the row shading by having 2 dark rows in succession.

Right now this can be accomplished by inserting `\\*` after every other row, so that the rows basically come in pairs and the table can only break after a shaded row:
`10 & 0.013\\*`
`20 & 0.021\\`
`30 & 0.047\\*`
`40 & 0.064\\`
`50 & 0.090\\*`
`60 & 0.110\\`
 but obviously this is tedious and a systematic solution is desirable. I did try ``row{even} = {appto = \nopagebreak}`` as well as with ``cmd``, but to  no effect. So it appears that the manual method is the only way at the moment, unless there is another trick I have not though of.

![2021-12-19 #600 (602×1232)](https://user-images.githubusercontent.com/11250765/146690639-4bc6ff1f-afb0-44b6-8065-d516f9434f19.png)

**Comment by lvjr** [comment]
There is an undocumented option `nopagebreak` for preventing page break **before** the specified rows. Therefore specification `row{odd} = {nopagebreak}` is what you are finding.

This option is undocumented because I have been thinking about moving it to `hline` in version 2022. So use it at your own risk.

**Comment by lvjr** [comment]
There will be `pagebreak=yes/auto/no` for `hborder{i}` or `hborder{odd}` in next version.
