### ISSUE TITLE
Provide a way to change presep and postsep for the tblr environment or to remove the caption from the longtblr environment

### ISSUE THREAD

**Issue by cabg2101** [lvjr/tabularray#166]
With package longtable, it's possible to redefine ```\LTpre``` and ```\LTpost``` such that there can be null or negative padding above and below the table. The caption is also optional. This is a combination of parameters that doesn't seem possible for tabularray: either use tlbr with no way to change ```presep``` / ```postsep```, or use longtblr with no way to remove the caption and its padding. Adding one of those options―or even better, both―would improve the vertical padding flexibility.

Adding a negative vertical space _works_, it's just tedious to add it before every table instead of being able to globally configure it.

**Comment by lvjr** [comment]
To remove table heads and foots of `longtblr`, you may write
```latex
\SetTblrTemplate{head,foot}{empty}
```
This are no `presep` and `postsep` for `tblr` since it is an inline element.

**Comment by cabg2101** [comment]
Thank you. Is there any way to remove the spacing left after emptying the head? I have to add ```presep=-24pt``` to get the table to the same height as a longtable with ```\LTpre=0pt```. Is there any cleaner solution?

**Comment by lvjr** [comment]
Please provide a minimal example with `longtblr` and `longtable` in it.

**Comment by cabg2101** [comment]
You can see in the example below that, even with longtblr's head and foot suppressed + ```presep=0pt```, some space is left between the title rule and the table.

```latex

\documentclass[letterpaper,12pt]{article}

\usepackage{longtable}
\usepackage{tabularray}

% Remove presep in longtable
\setlength{\LTpre}{0pt}

% Remove head and foot in longtblr
\DefTblrTemplate{head,foot}{empty}{}
\SetTblrTemplate{head,foot}{empty}

% Subsection as specified in the document I'm working on
\usepackage{titlesec}
\titleformat
    {\subsection}
    {\Large\scshape\raggedright}
    {}{0em}{}
    [{\titlerule[\arrayrulewidth]}]

% Suppressing subsection space to clearly see the difference between the two table environments
\titlespacing{\subsection}{0pt}{0pt}{0pt}

\begin{document}

\subsection{Test}

\begin{minipage}[t]{0.5\textwidth}
    \begin{longtable}{r|l}
        Lorem & ipsum
    \end{longtable}
\end{minipage}%
\begin{minipage}[t]{0.5\textwidth}
    \begin{longtblr}[presep=0pt]{stretch=0, colspec = {r|l}}
        Lorem & ipsum
    \end{longtblr}
\end{minipage}

\end{document}

```

**Comment by lvjr** [comment]
The extra space is from `headsep`, `footsep` and `rowsep`, but not from the `stretch`:

```latex
\documentclass[letterpaper,12pt]{article}

\usepackage{longtable}
\usepackage{tabularray}

% Remove presep in longtable
\setlength{\LTpre}{0pt}

% Remove head and foot in longtblr
\SetTblrTemplate{head,foot}{empty}

\SetTblrOuter[longtblr]{headsep=0pt,footsep=0pt}
\SetTblrInner[longtblr]{rowsep=0pt}

% Subsection as specified in the document I'm working on
\usepackage{titlesec}
\titleformat
    {\subsection}
    {\Large\scshape\raggedright}
    {}{0em}{}
    [{\titlerule[\arrayrulewidth]}]

% Suppressing subsection space to clearly see the difference between the two table environments
\titlespacing{\subsection}{0pt}{0pt}{0pt}

\begin{document}

\subsection{Test}

\begin{minipage}[t]{0.5\textwidth}
    \begin{longtable}{r|l}
        Lorem & ipsum
    \end{longtable}
\end{minipage}%
\begin{minipage}[t]{0.5\textwidth}
    \begin{longtblr}[presep=0pt]{colspec={r|l}}
        Lorem & ipsum
    \end{longtblr}
\end{minipage}

\end{document}
```
![image](https://user-images.githubusercontent.com/4239949/147618318-13902f34-60d6-4b8b-9e7b-2d79a378ada4.png)

**Comment by cabg2101** [comment]
Thanks a lot! This is exactly what I was looking for.
Great package by the way, I will make sure to use it in every project going forward.

**Comment by makecent** [comment]
For somebody who want use the features of  the `longtblr` but meanwhile put it inside the `table` environment. My practice is using the `talltblr` (instead of `longtblr`) and using the `\SetTblrTemplate{head}{empty}` to remove its caption.
