### ISSUE TITLE
longbooktabs environment

### ISSUE THREAD

**Issue by krlmlr** [lvjr/tabularray#170]
that combines the features from the `booktabs` and `longtblr` environments?

Are there other environments where a "long" version would be useful?

**Comment by lvjr** [comment]
You can write `\begin{booktabs}[long]{lcr}` for a long table.

**Comment by krlmlr** [comment]
Thanks. I went with

```tex
\def\longbooktabs{\begin{booktabs}[long]}
\def\endlongbooktabs{\end{booktabs}}
```

for my document. (The table environment is generated, I need a "proper" environment name.)

**Comment by lvjr** [comment]
I have added `longtabs` and `talltabs` environments in the previous commit.
