### ISSUE TITLE
`guard` option when using `siunitx`

### ISSUE THREAD

**Issue by marvlg** [lvjr/tabularray#175]
Consider this example

```
\documentclass{article}

\usepackage{tabularray}
\UseTblrLibrary{booktabs,siunitx}

\begin{document}
  \begin{tblr}{
	colspec={S[table-format=3.1]*{4}{S[table-format=2.1]}},
	row{2}={mode=math},
	cell{1}{2,4}={c=2}{c},
        }
        \toprule
        & {{{Technetium}}} & & {{{Molybdän}}} & \\
        \cmidrule[lr]{2-3} \cmidrule[lr]{4-5}
        {{{\lambda\,/\,\unit{\nm}}}} & {{{\phi_1}}} & {{{\phi_2}}} & {{{\phi_1}}} & {{{\phi_2}}} \\
        \midrule
        663,0 & 12,1 & 14,4 & 13,1 & 16,9 \\
        670,0 & 10,9 & 12,9 & 11,8 & 15,7 \\
        678,0 & 9,1 & 11,4 & 10,3 & 14,6 \\
        684,0 & 8,2 & 10,2 & 9,5 & 13,5 \\
        \bottomrule
  \end{tblr}
\end{document}
```

![grafik](https://user-images.githubusercontent.com/96285851/148946252-fb0ad2e4-5d0b-48e5-9df6-66ce0b431b26.png)

Currently, every `nonnumeric` cell has to be enclosed by triple curly braces. In the spirit of separating format from content, it would to nice to have a key such as

`row{1,2}={nonnumeric}`

The would clean up code quite a bit, as it is very common to have a few `nonumeric` cells in `S` type columns.

**Comment by lvjr** [comment]
In fact, `\newcommand\SiGuard[1]{{#1}}` and `row{1-2} = {cmd=\SiGuard}` solve your problem:

```latex
\documentclass{article}

\usepackage{tabularray}
\UseTblrLibrary{booktabs,siunitx}

\newcommand\SiGuard[1]{{#1}}

\begin{document}
  \begin{tblr}{
    colspec = {S[table-format=3.1]*{4}{S[table-format=2.1]}},
    row{2} = {mode=math},
    cell{1}{2,4} = {c=2}{c},
    row{1-2} = {cmd=\SiGuard},
  }
    \toprule
        & Technetium & & Molybdän & \\
    \cmidrule[lr]{2-3} \cmidrule[lr]{4-5}
        \lambda\,/\,\unit{\nm} & \phi_1 & \phi_2 & \phi_1 & \phi_2 \\
    \midrule
        663,0 & 12,1 & 14,4 & 13,1 & 16,9 \\
        670,0 & 10,9 & 12,9 & 11,8 & 15,7 \\
        678,0 & 9,1 & 11,4 & 10,3 & 14,6 \\
        684,0 & 8,2 & 10,2 & 9,5 & 13,5 \\
    \bottomrule
  \end{tblr}
\end{document}
```

**Comment by marvlg** [comment]
Thanks, this works. Maybe it would still be a usefull option for the keyval interface

**Comment by lvjr** [comment]
If some nonnumeric cell is multiline, e.g. changing `Molybdän` to `{Molybdän\\Molybdän}`, the column width is wrong. It is a known bug (see issue #90)

**Comment by lvjr** [comment]
I will add a new option `guard` for cells/rows/columns, which will enclose cell text with a pair of curly braces, hence guard it from `cmd` option such as a `siunitx` command from `siunitx` library.

**Comment by lvjr** [comment]
It seems I only need to define `guard` as `cmd=`, which removes `cmd` setting for some `S` cells.

**Comment by marvlg** [comment]
I guess that is acceptable. I can't think of a usage for `cmd` option for guarded cells in `S` columns. And there is still the option to guard with triple curly braces, if someone needs to use `cmd`.

**Comment by lvjr** [comment]
I have added `guard` option for `siunitx` library. Now you can write `row{1-2} = {guard}`.
