### ISSUE TITLE
Make booktabs row spacing available in longtblr and talltblr

### ISSUE THREAD

**Issue by turbanisch** [lvjr/tabularray#177]
In regression tables, I would like to have a slightly tighter spacing between the rows containing coefficients and rows containing the corresponding standard errors but keep `tabularray`'s default spacing for everything else (fit statistics etc.). Is there a smarter way to achieve this than in the second table below where I hard-code the rows for which I would like to modify the options `abovesep` and `belowsep`?

The booktabs environment (see table 3) seems to have a tighter spacing by default that can be relaxed using `addlinespace`. However, the disadvantages that I see are 1) the booktabs environment cannot be nested inside a `talltblr` or `longtblr`; and 2) adding the extra line space via the New Interface might be just as cumbersome as my solution in table 2.

Reflecting on a meta-level, regression tables seem to be quite a weird animal consisting of very different sections that might require different styling (such as line spacing, alignment at decimal dot etc) within the same column.

```latex
\documentclass{article}

\usepackage{tabularray}
\UseTblrLibrary{booktabs}

\begin{document}

\begin{table}
\centering
\caption{\texttt{tblr} default spacing}
\begin{tblr}{
colspec={lccc},
}
    \toprule
    & Model 1 & Model 2 & Model 3 \\
    \midrule
    Population & 3.132 & 12.13$^{***}$ & 0.111 \\
    & (1.124) & (4.234) & (0.001) \\
    Distance & 112.234$^{*}$ & 0.011 & 3.333 \\
    & (13.123) & (0.002) & (0.124) \\
    \bottomrule
\end{tblr}
\end{table}

\begin{table}
\centering
\caption{\texttt{tblr} default with reduced spacing between corresponding numbers}
\begin{tblr}{
colspec=lccc,
row{2,4} = {belowsep=0pt},
row{3,5} = {abovesep=0pt}
}
    \toprule
    & Model 1 & Model 2 & Model 3 \\
    \midrule
    Population & 3.132 & 12.13$^{***}$ & 0.111 \\
    & (1.124) & (4.234) & (0.001) \\
    Distance & 112.234$^{*}$ & 0.011 & 3.333 \\
    & (13.123) & (0.002) & (0.124) \\
    \bottomrule
\end{tblr}
\end{table}


\begin{table}
\centering
\caption{\texttt{tblr}'s \texttt{booktabs} environment}
\begin{booktabs}{
colspec=lccc,
}
    \toprule
    & Model 1 & Model 2 & Model 3 \\
    \midrule
    Population & 3.132 & 12.13$^{***}$ & 0.111 \\
    & (1.124) & (4.234) & (0.001) \\
    \addlinespace
    Distance & 112.234$^{*}$ & 0.011 & 3.333 \\
    & (13.123) & (0.002) & (0.124) \\
    \bottomrule
\end{booktabs}
\end{table}


\end{document}
```

**Comment by lvjr** [comment]
See issue #170.
