### ISSUE TITLE
Running documentation file

### ISSUE THREAD

**Issue by hvoss49** [lvjr/tabularray#178]
It takes more than 15 minutes to run the `tabularray` documentation. Is this a know behaviour?
However, you can speed up things if you compile the source code in a separate file
and then insert it with package `pdfpages`.

**Comment by lvjr** [comment]
Yes, this is a known behaviour.  Actually, I compile subfiles inside `manual` folder when I am updating the manual. I can run `texlua manual. lua` to generate `tabularray.tex` from subfiles. And I compile `tabularray.tex` only when I am making a new release.

**Comment by lvjr** [comment]
I have added `CONTRIBUTING.txt`.
