### ISSUE TITLE
Access measuring phase

### ISSUE THREAD

**Issue by cgnieder** [lvjr/tabularray#179]
Many table packages (e.g. `tabularx`, `tabu`, `ltxtable`) have measuring phases which detect column widths etc before actually typesetting the table. Sometimes other packages need to be able to access this phase because their macros change their outcome between first and subsequent typesetting (think of acronyms of the `acro` or `acronym` packages and see https://github.com/cgnieder/acro/blob/master/code/acro.patch.code.tex as an example).

The `tabu` package has `\tabuDisableCommands` for accessing the measuring phase, `\TX@trial` can be patched for `tabularx`, etc.

Is there an official way to do the same for `tabularray`?

**Comment by lvjr** [comment]
At this time, there are no hooks within `tabularray` tables. I will add them one day. As the first step, please provide a minimal unworking example here.

**Comment by cgnieder** [comment]
There is not really a *not working* example. As author or `acro` I'd like to have an interface to `tabularray` so I could add `\acswitchoff` if needed during the measuring phase. You can see why this is necessary here:

```latex
\documentclass{article}
\usepackage{acro}
\usepackage{tabularray}

\DeclareAcronym{ma}{
  short = MA ,
  long  = my acronym
}

\begin{document}

\begin{tblr}{XcX}
  a & MA & b
\end{tblr}

\begin{tblr}{XcX}
  a & \ac{ma} & b
\end{tblr}

\acresetall

\begin{tblr}{XcX}
  a & \acswitchoff\ac{ma} & b
\end{tblr}

\end{document}
```

**Comment by lvjr** [comment]
Currently, the code is a little messy. The function `\__tblr_make_vcell_text` typesets the cell once. And we even don't know whether it is the last time when we are typesetting the cell.

```
\__tblr__builder
   \__tblr_calc_cell_and_line_sizes
      \__tblr_calculate_line_sizes
      \__tblr_calculate_cell_sizes
         \__tblr_get_cell_text
            \__tblr_get_vcell_and_sizes
               \__tblr_make_vcell_text
               \__tblr_make_vcell_text
      \__tblr_compute_extensible_column_widths 
         \__tblr_calculate_cell_sizes (only for X columns)
            \__tblr_get_cell_text
               \__tblr_get_vcell_and_sizes
                  \__tblr_make_vcell_text
                  \__tblr_make_vcell_text
      \__tblr_adjust_sizes_for_span_cells 
         \__tblr_calculate_cell_sizes (only for multicolumn cells)
            \__tblr_get_cell_text
               \__tblr_get_vcell_and_sizes
                  \__tblr_make_vcell_text
                  \__tblr_make_vcell_text
   \__tblr_build_whole
      \__tblr_get_cell_text
         \__tblr_get_vcell_and_sizes
            \__tblr_make_vcell_text
            \__tblr_make_vcell_text
```

**Comment by cgnieder** [comment]
Well, this looks like the right track. This code

```latex
\ExplSyntaxOn
\NewTblrLibrary {acro}
  { \cs_set_protected:Npn \__tblr_save_counters:n ##1 { \acro_switch_off: } }
\ExplSyntaxOff
\UseTblrLibrary {acro}
```
get's the above example to work.

If there was an official hook right before (or after) each `\__tblr_save_counters:n` then I could provide code in `acro`. Right now 

- `\__tblr_save_counters:n` is a private command and
- using `\pretocmd` with it is bound to fail in cases because the `counter` library changes the definition again so execution order matters (also it's mixing interfaces):

```latex
\ExplSyntaxOn
\NewTblrLibrary {acro}
  { \pretocmd \__tblr_save_counters:n { \acro_switch_off: } {} { \fail } }
\ExplSyntaxOff
\UseTblrLibrary {acro}
\UseTblrLibrary {counter}
```

Could you just provide `\l_tblr_before_measurement_tl` (or similar) inserted at all places where `\__tblr_save_counters:n` is placed? Then I could just do

```latex
\tl_put_right:Nn \l_tblr_before_measurement_tl { \acro_switch_off: }
```

in `acro`.

**Comment by lvjr** [comment]
I am sorry, but simply using `\acswitchoff` will get wrong results if you use a acronym multiple times in `tblr`.

```latex
\documentclass{article}

\usepackage{acro}
\usepackage{tabularray}

\DeclareAcronym{ma}{
  short = MA ,
  long  = my acronym
}

\ExplSyntaxOn
\cs_set_protected:Npn \__tblr_save_counters:n #1 { \acro_switch_off: }
\ExplSyntaxOff

\begin{document}
  
\begin{tblr}{hlines,vlines}
  \ac{ma} & \ac{ma}
\end{tblr}

\end{document}
```

![image](https://user-images.githubusercontent.com/4239949/155644617-69820437-6ac5-44fd-a2cd-cc65a6a75139.png)

You **have to** create two new functions as described in my previous comment.

**Comment by lvjr** [comment]
@cgnieder I have added `\lTblrMeasuringBool` to `tabularray` and the following example produces correct result:

```latex
\documentclass{article}

\usepackage{tabularx}
\usepackage{tabularray}

\usepackage{acro}
\DeclareAcronym{ma}{
  short = MA ,
  long  = my acronym
}

\ExplSyntaxOn
\newcommand\myac[1]{\bool_if:NT\lTblrMeasuringBool{\acswitchoff}\ac{#1}}
\ExplSyntaxOff

\begin{document}

\section{tabularx}

\acresetall

\begin{tabularx}{\linewidth}{|X|X|X|}
\hline
  \ac{ma} & \ac{ma} & \ac{ma} \\
\hline
\end{tabularx}

\section{tabularray}

\acresetall

\begin{tblr}{colspec={XXX},hlines,vlines}
  \myac{ma} & \myac{ma} & \myac{ma} \\
\end{tblr}

\end{document}
```

**Comment by muzimuzhi** [comment]
Although 

> Thanks to pull request #265, now `\__tblr_make_vcell_text` is called once when typesetting a cell,

the content of a cell would still be boxed at most twice if cell width is not specified, see code line 3704 below.

https://github.com/lvjr/tabularray/blob/690e67ee175ff7601d0144c84f9a7e9c67573e0b/tabularray.sty#L3694-L3713

The attempt in https://github.com/lvjr/tabularray/issues/179#issuecomment-1399695943

> ```tex
> \newcommand\myac[1]{\IfBooleanT\lTblrMeasuringBool{\acswitchoff}\ac{#1}}
> [...]
> \acresetall
> 
> \begin{tblr}{colspec={XXX},hlines,vlines}
>   \myac{ma} & \myac{ma} & \myac{ma} \\
> \end{tblr}
> ```

worked because cell widths were set by `colspec={XXX}`. Without `colspec={XXX}`, that example failed. In general cases, using `\lTblrMeasuringBool` only is not sufficient to ensure executing some code once per cell.

Hence `tabularray` either needs another boolean or needs to adjust the position where `\lTblrMeasuringBool` is set true.

**Comment by lvjr** [comment]
> Maybe we can add another `\lTblrCellMeasuringBool` boolean.

Then we also need to add hooks `tabularray/trial/cell/before`
and `tabularray/trial/cell/after` which makes coding more complicated.

**Comment by lvjr** [comment]
Even we add another boolean and two hooks, it is still not easy for package writers to use these interfaces correctly.

**Comment by lvjr** [comment]
> the content of a cell would still be boxed at most twice if column width is not specified, see code lines 3700 and 3704 below.
> https://github.com/lvjr/tabularray/blob/690e67ee175ff7601d0144c84f9a7e9c67573e0b/tabularray.sty#L3694-L3713
> 

Maybe we can save the measured box `\l_tmpa_box` when the column width is not specified, and later use the box directly instead of put cell text in box again.

**Comment by lvjr** [comment]
I tried it but tests `library-006` and `table-011` failed with different outputs.

**Comment by lvjr** [comment]
And this method doesn't work well with `verb` option, since with it we need to rescan cell text. Maybe it is the time to remove `verb` option.

```latex
%% #1: cell text; #2: box width
%% All halign commands are defined at the beginning of the file
\cs_new_protected:Npn \__tblr_make_vcell_text:NN #1 #2
  {
    \dim_set:Nn \tex_hsize:D { #2 }
    \TblrParboxRestore
    \cs:w __tblr_halign_command_ \g__tblr_cell_halign_tl : \cs_end:
    \__tblr_leave_vmode:
    \bool_if:NTF \l__tblr_cell_math_mode_bool
      { #1 }
      { \__tblr_rescan_cell_tokens:N #1 }
  }
```

**Comment by lvjr** [comment]
In my first attempt above, some tests failed:
```
failed in l3build: library-006 verb-001
failed in ppmcheckpdf: cell-004 library-006 library-009 table-010 table-011 verb-001
```
Failed test `cell-004` includes some multiline cells. And I think it is impossible to make a vbox and measure its width at the same time without `varwidth` package.
```latex
\cs_new_protected:Npn \__tblr_get_cell_size_with_hbox:
  {
    \tl_set_eq:NN \l_tmpb_tl \l__tblr_c_tl
    \__tblr_insert_braces:N \l_tmpb_tl
    \seq_set_split:NnV \l_tmpa_seq { \\ } \l_tmpb_tl
    \tl_set:Nn \l__tblr_w_tl { 0pt }
    \seq_map_variable:NNn \l_tmpa_seq \l_tmpa_tl
      {
        \__tblr_remove_braces:N \l_tmpa_tl
        \hbox_set:Nn \l__tblr_measured_cell_box
          {
            \l__tblr_f_tl
            \__tblr_rescan_cell_tokens:N \l_tmpa_tl
          }
        \tl_set:Nx \l__tblr_w_tl
          { \dim_max:nn { \l__tblr_w_tl } { \box_wd:N \l__tblr_measured_cell_box } }
      }
  }
```
One solution would be making `hook` library depend on `varwidth` library, and always measuring cells with `vbox` whenever `hook` library is loaded.

**Comment by lvjr** [comment]
It is a pity `varwidth` package is unmaintained now. Hope someone would rewrite it with LaTeX3 someday.

**Comment by lvjr** [comment]
My second attempt above makes changes only when `hook` and `varwidth` library are loaded, so no tests fail, since we don't test `hook` library at present.

In `hook` branch, `hook` library is loaded in all test files. And lots of tests [failed](https://github.com/lvjr/tabularray/commit/c7862e263677f94067c8c5067831b3ccc76be558):
```
failed in l3build: table-004, table-011 
failed in ppmcheckpdf: cell-001, cell-002, cell-003, cell-004, cell-005, cell-006, cell-007, cell-009, cell-010, cell-011, color-001, color-002, color-003, color-005, extra-001, extra-002, hvline-001, hvline-002, hvline-003, hvline-004, library-001, library-002, library-003, library-005, library-006, library-007, library-008, library-009, library-010, library-011, library-014, library-015, long-002, long-007, long-008, rowcol-001, rowcol-002, rowcol-003, rowcol-004, table-001, table-002, table-003, table-004, table-005, table-006, table-007, table-009, table-010, table-011, table-012, table-013
```

**Comment by lvjr** [comment]
After previous two commits, only four tests fail in `hook` branch:
```
failed in l3build: table-011 
failed in ppmcheckpdf: cell-004, library-009, table-010, table-011
```

**Comment by lvjr** [comment]
In recent commits, I have made `l3build` also check `hook` library by using a separate `regression-test.cfg` file. But `ppmcheckpdf` only check files in `build/test` folder, so I need to update it first.

**Comment by muzimuzhi** [comment]
May I ask for which part of the current `varwidth` is considered not reliable?

**Comment by lvjr** [comment]
There are several bugs with it. One of them is the problem with `\color` in it which could be found from one of the failed test.

**Comment by muzimuzhi** [comment]
OK. So what's indeed needed is a bug fix version of `varwidth`, but not necessarily a latex3-rewritten one.

**Comment by lvjr** [comment]
And both LaTeX `firstaid` and `hyperref` package patch `varwidth`, but the patches haven't been incorporated into it for some time.

**Comment by lvjr** [comment]
After applying `\lastbox` trick I learned from `varwidth` package, the only failed test is `table-011`, which is about `itemize` environment and `\color` command.

**Comment by lvjr** [comment]
It seems for `itemize` environment `measure=vstore` produces better result than `measure=vbox` does.

![image](https://github.com/user-attachments/assets/2d37ba5a-c7b2-4abf-887a-5c4a5b1b232d)

**Comment by lvjr** [comment]
It is similar to the differences between `\parbox` and `minipage`:

https://tex.stackexchange.com/questions/6472/parbox-vs-minipage-differences-in-applicability
