### ISSUE TITLE
hborder and vborder options

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#183]
The existing `hline`/`vline` option can only be used to set one border line at specified position, therefore has some limitations. I am planning to add two new options `hborder` and `vborder` for holding the following border specifications (take `hborder` as an example):

1. `hborder{i} = {linecount=3}` or `hborder{i} = {linecount=0}` will set the total number of hlines (see #66).
2. `hborder{i} = {pagebreak}` or `hborder{i} = {nopagebreak}` will allow or prevent pagebreak at this position (see #165).

**Comment by marvlg** [comment]
I agree, that these options are usefull. However, I am not so sure about the interface to implement them.

I find the names `hborder` and `vborder` not very intuitive. Also, I don`t really see a need for an extra key option for the new features. The `linecount` option could be incorperated into `hline` in my opinion. And the `pagebreak` and `nopagebreak` option belong to the `row`  key, in my opinion.

Making an extra key with only two options is more confusing in my opinion. Also for `vborder`, the pagebreak options would not even exist.

**Comment by lvjr** [comment]
By default, `\hline` or `hline{i}` always draws a new hline, so it is weird to say `\hline[linecount=0]`.

Absolutely the `pagebreak` option belongs to `hborder` because we also need it even if there is not any hline in a long table.

And imagine the future when `tabularray` could break a row with long cell text into two pages just like Microsoft Word does. At that time we will need `pagebreak` option for rows.

Also imagine in the future there will be a `widetblr` environment for breaking a very wide table with many columns into multiple pages. Then we will need `pagebreak` option for `vborder`.

At last, there will be a `baseline` option for `hborder` for vertically aligning a table at the specified position (see #72).
