### ISSUE TITLE
tabularray incompatibility with hyperref

### ISSUE THREAD

**Issue by tomh-overleaf** [lvjr/tabularray#187]
Even this simple doc produces a warning:
```
\documentclass{article}

\usepackage{tabularray}
\usepackage{hyperref}

\begin{document}

Hello, world!

\end{document}
```

The order of the packages doesn't matter, the warning persists.

> ```% Package hyperref Warning: Invalid value `000' for option `pdfborder'. Option setting is ignored on input line 6.```

**Comment by tomh-overleaf** [comment]
Sorry, turns out it's been fixed.

**Comment by lvjr** [comment]
It is fixed in issue #33.

**Comment by lvjr** [comment]
@tomh-overleaf Will Overleaf update `tabularray` package to latest version 2021Q soon?

**Comment by tomh-overleaf** [comment]
> @tomh-overleaf Will Overleaf update `tabularray` package to latest version 2021Q soon?

We in general prefer not to upgrade the existing TeX Live images (for _every_ change breaks _something_), so we do it only for critical bug fixes.

We'll definitely have it in TeX Live 2022 (planned on the 3rd quarter).

**Comment by lvjr** [comment]
Ok, thanks for the info.
