### ISSUE TITLE
Upper horizontal line covered by background colour

### ISSUE THREAD

**Issue by mhabets** [lvjr/tabularray#193]
Looks like upper horizontal lines are located below cell background color so that the later may hide the lines as in below screenshots (may be only on Acrobat).
![image](https://user-images.githubusercontent.com/2016449/152647016-0aef42f0-200c-471b-a11b-cb8880fa5908.png)
![image](https://user-images.githubusercontent.com/2016449/152647027-4a900f09-68fd-43e5-a16c-37bb450f3326.png)
```latex
\begin{tblr}{
  colspec={Q[l]Q[c]Q[r]},
  rowspec={|Q|Q|Q|},
  cell{2}{2} = {yellow7}
}
 Alpha & Beta & Gamma \\
 Epsilon & Zeta & Eta \\
 Iota & Kappa & Lambda \\
\end{tblr}
```

**Comment by lvjr** [comment]
You need to update your tabularray package first.

**Comment by mhabets** [comment]
Working like a charm indeed with latest version. Apologies, I should have updated first.
