### ISSUE TITLE
hyperref affects enumerate inside varwidth

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#196]
After loading `hyperref` package, we can not correctly measure an `enumerate` with `varwidth` environment. The problem occures only when we compile code with PDFLaTeX or LuaLaTeX. It is a bug of `hyperref` or `varwidth`, but we could work around it by enclosing `varwidth` with `NoHyper` environment in measuring cell widths, because I think the widths are independent of `hyperref`. 

See https://github.com/latex3/hyperref/issues/204 and [TeX.SE/612306](https://tex.stackexchange.com/questions/612306/hyperref-package-affects-enumerate-inside-varwidth).

**Comment by lvjr** [comment]
But still there is extra vertical space before an enumerate caused by `hyperref`. A user has to remove it by using the [workaround](https://tex.stackexchange.com/questions/423014/hyperref-insert-spurious-space-before-list-and-minipage/489861#489861) given by Ulrike Fischer:
```latex
\makeatletter
\newcommand\nohyperitem{\measuring@true\item\measuring@false}
\makeatother
\begin{tblr}{
  colspec = {ll}, hlines, vlines,
  measure = vbox, stretch=-1,
}
  text & text \\
  \begin{enumerate}[nosep]
    \nohyperitem text 1
    \item text 2
  \end{enumerate} & oooo \\
\end{tblr}
```

**Comment by muzimuzhi** [comment]
> ```tex
> \newcommand\nohyperitem{\measuring@true\item\measuring@false}
> ```

Starting with `hyperref` v7.01a (2023-06-25), `amsmath` is required to make this trick work. See also #444.

**Comment by muzimuzhi** [comment]
FYI: Starting with hyperref [v7.00o](https://github.com/latex3/hyperref/releases/tag/release-7.00o) (2022-03-15), internals `\measuring@true` and `\measuring@false` can be replaced with new user commands `\LinkTargetOn` and `\LinkTargetOff`. See https://github.com/lvjr/tabularray/issues/444#issuecomment-1784221945 and updated [TeX.SX/a/489861](https://tex.stackexchange.com/a/489861).
