### ISSUE TITLE
Setting fonts?

### ISSUE THREAD

**Issue by c-alpha** [lvjr/tabularray#2]
Is there a way to set the font for any given row, column, or cell?

My use-case is that I want to set
```latex
\tableheaderfont\color{white}
```
for the first row.

**Comment by lvjr** [comment]
You could use `>` to add commands of fonts and foregroud colors in `colspec` and `rowspec` options of the `tblr` environment.
I will add more option keys to rows/columns/cells for this in the near future.
````latex
\documentclass{article}
\usepackage{xcolor}
\usepackage{tabularray}
\begin{document}
\begin{tblr}{
  colspec={>{\bfseries}lcr},
  rowspec={>{\Huge\selectfont\color{blue3}}Q[t]Q[m]Q[b]},
}
\hline
 Alpha   & Beta  & Gamma    \\
\hline
 Epsilon & Zeta  & Eta      \\
\hline
 Iota    & Kappa & Lambda   \\
\end{tblr}
\end{document}
````
![image](https://user-images.githubusercontent.com/4239949/118571839-931a4980-b7b1-11eb-9c51-edc8c23a826e.png)

**Comment by c-alpha** [comment]
Thanks for the swift response, and most helpful hint!

So with this LaTeX code:
```latex
\begin{table}[H]
   \caption{A simple table with a slightly longer caption to see where the wrapping margin is and how it is handled with respect to layout and aesthetic impression
     \label{tab:short-table-example}}
  \begin{center}
     \begin{tblr}{
	  colspec  = {lcr},
	  row{odd} = {bg=table-row},
	  row{1}   = {c,bg=header-blue},
	  rowspec  = {>{\tableheaderfont\color{white}}Q},
	}
	Alpha & Beta    & Gamma \\
	Delta & Epsilon & Zeta \\
	Eta   & Theta   & Iota \\
	Kappa & Lambda  & Mu \\
	Nu Xi Omikron & Pi Rho Sigma & Tau Upsilon Phi \\
     \end{tblr}
  \end{center}
\end{table}
```

I get this output:
<img width="560" alt="Screenshot 2021-05-18 at 16 57 50 " src="https://user-images.githubusercontent.com/2213269/118674608-34c58900-b7fa-11eb-898f-bf73ce188530.png">
And which is **exactly** what I wanted to achieve.

I'm using this as part of my style file for defining my own table environment, so I don't know the number of rows. It seems that if I omit the second and further rows from the `rowspec`, the `tabularray` "does the right thing", i.e. does not apply any formatting based on the `rowspec` alone, but retains any other formatting specified. 

-----
In the spirit of my example, I think a user interface along the lines of
```latex
     \begin{tblr}{
	  colspec  = {lcr},
	  row{odd} = {bg=table-row},
	  row{1}   = {c,bg=header-blue,fg=white,fn=tableheaderfont},
	}
```
would seem intuitive to me. As we already have `bg` (background), adding `fg` for foreground, and `fn` for font could seen logical to me.

Since my immediate issue is solved, I'd be happy for you to close this issue, If you wish, or keep it open as a reminder for yourself. Please do as you prefer.

**Comment by emanuelenardi** [comment]
Together with the solution proposed by @c-alpha for local table settings, I would like to suggest the implementation of global options for all tables in the document.

Such as in the solution proposed on [this answer](https://tex.stackexchange.com/a/4848/127473), one could write `\SetTblrDefault{headerfont=bfseries}` for making all table headers bold.

**Comment by lvjr** [comment]
It has been true since the first public release of `tabularray` that **all** table settings can be put in `\SetTblrDefault`. And I'm not going to break this good feature in the future releases.

**Comment by lvjr** [comment]
I have added `fg` and `font` options to cells/rows/columns. You may download the latest package file
https://github.com/lvjr/tabularray/raw/main/tabularray.sty
and test whether there are other problems.
````latex
\begin{tblr}{
 colspec  = {lcr},
 row{odd} = {bg=azure7},
 row{1}   = {c,bg=azure3,fg=white,font=\sffamily},
}
 Alpha & Beta    & Gamma \\
 Delta & Epsilon & Zeta \\
 Eta   & Theta   & Iota \\
 Kappa & Lambda  & Mu \\
 Nu Xi Omikron & Pi Rho Sigma & Tau Upsilon Phi \\
\end{tblr}
````
![image](https://user-images.githubusercontent.com/4239949/120089690-3f9fe800-c12f-11eb-8a5b-ec3a4389befb.png)

**Comment by c-alpha** [comment]
Apologies for my delay in getting back to you, and thanks a lot for your swift action.

This works **perfectly**!
