### ISSUE TITLE
\relax after \\ or \hline creates column bunching

### ISSUE THREAD

**Issue by autoditactics** [lvjr/tabularray#20]
For tblr and other tabular environments, adding square brackets to cells makes latex think you're passing an argument to line breaks `\\` or to `hline`. This can be avoided by adding `\relax`, but doing this in tblr makes the first column cells appear merged together into one long cell for some reason. For example,

```
\begin{tblr}{c|cccc}
	\times & [1] & [2] & [3] & [4]\\\relax
	\hline\relax
	[1] & [1] & [2] & [3] & [4]\\\relax
	[2] & [2] & [4] & [1] & [3]\\\relax
	[3] & [3] & [1] & [4] & [2]\\\relax
	[4] & [4] & [3] & [2] & [1]
\end{tblr}
```

causes the first column to be bunched up like `[1][2][3][4]`. Is there a better workaround for this situation for tabularrays?

**Comment by lvjr** [comment]
This is a bug of `tabularray` package. I will fix it later. A workaround is as follows:
````latex
$\begin{tblr}{
  hline{2} = {solid},
  vline{2} = {solid},
  cell{1}{2-5} = {preto={[}, appto={]}},
  cell{2-5}{-} = {preto={[}, appto={]}},
}
  \times & 1 & 2 & 3 & 4 \\
  1      & 1 & 2 & 3 & 4 \\
  2      & 2 & 4 & 1 & 3 \\
  3      & 3 & 1 & 4 & 2 \\
  4      & 4 & 3 & 2 & 1
\end{tblr}$
````
![image](https://user-images.githubusercontent.com/4239949/121759599-01f08580-cb59-11eb-8d9b-b87bdb098175.png)

**Comment by lvjr** [comment]
This bug should has been fixed. You may download the latest package file
https://github.com/lvjr/tabularray/raw/main/tabularray.sty
and test whether there are other problems.
````latex
$\begin{tblr}{c|cccc}
 \times & [1] & [2] & [3] & [4] \\
\hline\relax
 [1] & [1] & [2] & [3] & [4] \\\relax
 [2] & [2] & [4] & [1] & [3] \\\relax
 [3] & [3] & [1] & [4] & [2] \\\relax
 [4] & [4] & [3] & [2] & [1]
\end{tblr}$
````
![image](https://user-images.githubusercontent.com/4239949/121801676-1ae95b80-cc6b-11eb-937d-7762abdb939e.png)
