### ISSUE TITLE
aligment problem with tables

### ISSUE THREAD

**Issue by lsq** [lvjr/tabularray#206]
在参考tabularray 文档中5.6节Library varwidth，使用如下代码生成的PDF，最后两行对齐出问题
``` tex
\documentclass{standalone}
\usepackage{ctex}

\usepackage{enumitem}
\usepackage{tabularray}
\UseTblrLibrary{varwidth} 

\begin{document}
%\SetTblrInner{rowsep=0pt}
\begin{tblr}{
		hlines,vlines,rowspec={Q[c,m]Q[l,m]Q[l,m]Q[c,m]},
		measure=vbox,stretch=-1,
	}
	\emph{部门} & \emph{完成内容} & \emph{完成时间} & \emph{负责人}\\
	PMC &
	\begin{enumerate}[label=\arabic*、, nosep, topsep=0pt]
		\item 确认上月实际完工工单
		\item 确认系统完工未领料工单，并处理领料（日期）
		\item 确认完工工单在制物料情况，提供生产退料数据给生产部物料组
		\item 检查上月系统生产汇报单工时、加工类型、汇报单下推入库单跨月情况
		\item 结案所有完工工单（包括委外工单）
		\item 导出本月生产入库单，检查入库类型并提供给财务
	\end{enumerate} & 每月3日前 & a \\
	生产部 &
	\begin{enumerate}[label=\arabic*、, nosep]
		\item 清理产线完工工单，完成所有完工工单汇报入
		\item 根据PMC提供完工工单在制数据，安排生产退料
		\item 完成所有生产汇报工时正确录入、加工类型
		\item 提供库存返修实际工时报价
	\end{enumerate} & 每月3日前 & b \\
	品质部 & 
	\begin{enumerate}[label=\arabic*、, nosep]
		\item 优先检验月末生产汇报入库成品，保证不影响PMC导出成品入库数据及报价
		\item 优先检验处理月末PMC提供工单在制生产退料		
	\end{enumerate} & 每月3日前 & c \\
	仓储部 & 
	\begin{enumerate}[label=\arabic*、, nosep]
		\item 优先审核上月末生产入库单据、生产退料单据
		\item 检查上月物料收发明细，处理负库存
	\end{enumerate} & 每月3日前 & d\\
	工程部 & 
	\begin{enumerate}[label=\arabic*、, nosep]
		\item 根据PMC提供入库数据提供报价
		\item 提供售后返修实际工时报价
	\end{enumerate} & 每月5日前 & e\\	

\end{tblr}

\end{document}
```
![图片](https://user-images.githubusercontent.com/1617256/156337494-030cc596-bb09-456e-84e8-392bca41a195.png)

**Comment by lvjr** [comment]
You table has six rows, but with `rowspec={Q[c,m]Q[l,m]Q[l,m]Q[c,m]}` only four rows are styled. You need to change it to `rowspec={Q[c,m]Q[l,m]Q[l,m]Q[l,m]Q[l,m]Q[l,m]}` or `rowspec={Q[c,m]*{5}{Q[l,m]}}`.

PS, please always use English here to make other users understand your question.

**Comment by lsq** [comment]
> You table has six rows, but with `rowspec={Q[c,m]Q[l,m]Q[l,m]Q[c,m]}` only four rows are styled. You need to change it to `rowspec={Q[c,m]Q[l,m]Q[l,m]Q[l,m]Q[l,m]Q[l,m]}` or `rowspec={Q[c,m]*{5}{Q[l,m]}}`.
> 
> PS, please always use English here to make other users understand your question.

How to center the last column ? And how to set each column style in each row

**Comment by lvjr** [comment]
> How to center the last column ? And how to set each column style in each row

For one column add `column{4}={c}`. For one cell add `cell{6}{4}={c}`.
