### ISSUE TITLE
\tabularnewline not recognized

### ISSUE THREAD

**Issue by JeT76-ESCP** [lvjr/tabularray#209]
Based on this [TeX.SE question](https://tex.stackexchange.com/questions/636553/tabularray-incompatible-with-tabularnewline?noredirect=1#comment1586431_636553)

![image](https://user-images.githubusercontent.com/51879086/157640649-65c27773-e7aa-4ad2-9658-318697c6ede0.png)

```
\documentclass{article}
\usepackage{tabularray}
\UseTblrLibrary{booktabs}

\begin{document}

\section{All good here}

\begin{tblr}{lccr}
\hline
 Alpha & Beta & Gamma & Delta \\
\hline
 Epsilon & Zeta & Eta & Theta \\
\hline
 Iota & Kappa & Lambda & Mu \\
\hline
\end{tblr}

\section{Pb here}

\begin{tblr}{lccr}
\hline
 Alpha & Beta & Gamma & Delta \tabularnewline 
\hline
 Epsilon & Zeta & Eta & Theta \tabularnewline 
\hline
 Iota & Kappa & Lambda & Mu \tabularnewline 
\hline
\end{tblr}

\end{document}
```

PS : am a fan of tabularray ! thank you for it

**Comment by lvjr** [comment]
I have given an [answer](https://tex.stackexchange.com/questions/636553/tabularnewline-not-recognised-in-tabularray/647461#647461) to this question on TeX.SE.
