### ISSUE TITLE
How to remove the caption of longtblr and stop it's counter?

### ISSUE THREAD

**Issue by registor** [lvjr/tabularray#214]
Hi,

How to remove the caption of longtblr and stop it's counter? 

Can I put longtblr in table and set it's caption?

The MWE is:
```tex
\documentclass[12pt]{article}

\usepackage{tabularray}

\begin{document}
  \begin{longtblr}[
    caption={Test},
  ]{|X|X|X|X|}
  1 &  1  &  1  &  1 \\
  2 &  2  &  2  &  2 \\
  3 &  3  &  3  &  3 \\
  \end{longtblr}

  \begin{table}
    \caption{test2}
    \begin{longtblr}{|X|X|X|X|}
      1 &  1  &  1  &  1 \\
      2 &  2  &  2  &  2 \\
      3 &  3  &  3  &  3 \\
    \end{longtblr}    	
  \end{table}

\end{document}
```
![image](https://user-images.githubusercontent.com/13491204/158570907-70741c12-7ea7-48a1-864f-685d4240a9de.png)

Thanks!

**Comment by lvjr** [comment]
You can not put a long table (`longtblr` or `longtable`) inside `table` environment. To remove the caption, you can write
```latex
\SetTblrTemplate{head,foot}{empty}
```

**Comment by registor** [comment]
Thank you very much.
