### ISSUE TITLE
Provide a way to color a cell depending on its content

### ISSUE THREAD

**Issue by dbitouze** [lvjr/tabularray#219]
Would it be possible to provide a way to color (the background or the foreground) of a cell depending on its content, for instance whether it is negative or not, or whether it is less (or greater) a given threshold?

**Comment by lvjr** [comment]
You may try `csvsimple` package. It works well together with `tabularray` package.

**Comment by dbitouze** [comment]
> You may try `csvsimple` package. It works well together with `tabularray` package. (see `csvsimple-l3.pdf`)

Many thanks for the pointer. At a first glance, I have the feeling that `csvsimple` lets you filter globally the rows of the data file, and is not able to let you display all the rows but coloring the background of a given cell depending on its content.

**Comment by lvjr** [comment]
A first glance is not enough.

**Comment by lvjr** [comment]
Now it is possible to do conditional formatting with `functional` library (see #81).
