### ISSUE TITLE
Inconsistent local/global assignments and variables not declared

### ISSUE THREAD

**Issue by dbitouze** [lvjr/tabularray#22]
The compilation of the following file highlights several `expl3` problems in the `tabularray`'s code (inconsistent local/global assignments and variables not declared).
```latex
\RequirePackage[check-declarations,enable-debug]{expl3}
\documentclass{article}
\usepackage{tabularray}
\begin{document}
\end{document}
```

**Comment by lvjr** [comment]
Thanks. I will look into it later.

**Comment by dbitouze** [comment]
BTW, more can be caught with:
```latex
\RequirePackage[check-declarations,enable-debug]{expl3}
\ExplSyntaxOn
\debug_on:n { all}
\ExplSyntaxOff
\documentclass{article}
\usepackage{tabularray}
\begin{document}
\end{document}
```

**Comment by muzimuzhi** [comment]
@u-fischer Thanks for your report. I opened #517 to fix all the cases caught by `\debug_on:n { check-declarations }`.
