### ISSUE TITLE
"Unknown column type e!" when `longtblr` themes are used

### ISSUE THREAD

**Issue by dbitouze** [lvjr/tabularray#220]
The following MCE works like a charm except if the `theme = fancy` line is commented out, the error message being:

> ! Package tabularray Error: Unknown column type e!
> 
> Type <return> to continue.
>  ...                                              
>                                                   
> l.31 \end
>          {longtblr}
> ?
> 

```latex
\documentclass{article}
\usepackage{tabularray}

\NewTblrTheme{fancy}{}

\begin{document}
\begin{longtblr}{
    % theme = fancy,
  }
  Foo & Bar
\end{longtblr}
\end{document}
```
Here is my *File List*:

>  article.cls    2021/10/04 v1.4n Standard LaTeX document class
>   size10.clo    2021/10/04 v1.4n Standard LaTeX file (size option)
> tabularray.sty    2022-03-01 v2022A Typeset tabulars and arrays with LaTeX3
>    expl3.sty    2022-02-24 L3 programming layer (loader) 
> l3backend-pdftex.def    2022-02-07 L3 backend support: PDF output (pdfTeX)

**Comment by lvjr** [comment]
You need put `theme=fancy` inside square brackets since it is an outer specification.
