### ISSUE TITLE
How to change color of TblrNote tag?

### ISSUE THREAD

**Issue by Zarko1234** [lvjr/tabularray#224]
As far as I can see, the color of tag in `\TblrNote{a}` is in blue color, but I like to change its color to the same as have text in this row. For example, if row is colored blue, tag is not visible anymore.

I expected, that tag will overtake color of text in this row, but unfortunately this is not a case. An example of this problem can be seen in [https://tex.stackexchange.com/questions/639180/set-column-width-for-q-column-in-tabularray/639220#639220](https://tex.stackexchange.com/questions/639180/set-column-width-for-q-column-in-tabularray/639220#639220), where is used `tabularray` version 2022A.

How to convince `TblrNote` that its tag will be in the same color as is text in row?

**Comment by lvjr** [comment]
`Tabularray` doesn't set color for `\TblrNote`, the color is from `hyperref`.
```
\hypersetup{
  colorlinks = true,
  linkcolor = blue
}
```
You may change `linkcolor` to `red`, for example.

**Comment by Zarko1234** [comment]
Now I see, that using `hyperref` package is source of my problem. Since it set link color to blue,  tags of `TblrNote`s are in considering case not visible anymore. Consequently this color should be changed locally as is now done in addendum. Thank you very much.
