### ISSUE TITLE
Beamer \pause doesn't work with tabularray

### ISSUE THREAD

**Issue by CarLaTeX** [lvjr/tabularray#226]
In `beamer`, with the command `\pause`, you can show one table row at a time.   
With `tabular`, it works perfectly but, with `tlbr`, it produces a strange output.   
Compare the output of the following two frames.
See this post on TopAnswers TeX: https://topanswers.xyz/tex?q=2000.

```
\documentclass{beamer}
\usepackage{tabularray}

\begin{document}
\begin{frame}{With tabular works}
\begin{tabular}{cc}
    first & tabular\pause \\
    second & tabular \\ 
\end{tabular}
\end{frame}
\begin{frame}{With tblr doesn't work}
\begin{tblr}{cc}
    first & tblr\pause \\   
    second & tblr \\ 
\end{tblr}
\end{frame}
\end{document}
```

**Comment by davidcarlisle** [comment]
@CarLaTeX  does that work with `tabularx` ? I'd be surprised if it does, these environments are doing multiple trial settings to determine the layout so making `\pause` work would be very non trivial. In simple cases it's probably possible to make it a no-op on all but the final run, but in general, interleaving beamer's overlays with multiple-pass layout is not easy. (@lvjr  may accept the challenge, but if you posted the same thing to `tabularx` I'd say it was a documented feature)

**Comment by CarLaTeX** [comment]
> @CarLaTeX does that work with `tabularx` ? I'd be surprised if it does, these environments are doing multiple trial settings to determine the layout so making `\pause` work would be very non trivial. In simple cases it's probably possible to make it a no-op on all but the final run, but in general, interleaving beamer's overlays with multiple-pass layout is not easy. (@lvjr may accept the challenge, but if you posted the same thing to `tabularx` I'd say it was a documented feature)

You're right, it does not work with `tabularx`, too.

**Comment by lvjr** [comment]
@davidcarlisle @CarLaTeX  Actually it is complicated to catch `\pause` and change it to beamer overlays inside `tabularray`. Also it violates the principle of separating contents and styles. Therefore I won't do it (In fact, I ever opened issue #54 but closed it this year.)

User @registor of this package has done some tests on beamer overlays. It is not hard to do overlays with `counter` library and `cmd` option:

```latex
\documentclass{beamer}

\usepackage{tabularray}
\UseTblrLibrary{counter}

\begin{document}

\begin{frame}
\frametitle{Show a taularray row by row}
\begin{tblr}{colspec={lll},cells={cmd=\onslide<\arabic{rownum}->}}
 Alpha   & Beta  & Gamma  \\
 Epsilon & Zeta  & Eta    \\
 Iota    & Kappa & Lambda \\
\end{tblr}
\end{frame}

\begin{frame}
\frametitle{Show a tabularray column by column}
\begin{tblr}{colspec={lll},cells={cmd=\onslide<\arabic{colnum}->}}
 Alpha   & Beta  & Gamma  \\
 Epsilon & Zeta  & Eta    \\
 Iota    & Kappa & Lambda \\
\end{tblr}
\end{frame}

\begin{frame}
\frametitle{Show a tabularray cell by cell}
\begin{tblr}{colspec={lll},cells={cmd=\onslide<+->}}
 Alpha   & Beta  & Gamma  \\
 Epsilon & Zeta  & Eta    \\
 Iota    & Kappa & Lambda \\
\end{tblr}
\end{frame}

\end{document}
```

With this method, styles and contents of the tables are still well separated.

**Comment by CarLaTeX** [comment]
Thank you @lvjr for your alternative solutions!
