### ISSUE TITLE
itemize list inside cell?

### ISSUE THREAD

**Issue by baradhili** [lvjr/tabularray#229]
Some of the cells I'd like to put bullet lists into - doing 
```
{
	\begin{itemize}
		\item Sales Forecast
		\item Technical Proposal
		\item Production Forecast
	\end{itemize}
} \\
```
Actually works - but throws an error -  "Something's wrong--perhaps a missing \item. \end"

**Comment by lvjr** [comment]
Please read the [documentation](http://mirrors.ctan.org/macros/latex/contrib/tabularray/tabularray.pdf) first.

**Comment by baradhili** [comment]
well I see itemize in the documentation... but I don't see any requirements that might suggest it wouldn't work... they do turn up in a section about how to make the table look better.. but looking better vs breaking seem to be two different things to me..
