### ISSUE TITLE
Allowing inputting table from external file

### ISSUE THREAD

**Issue by mfontanaar** [lvjr/tabularray#239]
I think it is fairly common and handy when typesetting long tables to input them externally. The easiest way of doing this traditionally with other packages is by using `\input{mytable.tbl}` or, to prevent content being expanded beforehand 
```latex
\makeatletter\let\expandableinput\@@input\makeatother
...
Table environment, header, etc.
...
\expandableinput{mytable.tbl}
```
However this does not work in `tabularray`, and I didn't find a built in method to accomplish this. Is it possible the problem arises because `@@` works differently in LaTeX2e and LaTeX3? I don't know how it could fail otherwise.

MWE:
```latex
\documentclass{article}
\usepackage{tabularray}

\makeatletter\let\expandableinput\@@input\makeatother

\begin{document}

%This works
\begin{longtblr}{
        colspec = {*3{c}}
        }
	\hline[.2em]
        a & b & c\\
        \hline
\end{longtblr}

% This doesn't
\begin{longtblr}{
        colspec = {*3{c}}
        }
	\hline[.2em]
	\expandableinput{test.tex}
	\hline
\end{longtblr}
\end{document}
```
Contents of `text.tex`:
```
a & b & c \\
```
Perhaps an external input command could be added?

By the way, thanks for your work. This is a great package which puts together a lot of otherwise atomized table functionality.

**Comment by lvjr** [comment]
See my [answer](https://tex.stackexchange.com/questions/641441/how-to-input-include-individual-files-as-rows-for-a-table/641608#641608) in TeX.SE and this issue (#81).

**Comment by mfontanaar** [comment]
Sorry about the duplicate. Had read almost the entirety of the reference issue but missed the last message! Thanks a lot!
