### ISSUE TITLE
Use X, Y, Z for the last three childs in childs selectors

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#24]
It would be nice if we could use `row{1-Y}={gray}` in inner specifications.

**Comment by makecent** [comment]
not woring. When I use 
```latext

\begin{tblr}{
colspec = {c c c c X[r] X[r] X[c] X[c]},
hline{1,Z} = {1.5pt}
}
...
```
There would be a `missing number, treated as zero` error. The error will disappear once the `Z` is replaced with real number, e.g.,  `hline{1,8} = {1.5pt}`

**Comment by lvjr** [comment]
@makecent You need to update your `tabularray` package to version 2021M or newer (see the changelog [here](https://github.com/lvjr/tabularray/wiki/ChangeLog#2021-08-01-version-2021m)).

**Comment by makecent** [comment]
> @makecent You need to update your `tabularray` package to version 2021M or newer (see the changelog [here](https://github.com/lvjr/tabularray/wiki/ChangeLog#2021-08-01-version-2021m)).

Wow, thanks for your quick reply! I just found the reason. It's because of the overleaf not supporting the latest `tabularry`:cry:. I am trying to manually upload the latest `.sty`.

This is a amazing work. :+1:
