### ISSUE TITLE
Is it normal for `talltblr` to eat space after `\TblrNote`?

### ISSUE THREAD

**Issue by DangeRS2** [lvjr/tabularray#242]
Hi, Jianrui,

I am using `talltblr` to typeset the `threeparttable`-liked table. However, I find that the space after `\TblrNote` disappears. The MWE is listed as follows.

```latex
\documentclass{article}

\usepackage{tabularray}

\begin{document}

\begin{talltblr}[
    caption = {Long Long Long Long Tabular},
    note{a} = {It is the first footnote.},
    note{$\dag$} = {It is the second long long long long long long footnote.},
]{
    width = \linewidth,
    colspec = {XXX},
    hlines,
}
    Alpha & Beta & Gamma \\
    Epsilon & Zeta & Eta\TblrNote{a} Test \\
    Iota & Kappa & Lambda\TblrNote{$\dag$} Test \\
\end{talltblr}

\end{document}
```
![Snipaste_2022-05-05_22-57-56](https://user-images.githubusercontent.com/49086184/167059576-f3c0d431-50df-4ae2-92b5-a04247999db3.png)

**Comment by lvjr** [comment]
You get similar results with `threepartable` package. This is to makes numbers align well with `siunitx` library.

**Comment by lvjr** [comment]
You get similar results with `threepartable` package. This is to make numbers align well with `siunitx` library.
