### ISSUE TITLE
Support \caption[]{text} and \caption*{text}

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#25]
When we specify `entry=none`, no entry will be write to the List of Tables. And when we specify `label=none`, the package will set `caption-tag` template to `empty`, not create hyper target, and not increase the `table` counter. 

Therefore  `entry=none` is the same as `\caption[]{text}` in `longtable` package, and `entry=none,label=none` is the same as  `\caption*{text}` except for the counter.

**Comment by agvld** [comment]
I'm trying to eliminate the caption of a longtblr environment writing the following code:

`\begin{longtblr}[
%theme = fancy,
caption = {Some title},
entry = none,label=none,
%label = {tblr:test},
]{
colspec = {|X[c,m,0.2]X[c,m,0.4]X[c,m,0.4]|}, width = \linewidth,
rowhead = 1, rowfoot = 1,
}`

However, the caption is not disappearing from the table.

**Comment by lvjr** [comment]
You may write `\DefTblrTemplate{head}{default}{}` to get empty table head.

**Comment by agvld** [comment]
Ok, perfect. Now the caption is off. 
Thank you so much.
