### ISSUE TITLE
some open characters will break line height.

### ISSUE THREAD

**Issue by syvshc** [lvjr/tabularray#257]
Arch Linux
TeX Live 2022
tabularray: 2022A

Here is my mwe:

```latex
\documentclass{ctexart}
\usepackage{tabularray}
\begin{document}
  \begin{tblr}{colspec={cc},hlines}
    test & （ \\
    test & ） \\
    test & ［ \\
    test & ］ \\
    test &【  \\
    test & 】 \\
    test & ( \\ 
  \end{tblr}
\end{document}
```

![image](https://user-images.githubusercontent.com/38098591/171567989-8b29a844-5eee-4c2e-a95e-5a1eae0c9e2c.png)

I don't know how many characters will lead to this problem, please have a check.

**Comment by lvjr** [comment]
I think it is a duplicate of issue #145.

**Comment by qinglee** [comment]
I have partially fixed this issue in xeCJK: https://github.com/CTeX-org/ctex-kit/commit/ba4da26629f00e5ea44172f1e29afe7e43a8e8f4

A temporary workaround is `column{2}={cmd=\mbox}` in your case or increase `rowsep` and set `stretch=0`  to avoid adding struts at the beginning and end of the cell text.

It seems that each cell is typeset six times in tabularray. There may be some measurement confusion in the process.

**Comment by syvshc** [comment]
Thanks @qinglee and I'll close this issue.

**Comment by SainoNamkho** [comment]
> I have partially fixed this issue in xeCJK: [CTeX-org/ctex-kit@ba4da26](https://github.com/CTeX-org/ctex-kit/commit/ba4da26629f00e5ea44172f1e29afe7e43a8e8f4)
> 
> A temporary workaround is `column{2}={cmd=\mbox}` in your case or increase `rowsep` and set `stretch=0` to avoid adding struts at the beginning and end of the cell text.
> 
> It seems that each cell is typeset six times in tabularray. There may be some measurement confusion in the process.

Wraping cells in boxes makes puncutations incorretly aligned
```latex
%!TEX program=xelatex
\documentclass{ctexart}
\usepackage{tabularray}
\begin{document}
  \begin{tabular}{cc}\hline
    test & （ \\\hline
    test & ） \\\hline
    test &［ \\\hline
    test & ］ \\\hline
    test &【  \\\hline
    test & 】 \\\hline
    test & ( \\ \hline
  \end{tabular}
  \begin{tblr}{rowsep=0pt,colspec={cQ[c,cmd=\mbox]},hlines}
    test & （ \\
    test & ） \\
    test &［ \\
    test & ］ \\
    test &【  \\
    test & 】 \\
    test & ( \\ 
  \end{tblr}
\end{document}
```
![image](https://user-images.githubusercontent.com/23036788/171579738-c8cb8196-febd-4138-83bb-1bd2b2c7baf8.png)

**Comment by qinglee** [comment]
@SainoNamkho Add `appto=\unskip` to the second column specification.

**Comment by lvjr** [comment]
> I have partially fixed this issue in xeCJK: [CTeX-org/ctex-kit@ba4da26](https://github.com/CTeX-org/ctex-kit/commit/ba4da26629f00e5ea44172f1e29afe7e43a8e8f4)

@qinglee Good news. Thank you.
