### ISSUE TITLE
Table commands `\pagebreak` and `\nopagebreak` should take an opt-arg

### ISSUE THREAD

**Issue by muzimuzhi** [lvjr/tabularray#259]
Originally reported in https://tex.stackexchange.com/q/646495

**Description**

To allow normal use, either through direct user input or indirect macro expansion, of `\pagebreak` and `\nopagebreak` in `tblr` envs, their table command versions should take an opt-arg as well.

**Example**
```tex
\documentclass{article}
\usepackage{tabularray}

\begin{document}
\begin{tblr}{Q}
    a\pagebreak[0]b
\end{tblr}
\end{document}
```
output: `a[0]b`, noted the surplus `[0]`.

**Proposal**
```diff
diff --git a/tabularray.sty b/tabularray.sty
index bb8d02f..f5a440c 100644
--- a/tabularray.sty
+++ b/tabularray.sty
@@ -2258,12 +2258,12 @@
   }
 \cs_generate_variant:Nn \__tblr_row_unknown_key:n { V }

-\NewTableCommand \pagebreak
+\NewTableCommand \pagebreak [1] [4]
   {
     \hborder { pagebreak = yes }
   }

-\NewTableCommand \nopagebreak
+\NewTableCommand \nopagebreak [1] [4]
   {
     \hborder { pagebreak = no }
   }
```

**Comment by lvjr** [comment]
I think the real bug need to be fixed is issue #31.

**Comment by muzimuzhi** [comment]
#31 is truly better. Then maybe package doc should mention that table commands `\(no)pagebreak` has different syntax from their normal use in latex, that they doesn't take an opt-arg.

**Comment by lvjr** [comment]
This patch can also be applied. Who knows, maybe `tabularray` will be able to use the argument in the future.
