### ISSUE TITLE
Filling color misalignment in merged cells with tabularray in LaTeX

### ISSUE THREAD

**Issue by earthmoon** [lvjr/tabularray#276]
The background color of a merged cell is misaligned when there is a page break with the tabularray package in LaTeX.
![image](https://user-images.githubusercontent.com/45897471/178436785-3134b8fc-4a30-4b64-a3f1-8a01bcd7b64d.png)

> \documentclass{article}
> \usepackage{tabularray,tabularx,xcolor}
> \UseTblrLibrary{booktabs, siunitx}
> \definecolor{tablebackground}{RGB}{245,246,246}
> \SetTblrInner[longtblr]{cells={bg=tablebackground}}
> \begin{document}
> \begin{longtblr}{colspec={X[c] X[c]},rowhead=1}
> head1&head2\\
> \SetCell[r=35]{m}1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\
> 1&2\\1&2\\
> 
> 
> \end{longtblr}
> \end{document}

**Comment by lvjr** [comment]
Sorry, `tabularray` can not break multirow cells.

**Comment by earthmoon** [comment]
> Sorry, `tabularray` can not break multirow cells.

Thanks. Will you add this feature in the future?

**Comment by lvjr** [comment]
No, because it is too complicated.

**Comment by earthmoon** [comment]
> No, because it is too complicated.
Okay. Thanks. Is there another package that can do this?

**Comment by lvjr** [comment]
I don't know.

**Comment by earthmoon** [comment]
> I don't know.

Thanks a lot!
