### ISSUE TITLE
Unable to modify rowsep in longtblr

### ISSUE THREAD

**Issue by FruitSausage** [lvjr/tabularray#279]
Regular `tblr` `rowsep` can be reduced with for example:

```
\SetTblrInner{rowsep=0pt}
\begin{tblr}{lr}
a & b \\
c & d \\
\end{tblr}
```

But this does not work for `longtblr`:

```
\SetTblrInner{rowsep=0pt}
\begin{longtblr}{lr}
a & b \\
c & d \\
\end{longtblr}
```

Is there an alternative way?

**Comment by lvjr** [comment]
You need to write
`\SetTblrInner[longtblr]{rowsep=0pt}`.
