### ISSUE TITLE
User-defined variable bug?

### ISSUE THREAD

**Issue by FruitSausage** [lvjr/tabularray#283]
I've had trouble getting user-defined variables to work sometimes.  For instance, the following does not work:

```
\documentclass[letterpaper,11pt,oneside]{article}
\usepackage{tabularray}

\newcommand{\userVarA}{0.1}

\begin{document}

\begin{longtblr}{
   colspec = {| X[\userVarA,l] X |},
}
   alpha & beta \\
\end{longtblr}

\end{document}
```

But this does:

```
\documentclass[letterpaper,11pt,oneside]{article}
\usepackage{tabularray}

\begin{document}

\begin{longtblr}{
   colspec = {| X[0.1,l] X |},
}
   alpha & beta \\
\end{longtblr}

\end{document}
```

**Comment by lvjr** [comment]
When you write `Q[0.1]`, `tabularray` correctly guesses it is `Q[co=0.1]`, but when you write `Q[\userVarA]`, `tabularray` wrongly guesses it is `Q[wd=\userVarA]`. Therefore you can not omit `co=` in this case.
