### ISSUE TITLE
The styles of elements interfere with each other

### ISSUE THREAD

**Issue by Meiting-Wang** [lvjr/tabularray#286]
Hello Mr. Lu. I find that `\SetTblrStyle{note}{\huge\color{blue}}` will also affect the style of **remark** and **contfoot-text**, if I run the codes below:
```tex
\SetTblrStyle{contfoot-text}{\Large\color{red}}
\SetTblrStyle{remark}{\footnotesize}
\SetTblrStyle{note}{\huge\color{blue}}
```
and `\SetTblrStyle{note}{\huge\color{blue}}` will not affect the style of **remark** and **contfoot-text**, if I don't set style for both **remark** and **contfoot-text** at the same time, i.e. I only run the code:
```tex
\SetTblrStyle{note}{\huge\color{blue}}
```

I think this may be a bug.

Best wishes

PS.
my system: win10
Tex Live version: TeX 3.141592653 (TeX Live 2022)
tlmgr update time: August 6, 2022
My MWE:

![image](https://user-images.githubusercontent.com/42256486/184500765-4d810d2c-a1b5-43af-b07c-70e0c244fc0a.png)

```tex
\documentclass{article}
\usepackage{lipsum}
\usepackage{xcolor}
\usepackage{tabularray}

\SetTblrStyle{contfoot-text}{\Large\color{red}}
\SetTblrStyle{remark}{\footnotesize}
\SetTblrStyle{note}{\huge\color{blue}}

\begin{document}

\lipsum[1-4]

\begin{longtblr}[
  caption={There is a caption},
  remark{Note 1}={There is a remark.},
  note{a}={There is a note.},
]{
  hline{1,Z}={1pt},
}
  Alpha   & Beta             & Gamma  & Delta & aaa & bbb  \\
  Epsilon & Zeta\TblrNote{a} & Eta    & Theta & aaa & bbb  \\
  Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
  Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
  Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
  Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
  Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
  Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
  Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
  Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
  Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
  Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
\end{longtblr}
\end{document}
```

**Comment by lvjr** [comment]
This bug should has been fixed. You may download the latest package file
https://github.com/lvjr/tabularray/raw/main/tabularray.sty
and test whether there are other problems.

PS: It is better to write your `\SetTblrStyle` commands as follows:
```latex
\SetTblrStyle{contfoot-text}{font=\Large,fg=red}
\SetTblrStyle{remark}{font=\footnotesize}
\SetTblrStyle{note}{font=\huge,fg=blue}
```

**Comment by lvjr** [comment]
With the latest package file, you get the expected result:
```latex
\documentclass{article}
\usepackage[paperheight=6cm,height=3.5cm]{geometry}

\usepackage{xcolor}
\usepackage{tabularray}

\SetTblrStyle{contfoot-text}{font=\Large,fg=red}
\SetTblrStyle{remark}{font=\footnotesize}
\SetTblrStyle{note}{font=\huge,fg=blue}

%\SetTblrStyle{contfoot-text}{\Large\color{red}}
%\SetTblrStyle{remark}{\footnotesize}
%\SetTblrStyle{note}{\huge\color{blue}}

\begin{document}

\begin{longtblr}[
  caption={There is a caption},
  remark{Note 1}={There is a remark.},
  note{a}={There is a note.},
]{
  hline{1,Z}={1pt},
}
  Alpha   & Beta             & Gamma  & Delta & aaa & bbb  \\
  Epsilon & Zeta\TblrNote{a} & Eta    & Theta & aaa & bbb  \\
  Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
  Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
  Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
  Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
\end{longtblr}
\end{document}
```
![image](https://user-images.githubusercontent.com/4239949/188267581-53e8655d-e9a5-4d49-95ed-f1e235f3546f.png)

**Comment by Meiting-Wang** [comment]
> With the latest package file, you get the expected result:
> 
> ```
> \documentclass{article}
> \usepackage[paperheight=6cm,height=3.5cm]{geometry}
> 
> \usepackage{xcolor}
> \usepackage{tabularray}
> 
> \SetTblrStyle{contfoot-text}{font=\Large,fg=red}
> \SetTblrStyle{remark}{font=\footnotesize}
> \SetTblrStyle{note}{font=\huge,fg=blue}
> 
> %\SetTblrStyle{contfoot-text}{\Large\color{red}}
> %\SetTblrStyle{remark}{\footnotesize}
> %\SetTblrStyle{note}{\huge\color{blue}}
> 
> \begin{document}
> 
> \begin{longtblr}[
>   caption={There is a caption},
>   remark{Note 1}={There is a remark.},
>   note{a}={There is a note.},
> ]{
>   hline{1,Z}={1pt},
> }
>   Alpha   & Beta             & Gamma  & Delta & aaa & bbb  \\
>   Epsilon & Zeta\TblrNote{a} & Eta    & Theta & aaa & bbb  \\
>   Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
>   Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
>   Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
>   Iota    & Kappa            & Lambda & Mu    & aaa & bbb  \\
> \end{longtblr}
> \end{document}
> ```
> 
> ![image](https://user-images.githubusercontent.com/4239949/188267581-53e8655d-e9a5-4d49-95ed-f1e235f3546f.png)

Thank you very much. I can get the expected result now.
