### ISSUE TITLE
Symmetrically spread extra row height in cells adjacent to a tall multirow cell

### ISSUE THREAD

**Issue by Sonja-K** [lvjr/tabularray#3]
`tabularray` seems to avoid overflowing contents of tall `\multirow` cells by enlarging the height of the last row that the `\multirow` cell spans. Is there already a way to instead evenly distribute the extra row height over all rows that the `\multirow` cell spans or is such a feature planned?

Here is a MWE comparing the current output using `tabularray` as well as two mock-up versions showing such an evenly distributed additional row height:

![tabularray-example3](https://user-images.githubusercontent.com/30843621/118784369-3e99cb80-b890-11eb-80fa-f6db3fda52dc.png)

```
\documentclass{article}
\usepackage{tabularray}
\usepackage{multirow}

\begin{document}

\begin{tblr}{hlines,vlines, colspec={lp{3.25cm}}}
  Column1 & Column2  \\
  Row1 & \multirow{3}{=}{Long text that needs multiple lines. Long text that needs multiple lines.  Long text that needs multiple lines.}  \\ 
  Row2 &  \\  
  Row3 &  \\ 
  Row4 &  short text  \\ 
\end{tblr}

\bigskip
\begin{tabular}{|l|p{3.25cm}|}
  \hline
  Column1 & Column2  \\ 
  \hline
  Row1 & \multirow{6}{=}{Long text that needs multiple lines. Long text that needs multiple lines. Long text that needs multiple lines.} \\
  &\\ 
  \cline{1-1}
  Row2 &  \\
  &\\
  \cline{1-1}
  Row3 &  \\
  &\\
  \hline  
  Row4 &  short text  \\
  \hline
\end{tabular}
\quad
\begin{tabular}{|l|p{3.25cm}|}
  \hline
  Column1 & Column2  \\ 
  \hline
  \multirow{2}{*}{Row1} & \multirow{6}{=}{Long text that needs multiple lines. Long text that needs multiple lines. Long text that needs multiple lines.} \\
  &\\  
  \cline{1-1}
  \multirow{2}{*}{Row2} &  \\
  &\\
  \cline{1-1}
  \multirow{2}{*}{Row3} &  \\
  &\\ 
  \hline 
  Row4 &  short text  \\ 
  \hline
\end{tabular}

\end{document} 
```

Some related questions/comments:

https://tex.stackexchange.com/q/581298
https://tex.stackexchange.com/q/359003
https://tex.stackexchange.com/questions/343779/multirow-cell-content-overflows#comment843635_343779

**Comment by lvjr** [comment]
In `tabularray`, the default behaviors of `\multicolumn` and `\multirow` follow the span algorithm in TeXbook (see page 245 in chapter 22). It is in my todo list to add two options `hspan=even` and `vspan=even` as you described above.  But I'm refactoring the code to make it run faster, there maybe some days later when I add this feature.

**Comment by lvjr** [comment]
As long as we have a proper algorithm, it's not hard to implement it. The problem is, if we have many multirow cells which span different rows, how could we find the minimal height to extend? It's complex if we want to add the same height to each row.

**Comment by lvjr** [comment]
I have added `hspan=even` and `vspan=even` options, and this issue could be closed now.
````latex
\begin{tblr}{hlines, vlines, colspec={lp{3.25cm}}}
  Column1 & Column2  \\
  Row1 & \multirow{3}{=}{Long text that needs multiple lines. Long text that needs multiple lines. Long text that needs multiple lines.}  \\ 
  Row2 &  \\  
  Row3 &  \\ 
  Row4 &  short text  \\ 
\end{tblr}
\qquad
\begin{tblr}{hlines, vlines, colspec={lp{3.25cm}}, vspan=even}
  Column1 & Column2  \\
  Row1 & \multirow{3}{=}{Long text that needs multiple lines. Long text that needs multiple lines. Long text that needs multiple lines.}  \\ 
  Row2 &  \\  
  Row3 &  \\ 
  Row4 &  short text  \\ 
\end{tblr}
````
![image](https://user-images.githubusercontent.com/4239949/121449716-ef494580-c9cc-11eb-92fa-8059ba56cdc7.png)

**Comment by Sonja-K** [comment]
Thanks a lot. The `vspan=equal` option works just as I had envisaged.
