### ISSUE TITLE
\pagebreak and \nopagebreak for long tables

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#30]
At this moment,  `tabularray` is able to recognize a `\\*` command, but doesn't forbid a page break there. And It doesn't support `\nopagebreak` and `\pagebreak` commands. We need to implement these. But the optional arguments of `\nopagebreak` and `\pagebreak` commands seem useless in `tabularray`, since we manually break long tables.

**Comment by mhabets** [comment]
Indeed, to avoid having a very annoying row alone in the bottom of a page (see "Implementing partners" in the image below), I believe `\\*` command is a _must to have_ feature.

![image](https://user-images.githubusercontent.com/2016449/124790465-169b2000-df43-11eb-888f-7322c204e2fe.png)

**Comment by lvjr** [comment]
You may increase or decrease `rowsep` to get different page breaks, before this feature is implemented. Hope to implement it in this month.

**Comment by lvjr** [comment]
Now `\\*` command is working.

**Comment by mhabets** [comment]
So nice. Well done! 👍
