### ISSUE TITLE
environment longtblr can't break page correctly

### ISSUE THREAD

**Issue by zousiyu1995** [lvjr/tabularray#307]
I used longtblr to compose a very long table. I found the context before the longtblr can't break page correctly. The context was extruded below the page number. I can't provide a minimum working example due to my document is complex.
![image](https://user-images.githubusercontent.com/7608449/190835588-955433cf-1233-49df-9684-93c04b4b3f5c.png)

**Comment by lvjr** [comment]
You may insert some `\vspace` before the `\section` in preparing a minimal example.
