### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by mauriziopassariello** [lvjr/tabularray#310]
Hi,
I find the package very interesting but I confess I didn’t find the documentation very clear. I’m somewhat confused for example about the Q columns and the options available to specify them Although I’m familiar with the tabular environment I like the fact that you can separate the table specs from the content. Is there any simple guide somewhere (like a cheat sheet) where there is a clear explanation of the options available to specify the table? 
many thanks!

PS perhaps this is not the appropriate forum for this question but I could not contact you otherwise!

**Comment by lvjr** [comment]
See Table 2.9 in the manual for keys used in `Q` columns:

![image](https://user-images.githubusercontent.com/4239949/191393537-9304bb11-5aea-42f6-b1b2-f6f4119c0bff.png)

And you can write down your suggestions on the manual in this [survey](https://github.com/lvjr/tabularray/discussions/119).
