### ISSUE TITLE
X-columns

### ISSUE THREAD

**Issue by hvoss49** [lvjr/tabularray#311]
Wouldn't it make sense to define the optional argument `X=...` instead of `co=...`
Then it is always clear, that this value belongs to a X-column.

**Comment by lvjr** [comment]
Sorry, I don't think this is an enough strong reason to change existing syntax.

**Comment by hvoss49** [comment]
You don't need to change the syntax, you could handle `co=` and `X=`  as the same option.

**Comment by lvjr** [comment]
But `X[X=2]` looks a little weird, while `X[co=2]` looks natural.
