### ISSUE TITLE
preto shown in multicol/row cell

### ISSUE THREAD

**Issue by Felipe-Math** [lvjr/tabularray#317]
When I make a cell span in multiple rows and/or columns the content of `preto` is still prepended to the cell.

MWE:

```
\begin{tblr}{hlines,vlines,colspec={Q[l,preto=x:]}}
	1-1 & 1-2 & 1-3\\
	\SetCell[c=2]{c}2 cols & 2-3\\
	\SetCell[r=2]{c}2 rows& 3-2&3-3\\
	4-1&4-2&4-3\\
	\SetCell[r=2,c=2]{c}2 rows and cols &4-2& 4-3\\
	5-1&5-2&5-3\\
\end{tblr}
```
Printscreen:
![Captura de tela de 2022-10-10 21-16-50](https://user-images.githubusercontent.com/67498248/194971097-8964ceab-58f5-4301-bffe-f101f54014ac.png)

I didn't find a way to overcome it, just avoid using preto.

I tried to "overwrite", setting the `preto` in the `\SetCell`, but it doesn't work ... both preto content were shown.

I thinked in something like `row{1} = ...`, but for columns ... and tried to do something like `col{1} = {1}{preto=x:}`, but there is no such element `row{1}` in `tabularray` preamble specification.

**Comment by lvjr** [comment]
You need to use `cell{i}{1}={preto=x:}`.
