### ISSUE TITLE
Automatic colspec

### ISSUE THREAD

**Issue by london111** [lvjr/tabularray#319]
I think a nice feature for the future would be that you don't need to specify the number of columns, i.e. that something like

```
\begin{tblr}
a & b & c \\
\end{tblr}
```
should work (with a default col spec), so in particular you don't need to know or count the number of columns. 

Then it should be possible to specify the colspec for specific columns directly, for example:

```
\begin{tblr}{colspec{3}={l}}
a & b & c \\
\end{tblr}
```

This should just set the column type of the third row (if existent, if not just throw a warning, but no error). 

Moreover something like this

```
\begin{tblr}{colspec{2,4}={c},colspec{3}={l}}
a & b & c  & d & e & f \\
\end{tblr}
```
should also work (i.e. setting the column type of columns 2 and 4 to c and that of 3 to l). Maybe allowing also ranges like `colspec{2...5} = ...`

In this context it would also be great to implement named columns (by the context of the first row), i.e. something like 

```
\begin{tblr}{colspec{b,d}={c},colspec{c}={l}}
a & b & c  & d & e & f \\
A & B & C & D & E & F\\
\end{tblr}
```

I.e. referencing the columns by name not by number.

**Comment by lvjr** [comment]
This feature is already there since the first public release.
```latex
\SetTblrInner{columns={r}}
\begin{tblr}{}
a & b & c  & d & e & f \\
A & B & C & D & E & F\\
\end{tblr}
\begin{tblr}{column{1,Z}={c},column{Y}={l}}
a & b & c  & d & e & f \\
A & B & C & D & E & F\\
\end{tblr}
```

**Comment by london111** [comment]
Thanks, great. I overlooked this in the manual. If I am not mistaken, the first occurrence of such an example is in manual is in section 2.2.1. Maybe one could mention it already in 1.1 that the number of columns could be detected automatically. However the "named" reference doesn't seem to be implemented yet? May I ask for this in a new post?

**Comment by lvjr** [comment]
> However the "named" reference doesn't seem to be implemented yet? May I ask for this in a new post?

Sorry, it is unlikely that I will implement named columns by the context of the first row.

**Comment by london111** [comment]
Ok thanks. The idea was to be able to reference the columns similar as in python pandas. Maybe for the remote future...
