### ISSUE TITLE
longtblr - New page breaking issues

### ISSUE THREAD

**Issue by Aljumaily** [lvjr/tabularray#320]
The following example will break the cell in a way where the vertical lines don't show and places the `contfoot-text` text in way to be seen as a part of the table.

<img width="98" alt="image" src="https://user-images.githubusercontent.com/44656681/196045259-59326bc9-261d-447f-8f3a-67e34359d368.png">

```
\documentclass{article}

\usepackage{tabularray}
\begin{document}
~\vspace{5in}
\begin{longtblr}[
    caption = {The caption of the table},
  ]{colspec = {ll}, vlines}
  \hline
  \SetCell[r=2]{m, 1cm} {Line \\ Line \\ Line \\ Line} & Alpha \\
  \cline{2}
   & Beta                     \\
  \hline
  \SetCell[r=2]{m, 1cm} {Line \\ Line \\ Line \\ Line} & Alpha \\
  \cline{2}
   & Beta                     \\
  \hline
  \SetCell[r=2]{m, 1cm} {Line \\ Line \\ Line \\ Line} & Alpha \\
  \cline{2}
   & Beta                     \\
  \hline
\end{longtblr}
\end{document}
```

Off-topic: is there a way to ensure the caption in the example above spans `\textwidth` *without* changing the width of the table (*i.e.*, without the usage of `width=\textwidth`)?

Sidenote: Regardless, the package is FANTASTIC!

**Comment by lvjr** [comment]
Sorry, `tabularray` can not break multirow cells. See issue #278.
