### ISSUE TITLE
Macros in \NewColumnType

### ISSUE THREAD

**Issue by HROMANO** [lvjr/tabularray#322]
Is there a way to use macros in \NewColumnType? Here is a non working example of what I wanted to do:

```
\ExplSyntaxOn
\NewDocumentCommand{\decimaux}{m}
{
    \mafp_decimaux_split:n { #1 }
}

\tl_new:N \l_mafp_part_tl

\cs_new_protected:Npn \mafp_decimaux_split:n #1
{
    \regex_match:nnTF { .*\d+\.\d+.* } { #1 }
    {
        \tl_set:Nn \l_mafp_part_tl  { #1 }
        \regex_replace_once:nnN { .*\d+\.(\d+).* } { \1 } \l_mafp_part_tl
        \tl_use:N \l_mafp_part_tl
    }
    {
        #1
    }
}
\ExplSyntaxOff
\NewColumnType{e}[1]{S[table-format=#1, round-mode=places, round-precision=\decimaux{#1}]}
```

\decimaux extracts the number of decimal digits so I don't have to repeat it for the rounding. The macro works outside a \NewColumnType but a tblr with a column defined as e{3.2} doesn't work ("missing number").

Out of scope, documentation on \NewColumnType is sparse. What is the difference for example between:

```
\NewColumnType{a}[1]{…
\NewColumnType{a}[1][]{…
```

What's the meaning of the second optional argument?

Thanks

**Comment by lvjr** [comment]
> \decimaux extracts the number of decimal digits so I don't have to repeat it for the rounding. The macro works outside a \NewColumnType but a tblr with a column defined as e{3.2} doesn't work ("missing number").

Please provide a minimal but complete example (starting with `\documentclass` and ending with `\end{document}`). Can you use your macro in `\newcolumntype` and use the `e` columns in a traditional `tabular` environment? If it fails in `tabular` too, then you should make a feature request on [`siunitx`](https://github.com/josephwright/siunitx) package.
 
> Out of scope, documentation on \NewColumnType is sparse. What is the difference for example between:
> 
> ```
> \NewColumnType{a}[1]{…
> \NewColumnType{a}[1][]{…
> ```
> 
> What's the meaning of the second optional argument?

It is the same as `\newcommand`: the second optional argument of `\NewColumnType` make the first argument of the column type optional.

**Comment by HROMANO** [comment]
Thank you for your reply. It doesn't work with plain siunitx and tabular environment. Here is a complete (not working) example:

```
\documentclass{article}

\usepackage{expl3}
\usepackage{siunitx}

\ExplSyntaxOn
\NewDocumentCommand{\decimaux}{m}
{
    \mafp_decimaux_split:n { #1 }
}

\tl_new:N \l_mafp_part_tl

\cs_new_protected:Npn \mafp_decimaux_split:n #1
{
    \regex_match:nnTF { .*\d+\.\d+.* } { #1 }
    {
        \tl_set:Nn \l_mafp_part_tl  { #1 }
        \regex_replace_once:nnN { .*\d+\.(\d+).* } { \1 } \l_mafp_part_tl
        \tl_use:N \l_mafp_part_tl
    }
    {
        #1
    }
}
\ExplSyntaxOff

\begin{document}

    The decimal part in '<+2.1' is \decimaux{<+2.1}.
    
    \begin{tabular}{lS[table-format=<+2.1, round-mode=places, round-precision=\decimaux{<+2.1}]}
        36.32 & 36.32 \\
    \end{tabular}

\end{document}
```

I'll will ask to siunitx. I suppose \decimaux is not expanded before use.

And thanks for tabularray. It makes writing tables far more easy!
