### ISSUE TITLE
hyperref without pdfborder

### ISSUE THREAD

**Issue by wrfwerrr** [lvjr/tabularray#33]
目录中标题默认带的hyperref超链接边框没了，这可能是ninecolors宏包引起的，请问能否对这个小问题进行调整

```
\documentclass{ctexbook}

\usepackage{tabularray}
\usepackage{hyperref}

\begin{document}
\tableofcontents
\chapter{chapter}

\end{document} 
```
![图片](https://user-images.githubusercontent.com/70802391/125186240-c16d5000-e25b-11eb-90f0-87f15e917326.png)
![图片](https://user-images.githubusercontent.com/70802391/125186258-e2ce3c00-e25b-11eb-926c-bb513cb0340e.png)

**Comment by muzimuzhi** [comment]
This has nothing to do with `ninecolors`.

`tabularray` explicitly sets
https://github.com/lvjr/tabularray/blob/9b59794d3361f972d9375e7340787c4858213698/tabularray.sty#L20-L24
which overwrites the `hyperref` default `pdfborder={0 0 1}`.

**Comment by wrfwerrr** [comment]
> 
> 
> 目录中标题默认带的hyperref超链接边框没了，这可能是ninecolors宏包引起的，请问能否对这个小问题进行调整
> 
> ```
> \documentclass{ctexbook}
> 
> \usepackage{tabularray}
> \usepackage{hyperref}
> 
> \begin{document}
> \tableofcontents
> \chapter{chapter}
> 
> \end{document} 
> ```
> 
> ![图片](https://user-images.githubusercontent.com/70802391/125186240-c16d5000-e25b-11eb-90f0-87f15e917326.png)
> ![图片](https://user-images.githubusercontent.com/70802391/125186258-e2ce3c00-e25b-11eb-926c-bb513cb0340e.png)



> 
> 
> This has nothing to do with `ninecolors`.
> 
> `tabularray` explicitly sets
> 
> https://github.com/lvjr/tabularray/blob/9b59794d3361f972d9375e7340787c4858213698/tabularray.sty#L20-L24
> 
> which overwrites the `hyperref` default `pdfborder={0 0 1}`.

**Comment by muzimuzhi** [comment]
The `pdfborder={0 0 0}` setting is added in https://github.com/lvjr/tabularray/commit/d580c895803d65d43215bf999b5428e404fbd735, which seems to be required for the un-documented tblr template `note-target`. (Just follow the macro `\__tblr_hyper_target:n` / `\__tblr_hyper_target:V`.)

`hyperref` stores the value of key `pdfborder` in `\@pdfborder`, so maybe `tabularray` could use `\def\@pdfborder{0 0 0}` locally to support template `note-target` and keep the "global" `\@pdfborder` unchanged.

**Comment by lvjr** [comment]
Good idea!

**Comment by muzimuzhi** [comment]
The (low-level) latex3 support for creating PDF destinations (what `\hypertarge` does) and annotations (what `\hyperlink` does) are now in `l3pdf` (part of `l3kernel`) and `l3pdfannot` (a [`pdfmanagement-testphase`](https://ctan.org/pkg/pdfmanagement-testphase) module), and it looks like `pdfmanagement(-testphase)` will eventually provide high-level support. A chance that `tabularray` can grow with _The LaTeX Project_.

**Comment by lvjr** [comment]
I decided not to fix this. Since users could easily recover the pdfborder by the following line:
````latex
\AtBeginDocument{\hypersetup{pdfborder={0 0 1}}}
````
Also there is a disadvantage to use `\@pdfborder` locally: users could not recover the pdfborder by theirselves if they want.

**Comment by muzimuzhi** [comment]
Perhaps `tabularray` should document this, since it changes the default (or initial) `hyperref` setting.

**Comment by lvjr** [comment]
Yes, I should.  There are still many interfaces to be documented.

**Comment by u-fischer** [comment]
Sorry but it is wrong if a package like  tabularray interferes with user setting for links. Please remove this. 

If you want to  suppress the link border somewhere in a special location in a tabular you can reset it locally with `\hypersetup{pdfborder={0 0 0}`, or implement an user option for this, but imho it doesn't make sense to add a link if there is no visible clue that it exists.

**Comment by lvjr** [comment]
OK, I will reconsider it later.  Maybe use underline links with `pdfborderstyle={/S/U/W 1}` inside `tblr`  only and let user customize it with `\DefTblrTemplate`. 

In my opinion, the default pdf border is very ugly.  Why not default to underline links? Many other software use underline links nowadays.

**Comment by muzimuzhi** [comment]
I think the point here is not how the default setting looks like, but to not change it globally. After all, `tabularray` is not a class which usually provides something pre-configured, but a utility package.

**Comment by u-fischer** [comment]
> In my opinion, the default pdf border is very ugly. 

You are not alone with this opinion. But it is not the job of tabularray to change this. If a user decides to use pdfborder then loading a tabular package shouldn't suddenly remove them.

> Why not default to underline links?

Well make a feature request ;-) I could add the setting to the new hyperref driver in pdfmanagement. (But the main problem with it is that it isn't supported by all pdfviewer).

**Comment by sammaddens** [comment]
Besides the discussion of this option. The border stays in the document when compiling a MWE:
    
    \documentclass{article}
   
    \usepackage{hyperref}
    \usepackage{tabularray}
   
    \begin{document}
    \hypertarget{ref}{target} and \hyperlink{ref}{link}.
    \end{document}

The following warning arises: `Invalid value '000'(hyperref) for option 'pdfborder'.` This can be solved by using `\hypersetup{pdfborder={\ 0\ 0\ 0}}` in `tabularray.sty` (to secure the spaces).

Compiled on Windows with the latest version of MiKTeX.

**Comment by lvjr** [comment]
Oops!  The space characters are gobbled by `\ExplSyntaxOn`. Thanks for telling me this!

**Comment by lvjr** [comment]
But `\hypersetup` is before `\ExplSyntaxOn` in the source code. Strange?

**Comment by u-fischer** [comment]
> But `\hypersetup` is before `\ExplSyntaxOn` in the source code. Strange?

You are using `\ProvidesExplPackage`. This means that ExplSyntaxOn is implicit (and you shouldn't use it).

**Comment by lvjr** [comment]
@u-fischer Thanks. So I need to remove `\ExplSyntaxOn` in the source code. Can I remove `\ExplSyntaxOff` at the end too? (i.e., is `\ProvideExplPackage` add `\ExplSyntaxOff` at the end of file too?)

**Comment by u-fischer** [comment]
Yes both is unneeded. The LaTeX package code will take care to reset this (as it takes care of the @ in other packages)

**Comment by lvjr** [comment]
Now we have `note-border` template for setting `pdfborder`:
````latex
\SetTblrTemplate{note-border}{normal} % show
\SetTblrTemplate{note-border}{empty}  % hide
````
