### ISSUE TITLE
`label=none` still typesets a full caption using default `capcont` template

### ISSUE THREAD

**Issue by muzimuzhi** [lvjr/tabularray#335]
Example is simplified from #334.
```tex
\documentclass{article}
\usepackage{tabularray}

\begin{document}
% \listoftables

\begin{longtblr}[
%   entry = none,
  label = none,
  caption = Title
]{
  colspec = {llX},
  rowhead = 1,
}
  \hline
  \textbf{Name} & \textbf{Unit} & \textbf{Description} \\ \hline
  $V_{\mathrm{ref}}$ & & Reference voltage \\
  $C_{\mathrm{hp}}$  & & High pass filter capacitor \\
  \pagebreak
  $R_{\mathrm{hp}}$  & & High pass filter resistor \\
  \hline
\end{longtblr}
\end{document}
```

Actual: A simple caption "Title" is typeset on 1st page, while a full caption "Table 0:  (continued)" is typeset on 2nd page.
![image](https://user-images.githubusercontent.com/6376638/207164051-6d814eda-ac84-404e-93bd-65dbb632f636.png)
![image](https://user-images.githubusercontent.com/6376638/207172536-4d3d5b19-8b62-4270-821d-921579078e93.png)

Expected: A simple caption "Title (continued)" should be typeset on 2nd page.

**Comment by lvjr** [comment]
> I made a proposal in https://github.com/muzimuzhi/tabularray/tree/no-label.

Great. Could you make a pull request?
