### ISSUE TITLE
Usage with TexpadTex

### ISSUE THREAD

**Issue by lkoehl** [lvjr/tabularray#341]
I like to use a program called [Texifier](https://www.texifier.com), which comes with a custom Tex-Distribution called TexpadTex. When trying to compile a sample table with tabularray a long list of errors shows up. As a not so experienced LaTeX user, I can't really say if it could be possible to make it work. [Here you can find the compile log.](https://pastecode.io/s/8gjtaj8h)

It would be great if it's possible to use the package with the listed program, but no problem if not.

**Comment by FrankMittelbach** [comment]
The LaTeX version of that program is badly out of date:
```
LaTeX Warning: You have requested release `2018-04-01' of LaTeX,
               but only release `2017-04-15' is available.
```
April 2017 is way to old to be able to use any recent packages on top of it. If that Texifier is not updating its LaTeX I would say it is already now basically unusable but certainly so if you want to use anythign that has been develped n the last 5 years.

**Comment by lkoehl** [comment]
Thank you for your quick help. I couldn't really say if the problem was related to the software or the package. I just contacted the support if they are planning to update the LaTeX version, since I'm really interested in the capabilities of this package.

**Comment by FrankMittelbach** [comment]
@lkoehl LaTeX updates regularly every half year and there have been many improvements over the years directly in the format (e.g., in 2018 LaTeX moved to Unicode by default, or in 2020 it integrated a general hook management that is used by packages, also the L3 programming layer got integrated (which is what this package here is based upon). So basically if they ship with a frozen format then all you can do is used what was available in 2017 and hope for the best with anything else.

**Comment by muzimuzhi** [comment]
As a final resort, maybe you can try to upload a new-enough format file to Texifier. If you have TeX Live installed locally, `kpsewhich --engine=pdftex pdflatex.fmt` will return the full path for format `pdflatex.fmt`.
