### ISSUE TITLE
How to set different padding for cells?

### ISSUE THREAD

**Issue by libinxu01** [lvjr/tabularray#342]
## Description
Initial:
![t1](https://user-images.githubusercontent.com/15907992/209817371-ff16d983-a66a-4a6c-b206-3785e907ff48.png)
After I add rowsep=10pt to set padding for all cells, the first cell with diagbox is not aligned.
![t2](https://user-images.githubusercontent.com/15907992/209817423-89df0548-d114-491a-a707-6a628006c402.png)

I wonder how to set different padding for different cells?

## Add info or delete as appropriate:
- Relevant for XeTeX

## Minimal example demonstrating the issue
```tex
\documentclass{book}
\RequirePackage{tabularray}
\RequirePackage{setspace}

\UseTblrLibrary{diagbox}

\begin{document}
\NewTblrTheme{fancy}{
    \SetTblrTemplate{head,foot}{empty}
}
\par
\begingroup
\begin{center}
\begin{longtblr}[
	theme = fancy, 
]{
	colsep=8pt, 
        rowsep=10pt,
	stretch=1.1, 
	rulesep=3.0mm, 
	width=1.0\textwidth, 
	colspec={X[2.0,l,m]X[2.0,l,m]X[2.0,l,m]X[2.0,l,m]X[2.0,l,m]}, 
	hline{1}={1}{1.0pt,fg=}, 
	hline{1}={2}{1.0pt,fg=}, 
	hline{1}={3}{1.0pt,fg=}, 
	hline{1}={4}{1.0pt,fg=}, 
	hline{1}={5}{1.0pt,fg=}, 
	hline{2}={1}{1.0pt,fg=}, 
	hline{2}={2}{1.0pt,fg=}, 
	hline{2}={3}{1.0pt,fg=}, 
	hline{2}={4}{1.0pt,fg=}, 
	hline{2}={5}{1.0pt,fg=}, 
	vline{1}={1}{1.0pt,fg=}, 
	vline{2}={1}{0.5pt,fg=}, 
	vline{3}={1}{0.5pt,fg=}, 
	vline{4}={1}{0.5pt,fg=}, 
	vline{5}={1}{0.5pt,fg=}, 
	vline{6}={1}{1.0pt,fg=}, 
	column{1}={0.125\textwidth}, 
	column{2}={0.125\textwidth}, 
	column{3}={0.125\textwidth}, 
	column{4}={0.125\textwidth}, 
	column{5}={0.125\textwidth}, 
	row{1}={0.075\textwidth}, 
}
 \SetCell[r=1,c=1]{halign=c,valign=m}{\diagbox[innerwidth=0.125\textwidth, linewidth=0.5pt] {}{}}&\SetCell[r=1,c=1]{halign=c,valign=m}{\begin{minipage}[m]{0.125\textwidth}\raggedright  aaa \endgraf bbb  \endgraf ccc \quad\end{minipage}}&\SetCell[r=1,c=1]{halign=c,valign=m}{\begin{minipage}[m]{0.125\textwidth}\raggedright  aaa \endgraf bbb  \endgraf ccc \quad\end{minipage}}&\SetCell[r=1,c=1]{halign=c,valign=m}{\begin{minipage}[m]{0.125\textwidth}\raggedright  aaa \endgraf bbb \quad\end{minipage}}&\SetCell[r=1,c=1]{halign=c,valign=m}{\begin{minipage}[m]{0.125\textwidth}\raggedright  aaa \endgraf bbb \quad\end{minipage}}\\ 
\end{longtblr}
\end{center}
\endgroup

\end{document}
```

**Comment by muzimuzhi** [comment]
> I wonder how to set different padding for different cells?

Once the padding is added to the highest cell in a row, you have to add that same padding for `\diagbox` cell manually.

Try
```tex
\diagbox[innerwidth=0.125\textwidth, linewidth=0.5pt, height=3\line+\abovesep+\belowsep]...
```
in which `\abovesep` and `\belowsep` are both dimensions holding values set by `rowsep=10pt`.

**Comment by libinxu01** [comment]
> > I wonder how to set different padding for different cells?
> 
> Once the padding is added to the highest cell in a row, you have to add that same padding for `\diagbox` cell manually.
> 
> Try
> 
> ```
> \diagbox[innerwidth=0.125\textwidth, linewidth=0.5pt, height=3\line+\abovesep+\belowsep]...
> ```
> 
> in which `\abovesep` and `\belowsep` are both dimensions holding values set by `rowsep=10pt`.

Thanks so much! Resolved.
