### ISSUE TITLE
How to raise the content box with multiple lines in diagbox?

### ISSUE THREAD

**Issue by libinxu01** [lvjr/tabularray#347]
## Description
I use innerleftsep and innerrightsep to move the horizontal content box, and \raise and \lower to move the vertical, it works for single line.
## Example for single line
```tex
\documentclass{article}
\RequirePackage{tabularray}
\RequirePackage{setspace}

\UseTblrLibrary{diagbox}

\begin{document}
\NewTblrTheme{fancy}{
    \SetTblrTemplate{head,foot}{empty}
}

\begin{center}
\begin{longtblr}[
	theme = fancy, 
]{
	colsep=8pt, 
	rowsep=5pt, 
	stretch=1.1, 
	rulesep=3.0mm, 
	width=1.0\textwidth, 
	colspec={X[10.0,l,m]}, 
	hline{1}={1}{1.0pt,fg=}, 
	hline{2}={1}{1.0pt,fg=}, 
	vline{1}={1}{1.0pt,fg=}, 
	vline{2}={1}{1.0pt,fg=}, 
	column{1}={0.9402390438247012\textwidth}, 
	row{1}={0.3047808764940239\textwidth}, 
}
 \SetCell[r=1,c=1]{halign=c,valign=m}{\diagbox[innerwidth=0.9402390438247012\textwidth, height=0.3346613545816733\textwidth+\abovesep+\belowsep, innerleftsep=0.2\textwidth, innerrightsep=0.2\textwidth,  linewidth=0.5pt] {\raise30pt\hbox{helloworld}}{\lower30pt\hbox{helloworld}}}\\  
\end{longtblr}
\end{center}
\end{document}
```
![raise1](https://user-images.githubusercontent.com/15907992/210928222-c85383eb-8e5b-4ee3-94b2-9a42191123c3.png)

But it does not work for break lines. I've tried \parbox and others ways. I wonder how to raise the content box with multiple lines?
## Example for multiple lines
```tex
\documentclass{article}
\RequirePackage{tabularray}
\RequirePackage{setspace}

\UseTblrLibrary{diagbox}

\begin{document}
\NewTblrTheme{fancy}{
    \SetTblrTemplate{head,foot}{empty}
}

\begin{center}
\begin{longtblr}[
	theme = fancy, 
]{
	colsep=8pt, 
	rowsep=5pt, 
	stretch=1.1, 
	rulesep=3.0mm, 
	width=1.0\textwidth, 
	colspec={X[10.0,l,m]}, 
	hline{1}={1}{1.0pt,fg=}, 
	hline{2}={1}{1.0pt,fg=}, 
	vline{1}={1}{1.0pt,fg=}, 
	vline{2}={1}{1.0pt,fg=}, 
	column{1}={0.9402390438247012\textwidth}, 
	row{1}={0.3047808764940239\textwidth}, 
}
 \SetCell[r=1,c=1]{halign=c,valign=m}{\diagbox[innerwidth=0.9402390438247012\textwidth, height=0.3346613545816733\textwidth+\abovesep+\belowsep, innerleftsep=0.2\textwidth, innerrightsep=0.2\textwidth,  linewidth=0.5pt] {hello\\world}{hello\\world}}\\ 
\end{longtblr}
\end{center}
\end{document}
```
![2](https://user-images.githubusercontent.com/15907992/210928826-bda2ee9e-39e6-43ea-99c1-e0a04f3ba10f.png)

## Add info or delete as appropriate:
- Relevant for XeTeX

**Comment by muzimuzhi** [comment]
The zero-width-`\rule` trick still works:
```tex
\diagbox[...]{hello\\world\rule[-10pt]{0pt}{10pt}}{\rule{0pt}{20pt}hello\\world}
```
![image](https://user-images.githubusercontent.com/6376638/210939541-7a5b984c-391b-4927-b197-2260adc09e41.png)

It would be better if `diagbox` provides options to set above and below inner- and outer-seps.

BTW, may I ask where do the four magic numbers (two `0.94023...` and another two `0.33466...`) come from?

**Comment by libinxu01** [comment]
> The zero-width-`\rule` trick still works:
> 
> ```
> \diagbox[...]{hello\\world\rule[-10pt]{0pt}{10pt}}{\rule{0pt}{20pt}hello\\world}
> ```
> 
> ![image](https://user-images.githubusercontent.com/6376638/210939541-7a5b984c-391b-4927-b197-2260adc09e41.png)
> 
> It would be better if `diagbox` provides options to set above and below inner- and outer-seps.
> 
> BTW, may I ask where do the four magic numbers (two `0.94023...` and another two `0.33466...`) come from?

Thanks a lot! The user decides the width and height in the frontend, the backend transforms pt to \textwidth.

**Comment by lvjr** [comment]
@libinxu01 For pure questions, please ask them on https://github.com/lvjr/tabularray/discussions
