### ISSUE TITLE
& and % in tblr cause an error despite verb option

### ISSUE THREAD

**Issue by ysalmon** [lvjr/tabularray#358]
The following code causes an error ``\verb ended by end of line. \end``.

```tex
\documentclass{scrartcl}

\usepackage{tabularray}

\begin{document}
\begin{tblr}{verb,colspec={c}}
\verb!&!
\end{tblr}
\end{document}
```
The same happens with ``%``.

This is with tabularray 2022D and a freshly update texlive 2022, compiling with lualatex.

**Comment by muzimuzhi** [comment]
Just to make contents linked, this was originally asked on https://tex.stackexchange.com/q/673205.

**Comment by lvjr** [comment]
This is related to the tricky `\catcode` system in `TeX` and almost nothing can be done in the side of `tabularray` at present (see #13 for a future plan).

For `%` characters in `\verb` commands, you will also get an error if you use them inside a classical `tabular` environment. See #104 for a workaround for `tabularray`.

For `&` characters in `\verb` commands, you will also get an error if you use them inside a classical `tabularx` environment.

I am planning to add `\fakeverb` command to my `codehigh` package (see https://github.com/lvjr/codehigh/issues/11). Hopefully with the next release of `codehigh` package, you could easily write `\fakeverb{&\%}` to get `&%` in `tabularray` tables and other LaTeX commands.

**Comment by lvjr** [comment]
I have uploaded a new version of `codehigh` (with `\fakeverb` command) to CTAN.

**Comment by lvjr** [comment]
Since version 2023A, `verb` option was obsolete. Please use `\fakeverb` command instead.
