### ISSUE TITLE
Documentation should be more accessible to new users

### ISSUE THREAD

**Issue by ysalmon** [lvjr/tabularray#359]
The introduction to the documentation explicitly states that it is going to compare tabularray to the older packages it supersedes. This also explains why there are multiple ways to do the same thing.

This makes sense for already-experienced users who are familiar with those packages, but makes tabularray inaccessible to LaTeX newcomers — or even people who happen not to have used the various other packages.

A more comprehensive documentation, providing one recommended way to do each thing (or two in cases there is really a tradeoff between several ones ; I am think about multirow and multiline cells in particular) is necessary to allow tabularray to effectively supersede the older packages : for this, the knowledge of the mere existence of those packages cannot be a prerequisite.

**Comment by lvjr** [comment]
I am collecting suggestions for the documentations [here](https://github.com/lvjr/tabularray/discussions/119). Also contributions are always welcome.
