### ISSUE TITLE
enumerate inside cell text

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#36]
We use `\hbox` to measure the widths of cells before building the whole table. But it seems enumerate inside a cell would cause an error. Need to find out if there are any solutions for it.

**Comment by davidcarlisle** [comment]
Presumably the same applies to any vertical material, not just lists, eg display math.

**Comment by lvjr** [comment]
Then I think maybe we have to use `varwidth` to measure the sizes.

**Comment by lvjr** [comment]
Since `varwidth` package has not been updated for many years, and it even need first aid at this moment (https://ctan.org/pkg/latex-firstaid), it's safer to turn on its usage only by `\UseTblrLibrary{varwidth}`.

**Comment by lvjr** [comment]
I have added `varwidth` library and `measure` option to `tabularray` package:

````latex
\documentclass{article}

\usepackage{tabularray}
\UseTblrLibrary{varwidth}

\begin{document}

\begin{tblr}{
  colspec = {Xl}, hlines, vlines,
  measure = vbox,
}
  text & text \\
  \begin{itemize}
    \item text 1
    \item text 2
  \end{itemize} & text 3 \\
\end{tblr}

% set "measure=vbox" as default
\SetTblrInner{measure=vbox}

\begin{tblr}{
  colspec = {Xl}, hlines, vlines,
}
  text & text \\
  \begin{itemize}
    \item text 1
    \item text 2
  \end{itemize} & text 3 \\
\end{tblr}

\end{document}
````

![image](https://user-images.githubusercontent.com/4239949/130798560-f0a023b2-4f0a-4e8b-9d87-bb0a93b306b4.png)

**Comment by c-alpha** [comment]
Apologies for commenting on a closed issue, but I don't think this warrants opening a new one.

I was wondering whether there was a way of eliminating the vertical space above and below the list, i.e. to have "text 1" on the same baseline as "text 3"?

**Comment by lvjr** [comment]
See issue #99.
