### ISSUE TITLE
\nopagebreak before long tblr does not prevent a page break

### ISSUE THREAD

**Issue by Yodude2002** [lvjr/tabularray#361]
When using `\nopagebreak` before a long table, a page break may still be inserted.

Consider this example:
```latex
\documentclass[11pt]{article}
\usepackage{tabularray}
\usepackage{lipsum}

\begin{document}

\lipsum[1-4]

\section{Section}
\nopagebreak

\begin{tblr}{colspec={Q},hlines,vlines}}
    example cell text
\end{tblr}

\end{document}
```
<img width="520" alt="nopagebreak" src="https://user-images.githubusercontent.com/47131276/216684530-4361a5c1-1459-479f-aaa8-3c6b3ca41549.png">

Here, `\nopagebreak` prevents a page break before the table, so the section header is moved to the next page.

If this table is changed to a long table, the section header is left behind on the previous page:
```latex
\documentclass[11pt]{article}
\usepackage{tabularray}
\usepackage{lipsum}

\begin{document}

\lipsum[1-4]

\section{Section}
\nopagebreak

\begin{tblr}[long]{colspec={Q},hlines,vlines}}
    example cell text
\end{tblr}

\end{document}
```
<img width="520" alt="long_nopagebreak" src="https://user-images.githubusercontent.com/47131276/216684592-08520a6a-cd0b-48a2-8241-d64b448d6da0.png">

**Comment by lvjr** [comment]
See issue #42. Unfortunately `tabularray` tables can not work well when they follow sectioning commands. Please put some text between them.

**Comment by Yodude2002** [comment]
I've been looking into this a bit.

It looks like `\skip_vertical:n` and `\tex_penalty:D` can be used to force the TeX page breaking algorithm to run without leaving content behind (like `\newpage` does):

```latex
\skip_vertical:n { <length> }
\tex_penalty:D 9999
\skip_vertical:n { -<length> }
```
This will force a new page while keeping `\nopagebreak`s together (as long as`<length>` is large enough to overfill the current page).

By replacing the first `\TblrNewPage` in `\__tblr_build_long_table:n` with the following, long tables stay attached to `\section`s without affecting other page breaks or content after the table:

```latex
\int_compare:nNnTF
{ \l__tblr_curr_i_int } = { \l__tblr_row_head_tl + 1 }
    {
    \group_begin:
    \skip_vertical:n { \pagetotal - \pagegoal }
    \dim_set:Nn \l_tmpb_dim {
        \__tblr_box_height:N \l__tblr_table_firsthead_box
        + \l_tmpa_dim + \__tblr_box_height:N \l__tblr_table_firstfoot_box
    }
    \skip_vertical:n { \l_tmpb_dim }
    \tex_penalty:D 9999
    \skip_vertical:n { - \l_tmpb_dim }
    \group_end:
}
    {
    \TblrNewPage
}
```
By using `\int_compare:nNnTF { \l__tblr_curr_i_int } = { \l__tblr_row_head_tl + 1 }`, this replacement only occurs at the start of the table. `\l_tmpb_dim` is big enough to push the `\tex_penalty:D` past the end of the page, forcing both the table and the `\section` to the next page. The `\skip_vertical:n { \pagetotal - \pagegoal }` counteracts the `\skip_vertical:n` from ecc00b9, which this solution doesn't need.

While this produces what I would expect, I'm not sure if this breaks anything I'm unaware of. I'm sure there is a better way to do this, but I'm not familiar enough with `expl3` or tabularray internals to find it.

**Comment by lvjr** [comment]
@Yodude2002  It seems your idea is pretty good. I need to find more time to test it some days. Actually `tabularray` uses `l3build` for regression tests, so you could make a draft pull request to this repository to let GitHub Actions tell you whether anything is broken in several minutes.
