### ISSUE TITLE
Setting multiple environments at the same time

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#37]
### Discussed in https://github.com/lvjr/tabularray/discussions/35

<div type='discussions-op-text'>

<sup>Originally posted by **zandivx** July 13, 2021</sup>
When defining new tabularray environments with \NewTblrEnviron I often find myself copying and pasting existing definitions of other environments I've created earlier. I think it would be a great option to be able to refer to existing environments and inherit their options (something like \UseTblrTemplate but for environments).</div>

**Comment by lvjr** [comment]
It is easy to inherit options of an existring environment when defining a new environment. But if we want to go further, making `\SetTblrInner` and `\SetTblrOuter` obey environment inheritance, we need to carefully design some proper interfaces for this.

For example, if we define `longtblr` as an inheritance of `tblr` environment, then users should be able to control whether or not `\SetTblrInner[tblr]{rowsep=0pt}` also applies to `longtblr` environment.

**Comment by lvjr** [comment]
Maybe it is easier to just provide an interface to make common settings for all `tabularray` environments with
````latex
\SetTblrInner[*]{<settings>}
\SetTblrOuter[*]{<settings>}
````
or
````latex
\SetTblrInner*{<settings>}
\SetTblrOuter*{<settings>}
````

**Comment by earthmoon** [comment]
> It is easy to inherit options of an existring environment when defining a new environment. But if we want to go further, making `\SetTblrInner` and `\SetTblrOuter` obey environment inheritance, we need to carefully design some proper interfaces for this.
> 
> For example, if we define `longtblr` as an inheritance of `tblr` environment, then users should be able to control whether or not `\SetTblrInner[tblr]{rowsep=0pt}` also applies to `longtblr` environment.

I think it is better to change all the setting of `tblr`, `talltblr` and `longtblr` when nothing is input in `[ ]`.

**Comment by lvjr** [comment]
There is a potential problem if we change settings for all `tabularray` environments by default. In `amsmath` library, some environments `+array`, `+pmatrix`, etc are defined. These environments should not be affected.

**Comment by earthmoon** [comment]
> 

By default, exclude them and leave a choice to user to change them.

**Comment by lvjr** [comment]
Or we can make `\SetTblrInner` and `\SetTblrOuter` accept keyval options:

- `env={env1,env2,…,envN}` or `env=*`
- `mode=text` or `mode=math`

**Comment by lvjr** [comment]
To make my life easier, I decide to only extend the interface a little, allowing the setting for multiple `tabularray` environments at the same time:
```latex
\SetTblrInner[enva,envb,envc]{<settings>}
\SetTblrOuter[enva,envb,envc]{<settings>}
```
