### ISSUE TITLE
caption/head alignment don't function

### ISSUE THREAD

**Issue by matteo339** [lvjr/tabularray#386]
```
\documentclass{article}
\usepackage{tabularray}
  \SetTblrStyle{head}{halign=l} % ??
\usepackage{caption}
  \captionsetup{singlelinecheck=false}

\begin{document}

\begin{table}
  \begin{talltblr}[caption = The caption]
    {
      colspec = *7{X[c]} ,
      hline{1,Z} ,
    }
    1	& 2	& 3	& 4	& 5	& 6	& 7 \\
    1	& 2	& 3	& 4	& 5	& 6	& 7 \\
    1	& 2	& 3	& 4	& 5	& 6	& 7 \\
    1	& 2	& 3	& 4	& 5	& 6	& 7 \\  
  \end{talltblr}
\end{table}

\begin{table}
  \caption{The caption}
  \begin{tblr}
    {
      colspec = *7{X[c]} ,
      hline{1,Z} ,
    }
    1	& 2	& 3	& 4	& 5	& 6	& 7 \\
    1	& 2	& 3	& 4	& 5	& 6	& 7 \\
    1	& 2	& 3	& 4	& 5	& 6	& 7 \\
    1	& 2	& 3	& 4	& 5	& 6	& 7 \\  
  \end{tblr}
\end{table}

\end{document}
```
I expected that `\SetTblrStyle{head}{halign=l}` to correspond to `\captionsetup{singlelinecheck=false}`.
Caption alignment should have nothing to do with cell alignment (and therefore with column type).
Maybe I misunderstood the `halign` key?
Matteo

**Comment by hvoss49** [comment]
What do you expect for X columns which fit the total line width?

<img width="786" alt="Bildschirm­foto 2023-03-20 um 12 48 23" src="https://user-images.githubusercontent.com/12891199/226330845-a74bf932-3f75-4bb7-bbd1-5f1bcd6e7fdc.png">

**Comment by lvjr** [comment]
Sorry, I need to document this in a future release:
```latex
\SetTblrTemplate{caption}{simple}
```
in `tabularray` package corresponds to
```latex
\captionsetup{singlelinecheck=false}
```
in `caption` package.
