### ISSUE TITLE
Longtable without captions (and more)

### ISSUE THREAD

**Issue by R-van-Bakel** [lvjr/tabularray#389]
I have a request for a feature involving long tables. I don't think there is currently a way to create a long table, such that it has no captions (1), that it does not increment the table counter (2) and that it is not added to the list of tables (3). If there is currently a way to create long tables with these three features, I would like to know, otherwise I think this would be a nice feature to be added.

**Comment by muzimuzhi** [comment]
Try `\begin{longtblr}[entry=none, label=none]{...}`, see https://github.com/lvjr/tabularray/discussions/334#discussioncomment-4384372 . It's mentioned near the end of package doc, sec. 4.1 _A Simple Example_.

**Comment by R-van-Bakel** [comment]
> Try `\begin{longtblr}[entry=none, label=none]{...}`, see [#334 (comment)](https://github.com/lvjr/tabularray/discussions/334#discussioncomment-4384372) . It's mentioned near the end of package doc, sec. 4.1 _A Simple Example_.

That seems to have done the trick! I must have read over that part of the documentation. Thank you very much!
