### ISSUE TITLE
How to let longtable caption start from a new line?

### ISSUE THREAD

**Issue by DangeRS2** [lvjr/tabularray#395]
Hi,

I found some instructions in the manual, but still cannot get the following style.
```latex
\DefTblrTemplate{caption-tag}{default}{TABLE~\thetable}
\DefTblrTemplate{caption-sep}{default}{\par}
\DefTblrTemplate{caption-text}{default}{\InsertTblrText{caption}}
```

![image](https://user-images.githubusercontent.com/49086184/232956209-363aa06b-d0b3-45d7-84a8-5f3b475c4555.png)

**Comment by lvjr** [comment]
Please ask your questions on https://github.com/lvjr/tabularray/discussions
