### ISSUE TITLE
error when trying with texlive-2020 as delivered by Fedora 34

### ISSUE THREAD

**Issue by jtl5770** [lvjr/tabularray#4]
Hi,
I am trying to get the minimal program from the homepage to run under texlive-2020:
```
\documentclass{article}
\usepackage{tabularray}
\begin{document}
\begin{tblr}{|lc|r|}
\hline
One    & Two   & Three \\
Four   & Five  & Six \\
\hline
Seven  & Eight & Nine \\
\hline
\end{tblr}
\end{document}
```

Running this results in the following error on loading tabularray:

```
ERROR: Undefined control sequence.

--- TeX said ---
l.191 \NewDocumentCommand
                        \NewChildSelector { m O{0} o m }
--- HELP ---
TeX encountered an unknown command name. You probably misspelled the
name. If this message occurs when a LaTeX command is being processed,
the command is probably in the wrong place---for example, the error
can be produced by an \item command that's not inside a list-making
environment. The error can also be caused by a missing \documentclass
command.
```

**Comment by lvjr** [comment]
In old texlive 2020, you need to add \usepackage{xparse} to the preamble of the document.

**Comment by jtl5770** [comment]
I did, and that is the new error:

```
ERROR: Undefined control sequence.

--- TeX said ---
\NewDashStyle code ..._tmpa_seq {4}}\tl_if_eq:NnT 
                                                  \l__tblr_a_tl {on}{\tl_if_...

l.421 \NewDashStyle {dashed} {on ~ 2pt ~ off ~ 2pt}
                                                 
--- HELP ---
TeX encountered an unknown command name. You probably misspelled the
name. If this message occurs when a LaTeX command is being processed,
the command is probably in the wrong place---for example, the error
can be produced by an \item command that's not inside a list-making
environment. The error can also be caused by a missing \documentclass
command.
```

**Comment by muelli** [comment]
I'm seeing the same with the LaTeX provided by Ubuntu 20.04.
I'm looking forward to using the package in the future, then.

**Comment by lvjr** [comment]
I have backported missing \tl_if_eq:NnTF command for texlive 2020. You may download the latest https://github.com/lvjr/tabularray/raw/main/tabularray.sty
and test whether there are other missing commands in texlive 2020.

**Comment by lvjr** [comment]
Now `tabularray` should run well in texlive 2020.

**Comment by lvjr** [comment]
Also note that you need `ninecolors` package (https://ctan.org/pkg/ninecolors) if you are using colors.

**Comment by jtl5770** [comment]
I can confirm that tabularray now loads correctly in texlive 2020 and works with my minimal example. I didn't have the time yet to try complex stuff, but I assume that the original bug can be considered fixed. Thank you very much, looking forward into playing with this!
