### ISSUE TITLE
Slow Compilation With \NewTblrEnviron

### ISSUE THREAD

**Issue by R-van-Bakel** [lvjr/tabularray#407]
We implemented our own kind of tables using the \NewTblrEnviron command, but our document has now reached to point that compilation takes over two minutes. When the tables are removed, the file compiles in seconds. Is this a common problem and is there a way to fix it?

**Comment by muzimuzhi** [comment]
Do you mean that using builtin environments like `tblr` and `longtblr` is much faster than environments defined by `\NewTblrEnviron`?  Or it's just the `tabularray` itself that slows down the compilation?

Better to provide a (complete) example to show the difference.

**Comment by R-van-Bakel** [comment]
We are creating our own types of tables using the `\NewTblrEnviron` command in a separate `.cls` file. Even if we do not add any styling using `\SetTblrOuter` or `\SetTblrInner`, it is already very slow.

**Comment by lvjr** [comment]
I will close this since it is unclear.
