### ISSUE TITLE
Missing of the crucial trim option for \cmidrule

### ISSUE THREAD

**Issue by mhabets** [lvjr/tabularray#41]
Trim option for `\cmidrule` is _crucial_ to prevent the connection of the rule below column headings as for the rule below column headings "I" and "II" below:
![image](https://user-images.githubusercontent.com/2016449/126360797-c76a9e0f-bdc9-4c17-adf8-ed1e95f03094.png)
From [here](https://tex.stackexchange.com/q/156219/218146).

**Comment by lvjr** [comment]
The trim option is a little tricky to implement. It may not be added in a short while.

**Comment by lvjr** [comment]
A workaround: add an empty column there.

**Comment by lvjr** [comment]
I have implemented trim options for `booktabs` library. Note that the `l`, `r`, or `lr` options should be put in square brackets and their values are ratio numbers between `-1` and `0` (used to multiply `leftsep` or `rightsep`).

````latex
\documentclass{article}

\usepackage{tabularray}
\UseTblrLibrary{booktabs}

\begin{document}

\begin{tabular}{lcccc}
\toprule
  \multirow{2}[3]{*}{Sample} & \multicolumn{2}{c}{I} & \multicolumn{2}{c}{II} \\
\cmidrule(l{0.65em}r{0.65em}){2-3} \cmidrule(lr){4-5}
     & A & B &  C & D \\
\midrule
  S1 & 5 & 8 & 12 & 2 \\
  S2 & 6 & 9 &  2 & 6 \\
  S3 & 7 & 9 &  5 & 8 \\
  S4 & 8 & 9 &  8 & 2 \\
\bottomrule
\end{tabular}

\bigskip

\begin{tblr}{
  colspec = lcccc,
  cell{1}{1} = {r=2}{},
  cell{1}{2,4} = {c=2}{},
}
\toprule
  Sample & I &   & II &   \\
\cmidrule[lr=-1]{2-3} \cmidrule[lr]{4-5}
         & A & B & C  & D \\
\midrule
  S1     & 5 & 8 & 12 & 2 \\
  S2     & 6 & 9 &  2 & 6 \\
  S3     & 7 & 9 &  5 & 8 \\
  S4     & 8 & 9 &  8 & 2 \\
\bottomrule
\end{tblr}

\end{document}
````

![image](https://user-images.githubusercontent.com/4239949/130093624-de5863c0-82fe-44d7-8585-16b6a41799ca.png)
