### ISSUE TITLE
Vline and hline specs with macros

### ISSUE THREAD

**Issue by cpierquet** [lvjr/tabularray#413]
Hi-
I want to create a tabular with options for thickness and color rules, but with color it's not working :

```
\documentclass{article}
\usepackage{tabularray}

\def\MPMThick{2pt}
\def\MPMLargBoite{0.65cm}
\def\MPMFont{\scriptsize\sffamily}
\def\MPMColor{orange}
```

With this code, it's working (thickness is OK) :
```
\begin{tblr}{rowsep=1pt,colsep=1pt,%
    hlines={\MPMThick},vlines={\MPMThick},%
    colspec={Q[\MPMLargBoite,m,c]Q[\MPMLargBoite,m,c]},
    cells={font=\MPMFont},
    row{1}={font=\bfseries\MPMFont}
    }
    \SetCell[c=2]{c} {Début} & \\
	{0} & {0} \\
\end{tblr}
```
![image](https://github.com/lvjr/tabularray/assets/45103962/ecd85d35-c9ef-486a-baf9-4222978293f3)

With this code, it's not working :
```
\begin{tblr}{rowsep=1pt,colsep=1pt,%
    hlines={\MPMColor},vlines={\MPMColor},%
    colspec={Q[\MPMLargBoite,m,c]Q[\MPMLargBoite,m,c]},
    cells={font=\MPMFont},
    row{1}={font=\bfseries\MPMFont}
    }
    \SetCell[c=2]{c} {Début} & \\
	{0} & {0} \\
\end{tblr}
```
![image](https://github.com/lvjr/tabularray/assets/45103962/e5c489ae-607a-449b-b503-f42b97be1858)

I'm a wrong with the syntax ?

**Comment by note286** [comment]
```latex
hlines={wd=\MPMThick,fg=\MPMColor},
vlines={wd=\MPMThick,fg=\MPMColor},
```

**Comment by cpierquet** [comment]
> ```
> hlines={wd=\MPMThick,fg=\MPMColor},
> vlines={wd=\MPMThick,fg=\MPMColor},
> ```

It's perfect !!
