### ISSUE TITLE
Naming consistency: `\NewTableCommand` vs `\NewTblr...`

### ISSUE THREAD

**Issue by muzimuzhi** [lvjr/tabularray#421]
`tabularray` 2023A (2023-03-01) provides
- `\NewTableCommand`

But `Tblr`, instead of `Table`, is used as the middle part of names of more commands:
- `\NewTblrEnviron`, `\NewTblrTheme`, and `\NewTblrLibrary`
- `\SetTblrInner`, `\SetTblrOuter`, `\SetTblrStyle`, `\SetTblrTemplate`, and `\SetTblrTracing`

Is the special naming of `\NewTableCommand` on purpose?

**Comment by lvjr** [comment]
There is also `\NewContentCommand` in `tabularray`. But I have no plan to  rename them

**Comment by lvjr** [comment]
Well, the meaning of `\NewTableCommand` is clear, but that of `\NewContentCommand` is unclear. Better to add `Tblr` to both of the names (and keep the old names).

**Comment by lvjr** [comment]
I added `Tblr` to the names of commands `\NewDashStyle`,  `\NewColumnType`, `\NewRowType` and `\NewColumnRowType`. Now all public commands have `Tblr` in their names.
