### ISSUE TITLE
Beamer overlays with \SetRow

### ISSUE THREAD

**Issue by dmort27** [lvjr/tabularray#429]
Thank you for creating `tabularray`, one of my top-four LaTeX packages of all time!

I would like to animate the styling of a `tblr` using `beamer` overlays. Something like this:

```latex
\begin{tblr}{ccc}
  \onslide<2->{\SetRow{cyan7}} 1 & 2 & 3\\
  4 & 5 & 6\\
\end{tblr}
```

I want the first row to have a cyan background on the second slide displaying the table, but not the first. However, this does not seem to work. I have also tried the `beamer` `\only` command, with the same result. Is there currently a way of achieving this? If not, is there any plan to add such a feature?

**Comment by muzimuzhi** [comment]
This seems to work.
```tex
\documentclass{beamer}
\usepackage{tabularray}

\NewTableCommand{\beamerTemporal}[4]{\temporal<#1>{#2}{#3}{#4}}

\begin{document}
\begin{frame}
  \begin{tblr}{ccc}
    \beamerTemporal{2-}{}{\SetRow{cyan7}}{} 1 & 2 & 3 \\
    4 & 5 & 6 \\
  \end{tblr}
\end{frame}
\end{document}
```
![image](https://github.com/lvjr/tabularray/assets/6376638/9bc0ab56-2a55-4677-97b3-3ab996074cf2)

> is there any plan to add such a feature?

According to #54 and #226, no `tabularray` has no plan to provide (built-in) support for beamer overlays.

**Comment by dmort27** [comment]
Thank you very much! This solves my problem.
