### ISSUE TITLE
Setting `\hfuzz=\maxdimen` completely breaks X columns

### ISSUE THREAD

**Issue by IsaacOscar** [lvjr/tabularray#445]
In order to silence annoying overfull hbox warnings when I'm compiling a draft, I set `\hfuzz=\maxdimen`. But this broke all my X columns (they were 0 width).
I found the cause of the problem:

https://github.com/lvjr/tabularray/blob/690e67ee175ff7601d0144c84f9a7e9c67573e0b/tabularray.sty#L4099

Using `xpatchcmd` I modifed the above to use `0pt` in place of `\hfuzz`, which solved my problem. 

But not having to use `xpatchcmd` would probably be better, I'd submit a pull request myself, but I'm not sure what that line is actually doing, and whether `0pt` is a sensible value, or even if it would be usefull to make it user configurable.

**Comment by lvjr** [comment]
We need to use our own `hfuzz` dimension instead of global `\hfuzz` dimension in `tabularray`.

**Comment by lvjr** [comment]
This bug has been fixed.
