### ISSUE TITLE
borders of tabular environment in a cell of tabularray are lost

### ISSUE THREAD

**Issue by tajpulo** [lvjr/tabularray#447]
## Example

```
\documentclass{article}
\usepackage{tabularray}
\usepackage{graphicx}

\begin{document}

      \begin{tblr}{colspec = {X[10em,m,c] X[m,c]}, width = {\linewidth}}
          {
            \begin{tabular}{c|c}
             $ x $ & $f(x)$ \\
            \hline
             $-2 $ &     \\
             $-1 $ & $5$ \\
             $ 0 $ &     \\
             $ 1 $ &     \\
             $ 2 $ &     \\
             $ 3 $ & $-3$
            \end{tabular}
          }
        &
          \raisebox{-.5\height}{\includegraphics[width=0.7\textwidth]{example-image-a}}
      \end{tblr}

\end{document}
```

Compiled with: `lualatex --halt-on-error --interaction=nonstopmode mwe.tex`

## Expected behavior

Borders of tabular like `|` are respected and shown.

## Actual behavior

![image](https://github.com/lvjr/tabularray/assets/97669430/78390cb4-e9ad-4735-8e0b-f853441aa90b)

**Comment by muzimuzhi** [comment]
Can't reproduce, both locally and using Overleaf's texlive 2023.
![image](https://github.com/lvjr/tabularray/assets/6376638/cac3d990-8dc8-4908-beea-311b4edf0dd6)

Does zooming in makes the missing horizontal line correctly rendered?

**Comment by tajpulo** [comment]
No, it is a valid point, but not a rendering issue.

But I might just be subject to deprecated versions. debian ships an old texlive-full installation and thus upgrading should fix it then. If you think so too, please close the issue. For now, I attach relevant version numbers:

* `LuaHBTeX, Version 1.14.0 (TeX Live 2022/dev/Debian)`
* `LaTeX2e <2021-11-15> patch level 1`
* `Document Class: article 2021/10/04 v1.4n Standard LaTeX document class`
* `Package: expl3 2022-01-21 L3 programming layer (loader)`
* `Package: tabularray 2021-12-01 v2021Q Typeset tabulars and arrays with LaTeX3`

**Comment by muzimuzhi** [comment]
> But I might just be subject to deprecated versions.

You reminded me. I think this is a duplicate of #31, which has been fixed since release [2022C](https://github.com/lvjr/tabularray/releases/tag/2022C) (2022-07-01).

Overleaf's texlive 2022 mirror provides `tabularray` v2022B, hence can reproduce the problem. The problem disappeared after uploading [`tabularray.sty` at v2022C](https://github.com/lvjr/tabularray/blob/2022C/tabularray.sty).

**Comment by muzimuzhi** [comment]
Duplicate of #31.

**Comment by tajpulo** [comment]
Then sorry for the noise and thank you very much for your efforts 😊
