### ISSUE TITLE
StackExchange suggestion for 'remove column' doesn't work in tblr

### ISSUE THREAD

**Issue by jonhall** [lvjr/tabularray#451]
https://tex.stackexchange.com/questions/16604/easiest-way-to-delete-a-column suggests the use of the following to remove a column from a table (rewritten to tblr syntax):

`\NewColumnType{H}{Q[preto={\setbox0=\hbox\bgroup},appto={\egroup},c]}`

This works for ordinary entries, but (apparently) not for entries needing vbox:

```
\documentclass[10pt]{article}

\usepackage{tabularray}
\UseTblrLibrary{varwidth}%%For itemize in entries

\begin{document}

%%Example of 'H' column from https://tex.stackexchange.com/questions/16604/easiest-way-to-delete-a-column
\NewColumnType{H}{Q[preto={\setbox0=\hbox\bgroup},appto={\egroup},c]}

\begin{tblr}{
	colspec={lHl},
	measure=vbox,
	}
	
One&Two&Three\\

One
&\begin{itemize}%%comment this Cell out to make MWE work
\item one
\item two
\end{itemize}
&Three\\
\end{tblr}
\end{document}
```

**Comment by jonhall** [comment]
Temporary workaround to hide a column is

`\NewColumnType{H}{Q[fg={white},wd=0pt,c]}`

**Comment by jonhall** [comment]
The following appears to work (and I should have guessed, apologies)

```
\newcommand{\zerobox}[1]{\setbox0=\vbox{#1}}
\NewColumnType{H}{Q[cmd=\zerobox]}

```

**Comment by muzimuzhi** [comment]
I posted a revised version as a [new answer](https://tex.stackexchange.com/a/700943) to the TeX-SX question you mentioned.

Please post questions as [discussions](https://github.com/lvjr/tabularray/discussions), and only bug reports and feature requests as issues in the future.
