### ISSUE TITLE
`NewColumnType` doesn't have the corresponding `RenewColumnType`

### ISSUE THREAD

**Issue by jonhall** [lvjr/tabularray#452]
With `\newcommand` we have a `\renewcommand` to safely redefine a command. 

`NewColumnType` doesn't have the corresponding `RenewColumnType`. Using `NewColumnType` twice issues an error.

**Comment by muzimuzhi** [comment]
I infer the original consideration is to make built-in column and row types static.

To provide `\RenewColumnType` and `\RenewRowType`, `tabularray` would need to be able to distinguish built-in and user-defined types. There's also an undocumented command `\NewColumnRowType`.

**Comment by jonhall** [comment]
Thank you for your comment. The intention was not to make built-in column and row types states, but to permit their controlled redefinition via the new command. 

I accept the this might not be possible without substantial changed of the form you suggest.
