### ISSUE TITLE
graphics and tblr

### ISSUE THREAD

**Issue by syvshc** [lvjr/tabularray#46]
I want to include some graphics in tblr. I'd like to put a figure and the text in 2 rows and let them align at center vertically. My English is poor, so here is the mwe:
```latex
\documentclass{article}
\usepackage{tabularray}
\usepackage{graphicx}
\begin{document}
    \begin{tblr}{
        vline{2},
        hlines,
        row{1}      =   {c, m},
        cell{1}{2}  =   {h},
        cell{2}{2}  =   {m}
    }
        text & \includegraphics[width = 2cm]{example-image-a}\\ 
        text & \includegraphics[width = 2cm]{example-image-b}\\     
    \end{tblr}
\end{document}
```
![image](https://user-images.githubusercontent.com/38098591/127767395-de0e57fc-0145-407c-ae68-1c6508360568.png)

I want something like the image-a, but image-a's top and bottom's sep seems not same. How can I do this?

**Comment by lvjr** [comment]
The extra space is from the `stretch`. You may set `stretch=0`:
````latex
\begin{tblr}{
    vline{2},
    hlines,
    row{1}      =   {c, m},
    cell{1}{2}  =   {h},
    cell{2}{2}  =   {m},
    stretch = 0,
}
    text & \includegraphics[width = 2cm]{example-image-a}\\ 
    text & \includegraphics[width = 2cm]{example-image-b}\\     
\end{tblr}
````
![image](https://user-images.githubusercontent.com/4239949/127767622-1f01fd02-9410-4425-848c-6cc425b8c403.png)
