### ISSUE TITLE
make features of `\UseTblrLibrary{amsmath}` enable on `physics` package

### ISSUE THREAD

**Issue by Firestar-Reimu** [lvjr/tabularray#462]
> Each of the environments is similar to the environment without `+` prefix in its name, but has default `rowsep=2pt` just as `tblr` environment.

I want this feature also enabled on `physics`, like:

`\mqty` `\bmqty` `\mdet` `\imat` etc.

**Comment by muzimuzhi** [comment]
These `physics` matrix macros breaks `tabularray`'s requirement on table-like environment content, that `&` and `\\` must be seen explicitly.

Currently the only supported way to generate cells is by using outer key `evaluate`, provided by `functional` library. But `amsmath`-derived environments like `+pmatrix` accepts inner keys only, in form of optional argument of environment.

Also to support `\mqty` and friends, `tabularray` lacks the ability to manipulate structure of table cells.

**Comment by lvjr** [comment]
Anyone can write a new package for this feature. But I need to keep `tabularray` minimal.
