### ISSUE TITLE
LaTeX3 modules/prefixes other than `tblr` in use

### ISSUE THREAD

**Issue by muzimuzhi** [lvjr/tabularray#469]
`tabularray` registers `tblr` LaTeX module name (prefix) in LaTeX3 repo (see [`l3prefixes.csv`](https://github.com/latex3/latex3/blob/main/l3kernel/doc/l3prefixes.csv)), but prefixes `column` and `row` are also found in source code.

```
$ rg --no-heading 'new:N\s*\\[lgc]__[^t]' -g '!build'

tabularray.sty:4018:\dim_new:N \l__column_target_dim
tabularray.sty:4019:\prop_new:N \l__column_coefficient_prop
tabularray.sty:4020:\prop_new:N \l__column_natural_width_prop
tabularray.sty:4021:\prop_new:N \l__column_computed_width_prop
tabularray.sty:6303:\dim_new:N \l__row_upper_dim
tabularray.sty:6304:\dim_new:N \l__row_lower_dim
tabularray.sty:6305:\dim_new:N \l__row_vpace_dim
```

I suggest to rename these variables so that `tabularray` sticks to `tblr` prefix.

**Comment by lvjr** [comment]
Please fix them if you want to.

**Comment by FrankMittelbach** [comment]
I think it would be good if generic names like "column" and "row" would not become module names, thus please use `\l__tblr_column` etc,
