### ISSUE TITLE
Cell grows higher than `\diagbox` needed

### ISSUE THREAD

**Issue by muzimuzhi** [lvjr/tabularray#471]
With large enough `abovesep` and `belowsep`, cells containing `\diagbox` grow higher than needed.

In example below, tables in first column show the natural height of first rows. Tables in second and third columns show how `\diagbox` enlarges first rows. When either `abovesep` or `belowsep` is set to 7pt, a small gap is seen at the top or bottom of cell (1, 1), respectively. I think such gaps should be avoided.

```tex
\documentclass{article}
\usepackage{tabularray}
\usepackage{pgffor}

\UseTblrLibrary{diagbox}

\newcommand{\testDiagbox}[1]{
  \begin{tblr}{}
    #1 \\
    A & B & C & D \\
  \end{tblr}
}

\SetTblrOuter{baseline=B}
\SetTblrInner{hlines, vlines}

\begin{document}

\foreach \i in {2pt, 5pt, 7pt, 10pt} {
  \noindent\llap{belowsep=\i}
  \SetTblrInner{row{1} = {belowsep=\i}}
  \testDiagbox{}
  \testDiagbox{\diagbox{}{}}
  \testDiagbox{\diagbox{X}{Y}}
  \par\medskip
}

\foreach \i in {2pt, 5pt, 7pt, 10pt} {
  \noindent\llap{abovesep=\i}
  \SetTblrInner{row{1} = {abovesep=\i}}
  \testDiagbox{}
  \testDiagbox{\diagbox{}{}}
  \testDiagbox{\diagbox{X}{Y}}
  \par\medskip
}

\end{document}
```

![image](https://github.com/lvjr/tabularray/assets/6376638/035e67f8-8b1c-4f90-8d19-38e865567c2e)
![image](https://github.com/lvjr/tabularray/assets/6376638/40da30d4-f798-4629-b170-f96e84e6fd5f)

**Comment by lvjr** [comment]
Better be fixed in `diagbox` package, which hasn't been updated for some years and doesn't know `\abovesep` and `\belowsep` yet.

**Comment by muzimuzhi** [comment]
`\abovesep` and `\belowsep` are only declared in `tabularray`, not by any other table-related packages (quickly checked in texstudio's completion files), thus even author `diagbox` becomes re-active, these two dimensions can only be used by future versions of `diagbox` when it detects that `tabularray` is loaded and `\diagbox` is actually used directly inside a `tblr`-like table, i.e., not directly in a normal `tabular` table nested in `tblr`.

So I think patching `diagbox` in `tabularray` is more likely to happen.
https://github.com/lvjr/tabularray/blob/eca12d98d541d936c4bc7c34d7dc5b0a9280206e/tabularray.sty#L164-L168

**Comment by muzimuzhi** [comment]
Ah maybe you meant similar to what I wrote in https://github.com/lvjr/tabularray/issues/347#issuecomment-1373185407

> It would be better if `diagbox` provides options to set above and below inner- and outer-seps.

Then yes, it's better to be done on `diagbox`'s side.

**Comment by lvjr** [comment]
> `\abovesep` and `\belowsep` are only declared in `tabularray`, not by any other table-related packages (quickly checked in texstudio's completion files), thus even author `diagbox` becomes re-active, these two dimensions can only be used by future versions of `diagbox` when it detects that `tabularray` is loaded and `\diagbox` is actually used directly inside a `tblr`-like table, i.e., not directly in a normal `tabular` table nested in `tblr`.

With a little code improvement in `tabularray` it is easy to make `diagbox` know whether it is directly inside a `tblr`-like table. But I would avoid patching any other package in `tabularray` whenever possible.

> So I think patching `diagbox` in `tabularray` is more likely to happen.
