### ISSUE TITLE
Key `hline` shows inconsistent behaviour in `longtblr`

### ISSUE THREAD

**Issue by guemax** [lvjr/tabularray#489]
The key `hline` seems to be inconsistent when used in a `longtblr`. In the following MVP I added an `hline` above and below the first row of the table. Notice that the `hline` above the first row appears again at the first row of the continued table, but the `hline` below does not (exactly how I think it should be).

For comparison, I also colored the first row of the table. This color is *not* repeated for the first row of the continued table. In my opinion, `hline` should behave just like `row`.

```tex
\documentclass{article}

\usepackage{tabularray}
\usepackage{xcolor}

\begin{document}

\begin{longtblr}[
  caption = {A Long Long Long Long Long Long Long Table},
  ]{
    hline{1,2},
    colspec = {XXX}, width = 0.85\linewidth,
    row{1} = {purple7}
  }
  Alpha & Beta & Gamma \\
  Epsilon & Zeta & Eta \\
  Iota & Kappa & Lambda \\
  Nu & Xi & Omicron \\
  Rho & Sigma & Tau \\
  Phi & Chi & Psi \\
  .......
  Alpha & Beta & Gamma \\
  Epsilon & Zeta & Eta \\
  Iota & Kappa & Lambda \\
  Nu & Xi & Omicron \\
  Rho & Sigma & Tau \\
  Phi & Chi & Psi \\
\end{longtblr}
\end{document}
```
![test](https://github.com/lvjr/tabularray/assets/93522160/7a238ca7-c744-4435-8334-2718b024cc1e)

PS:  Thank you so much for this wonderful package! :+1:

**Comment by muzimuzhi** [comment]
Related to
- #50
- #130

Here's a revised example in which the `longtblr` does trigger page breaks:
```tex
\documentclass{article}

\usepackage{tabularray}
\usepackage{xcolor}

\usepackage[paperheight=6cm]{geometry}

\begin{document}

\begin{longtblr}[
  caption = {A Long Long Long Long Long Long Long Table},
]{
  hline{1,2},
  colspec = {XXX}, width = 0.85\linewidth,
  row{1} = {purple7}
}
  Alpha & Beta & Gamma \\
  Epsilon & Zeta & Eta \\
  Iota & Kappa & Lambda \\
  Nu & Xi & Omicron \\
  Rho & Sigma & Tau \\
  Phi & Chi & Psi \\
  ....... \\
  Alpha & Beta & Gamma \\
  Epsilon & Zeta & Eta \\
  Iota & Kappa & Lambda \\
  Nu & Xi & Omicron \\
  Rho & Sigma & Tau \\
  Phi & Chi & Psi \\
\end{longtblr}
\end{document}
```

![image](https://github.com/lvjr/tabularray/assets/6376638/1067006b-9e02-40a1-9202-cb374916d35c)
