### ISSUE TITLE
\SetCell breaks the line breaking

### ISSUE THREAD

**Issue by suuuehgi** [lvjr/tabularray#499]
Without further knowledge, I assume that `\SetCell` adheres to the `width = 0.85\linewidth`, but this is not the case.

```latex
\documentclass{scrartcl}
\usepackage{tabularray, blindtext}


\begin{document}
\begin{longtblr}{
    width = 0.85\linewidth,
    colspec = {|rX|}
    }
 \hline
 test & \blindtext \\
 % \SetCell[c=2]{l} \blindtext\\ % <-- uncomment this line to break the text alignment
 \hline
\end{longtblr}
\end{document}

```

![Screenshot from 2024-05-31 00-15-47](https://github.com/lvjr/tabularray/assets/7861774/73a0152f-e639-4d20-a32e-d80744055209)
![Screenshot from 2024-05-31 00-16-04](https://github.com/lvjr/tabularray/assets/7861774/ed2a1a75-509b-4b26-979f-5a2b26e89ec7)

Current git version.

**Comment by sgolovan** [comment]
In your `\SetCell` argument you specify the cell spec `l` which means that it is formatted as a one-line cell. One way to mitigate this is to add `hspan=minimal` to the table options. It would mean that cell width is calculated using small one-column cells, and the span cells just use this calculated width. Also, you may want to replace `l` by `j` to make the span cell justified.

The code:

```
\documentclass{scrartcl}
\usepackage{tabularray, blindtext}


\begin{document}
\begin{longtblr}{
    width = 0.85\linewidth,
    colspec = {|rX|},
    hspan = minimal
    }
 \hline
 test & \blindtext \\
 \SetCell[c=2]{j} \blindtext\\
 \hline
\end{longtblr}
\end{document}
```

**Comment by suuuehgi** [comment]
Thank you very much! But shouldn't one-line cells stick to the outside width of the table?

**Comment by sgolovan** [comment]
If you use `l` instead of `X` in the colspec argument, the whole paragraph turns into one line ignoring the width specification. Something similar happens with `\SetCell` and the default `hspan` value.
