### ISSUE TITLE
Set all cells content alignment 

### ISSUE THREAD

**Issue by Firestar-Reimu** [lvjr/tabularray#502]
I have a 10*25 big table, and I do not want to print `|c|c|c|c|c|c|c|c|c|c|` and 26 `\hline`, so I use `\begin{longtblr}{hlines,vlines}`

Now I want to set all contents align center/left/right in the cell

But I cannot find such setting in doc

**Comment by muzimuzhi** [comment]
Both `colspec={*{25}{<column type>}}` and `cells={<cell keys>}` work.

```tex
\documentclass{article}
\usepackage{tabularray}

\begin{document}
\begin{tblr}{hlines, vlines}
  a & a & a \\
  aa & aa & aa \\
  aaa & aaa & aaa
\end{tblr}

\begin{tblr}{hlines, vlines, colspec={*{3}{c}}}
  a & a & a \\
  aa & aa & aa \\
  aaa & aaa & aaa
\end{tblr}

\begin{tblr}{hlines, vlines, cells={r}}
  a & a & a \\
  aa & aa & aa \\
  aaa & aaa & aaa
\end{tblr}
\end{document}
```
![image](https://github.com/lvjr/tabularray/assets/6376638/3907eedd-047e-4f35-a15d-2e3c22bc65f7)

**Comment by Firestar-Reimu** [comment]
Thanks! `cells=` is the most elegant.
