### ISSUE TITLE
+cases environment does not emulate the traditional cases

### ISSUE THREAD

**Issue by Basmah1961** [lvjr/tabularray#507]
![image](https://github.com/lvjr/tabularray/assets/94080257/16d91eec-e28f-408d-806c-a137fb2e1a23)

The rules above shows the issue clearly. When the option `fleqn` in `amsmath` is enabled, `+cases` emulates the traditional `cases` perfectly

```
\documentclass{article}

\usepackage{xcolor}

\usepackage{amsmath}

\usepackage{tabularray}
\UseTblrLibrary{amsmath}

\begin{document}

\begin{align*}
	a_n
	&=\smash{\color{gray}\llap{\vrule width 1pt depth 5em height 0em}} (-1)^n
	\\
	&=
	\begin{cases}
		+1 \\
		-1
	\end{cases}
\end{align*}

\vspace{-1em}

\begin{align*}
	a_n
	&=\smash{\color{gray}\llap{\vrule width 1pt depth 0em height 5em}} (-1)^n \\
	&=
	\begin{+cases}
		+1 \\
		-1
	\end{+cases}
\end{align*}

\end{document}
```

**Comment by lvjr** [comment]
Actually, `cases` environment in `amsmath` always assumes there are two columns, therefore extra `\quad` space at the right side is not removed when there are only one column. 

```latex
\def\env@cases{%
  \let\@ifnextchar\new@ifnextchar
  \left\lbrace
  \def\arraystretch{1.2}%
  \array{@{}l@{\quad}l@{}}%
}
```

I would consider it a bug of `amsmath` and `+cases` environment will not emulate the `cases` environment.

```latex
\documentclass{article}
\usepackage{tabularray}
\UseTblrLibrary{amsmath}
\begin{document}

\texttt{cases}: \fbox{$\begin{cases}+1 \\ -1\end{cases}$}

\texttt{+cases}: \fbox{$\begin{+cases}+1 \\ -1\end{+cases}$}

\end{document}
```

<img width="309" alt="image" src="https://github.com/user-attachments/assets/4336e98c-0283-4387-a6b9-62c5b174151b">
