### ISSUE TITLE
[Bug] Footnote (`\TblrNote{<num>}`) will obscure the parentheses when used together with parentheses

### ISSUE THREAD

**Issue by Mikachu2333** [lvjr/tabularray#511]
As the titile shows. Here is a pic which might help people to understand the title.

Chinese also has this issues.

![图片](https://github.com/user-attachments/assets/ce3ecf78-bd5f-43f1-9c11-53f476d74f14)

### English only
```latex
% !TeX encoding = UTF-8
\documentclass{article}
\usepackage{tabularray}

\begin{document}

\begin{tblr}[
		long,
		note{1} = {Footnote test.},
	]{
		cells = {c,m},
		hlines,
		vlines,
	}
	English & (Test\TblrNote{1})

\end{tblr}

\end{document}
```

### Chinese-English

![图片](https://github.com/user-attachments/assets/3520ba3e-7bb5-454f-b680-d9c1a60c6fdd)

```latex
% !TeX encoding = UTF-8
\documentclass[UTF8]{ctexrep}
\usepackage{tabularray}

\begin{document}

\begin{tblr}[
		long,
		note{1} = {脚注测试。Footnote test.},
	]{
		cells = {c,m},
		hlines,
		vlines,
	}
	Chinese-English & （测试Test\TblrNote{1}) \\
	English-Chinese & (Test测试\TblrNote{1}） \\
	Chinese         & （测试\TblrNote{1}）    \\
	English         & (Test\TblrNote{1})

\end{tblr}

\end{document}
```

**Comment by muzimuzhi** [comment]
You can redefine `\TblrOverlap`, which is initially let to `\rlap` (thus the behavior you reported) and unfortunately is undocumented.

See https://github.com/lvjr/tabularray/issues/198#issuecomment-1033503487 and https://github.com/lvjr/tabularray/issues/473#issuecomment-1938448460 for some examples.

**Comment by Mikachu2333** [comment]
Thanks a thousand of time!
