### ISSUE TITLE
Compilation Failure Using `datatool` with `tabularray` in LaTeX: Incompatibility with `\DTLforeach` Function

### ISSUE THREAD

**Issue by EvilCheetah** [lvjr/tabularray#514]
**Describe the bug**
When using the `datatool` package in combination with `tabularray`, specifically when utilizing the `\DTLforeach` function, the compilation fails with an error.

**Expected Behavior**
The expected behavior is a successful compilation with correct `datatool` utilization. An example of this is provided in the section `Minimum Working Example to Reproduce the Problem`, along with a link to the [Repository](https://github.com/EvilCheetah/latex/tree/datatool-tabularray).

**Minimum Working Example to Reproduce the Problem**
A minimum example is shown in the [Repository](https://github.com/EvilCheetah/latex/tree/datatool-tabularray)

An overview of the Example:
Data:
```csv
Name,Email
Alice Smith,alice@example.com
Bob Johnson,bob@example.com
Charlie Brown,charlie@example.com
```
Generator Function:
```tex
% functions/display-members.tex

\newcommand{\DisplayMembers}{%
    \DTLforeach
        {teamdata}{\name=Name,\email=Email}
        {%
            \name & \email \\
        }%
}
```
Tablulated Data:
```tex
% content/index.tex

\begin{tblr}{
    colspec = {|c|X|}
}
    \hline
    \textbf{Name} & \textbf{Email}      \\ \hline[solid,1pt]
    \DisplayMembers
    \hline
\end{tblr}
```

**Specifications**
Packages:
`datatool` 2019/09/27 v2.32 (NLCT)
`tabularray` 2024-02-16 v2024A Typeset tabulars and arrays with LaTeX3

Compiler:
`Latexmk`, John Collins, 7 Apr. 2024. Version 4.85
`pdfTeX`, Version 3.141592653-2.6-1.40.26 (MiKTeX 24.4) (preloaded format=pdflatex 2024.9.29)

Platform:
`Microsoft Windows 11 Pro` 10.0.22631 N/A Build 22631
`MacOS Sonoma 14.5` Build 23F79

**Error Message**
```
! Misplaced alignment tab character &.
<argument> ...annumeral \dtlforeachlevel }}\name &
                                                   \email \\ \edef \@dtl@tmp...
l.9 \end
        {tblr}
```

**Additional context**
I have attempted to research how to fix this issue, but the only solutions I could find are from Stack Exchange:
- [Stack Exchange - Using datatool with tabularray](https://tex.stackexchange.com/questions/703051)
- [Stack Exchange - How to use DTLforeach (datatool) within a tabularray table?](https://tex.stackexchange.com/questions/638066)

Unfortunately, these solutions don't solve this issue in a nice and elegant way.

**Comment by muzimuzhi** [comment]
> In contrast to traditional `tabular` environment, `tabularray` environments need to see every `&` and `\\` when splitting the table body with `l3regex`.
>
> _`tabularray` package doc (2024A, 2024-02-16), sec. 3.2.3 Expand Macros First_

As the `\DTLforeach` is not fully expandable, you have to collect and store the processed data in a macro then use it with `expand=<\cmd>`, as the first linked Stack Exchange answer did.

`tabularray`'s `functional` library provides a new way to do the collection, but I'm afraid that's not "nice and elegant" to you too.

To process CSV files, you can also try with `csvsimple-l3` package which can automatically collect and then typeset the processed data.

```tex
\begin{filecontents}{members.example.csv}
Name,Email
Alice Smith,alice@example.com
Bob Johnson,bob@example.com
Charlie Brown,charlie@example.com
\end{filecontents}

\documentclass{article}
\usepackage{tabularray}
\usepackage{csvsimple-l3}

\begin{document}
\csvreader[
  head to column names,
  tabularray={colspec={|c|X|}, hline{1,Z}},
  table head={\textbf{Name} & \textbf{Email} \\ \hline[solid,1pt]}
]{members.example.csv}{}{\Name & \csvexpnot\ttfamily \Email}
\end{document}
```

![image](https://github.com/user-attachments/assets/1d5cef1b-2326-4f86-a1c7-45e584b57a4a)

**Comment by EvilCheetah** [comment]
Hi @muzimuzhi!
I really appreciate your help!

I skimmed through the documentation of `csvsimple`, and it turns out you can even handle conditionals using the `filter test` parameter in combination with the `etoolbox` package, referencing indexed columns like `csvcoli`! 😱
This IS an elegant solution! Thank you so much for your help and time!
