### ISSUE TITLE
Variable has not been (LaTeX) declared in tabularray Error while using tagpdf

### ISSUE THREAD

**Issue by baskar-67** [lvjr/tabularray#518]
The tabularray.sty style files working fine. If I add tagpdf package then tabularray package shows continuously error variables have not been declared the following varibles errors comes
\g__tblr_table_cmd_SetHlines_arg_numb_tl
\g__tblr_table_cmd_cline_arg_numb_tl
\g__tblr_table_cmd_SetHline_arg_numb_tl
\g__tblr_table_cmd_firsthline_arg_numb_tl
 \g__tblr_table_cmd_lasthline_arg_numb_tl
 \g__tblr_table_cmd_SetVlines_arg_numb_tl
 \g__tblr_table_cmd_rline_arg_numb_tl
 \g__tblr_table_cmd_vline_arg_numb_tl

**Comment by muzimuzhi** [comment]
Already reported by https://github.com/lvjr/tabularray/issues/22#issuecomment-2399764343, which would be fixed by #517.
