### ISSUE TITLE
With inclusion of `cm-super` package, ppm check now also passes on Ubuntu and macOS

### ISSUE THREAD

**Issue by muzimuzhi** [lvjr/tabularray#521]
With the inclusion of `cm-super` font package, the ppm check (done by `texlua buildend.lua` after `l3build check`) now also passes on Ubuntu (see [workflow log](https://github.com/lvjr/tabularray/actions/runs/11431772746/job/31801227465#step:6:8)) and macOS (verified locally).

Thus the words in `CONTRIBUTING.txt` can perhaps be updated
https://github.com/lvjr/tabularray/blob/77ca1bc7393f6ca1ec9846381acb76ef3b91ae5c/CONTRIBUTING.txt#L26-L28

**Comment by lvjr** [comment]
Good news!
