### ISSUE TITLE
Use linked property lists

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#541]
In 2021, there were only flat property lists in LaTeX3, so I had to use intarrays and others in adding support for long `tabularray` tables. Nevertherless, long tables are still very slow. Now there are linked property lists in LaTeX3, we can use them to make `tabularray` run faster.

**Comment by lvjr** [comment]
Recently @muzimuzhi found a bug of linked property lists: https://github.com/latex3/latex3/issues/1630 . Not sure whether texlive 2023 users can use them.

**Comment by muzimuzhi** [comment]
Possible to [get around it](https://github.com/muzimuzhi/tabularray-dev/blob/355b90dd3f1308787d5540de7865f3f980801327/zutil/zutil-debug.code.tex#L54-L69) in user-level code.

**Comment by jasperhabicht** [comment]
Another way: Use `\IfExplAtLeastTF { 2024-12-09 } { ... }` and only use linked props if the kernel version is new enough.

**Comment by lvjr** [comment]
`\IfExplAtLeastTF` was added in LaTeX release 2023-11-01 (see https://github.com/latex3/latex2e/issues/1004).

**Comment by lvjr** [comment]
I did an experiment with linked property lists by running `benchmark.lua`:
```
flat prop - default

pdflatex average time   old = 4.9162483215332   new = 3.6152496337891   ratio = 0.73536758059072
xelatex average time    old = 4.9034996032715   new = 3.763744354248    ratio = 0.76756289563825
lualatex average time   old = 5.6615371704102   new = 4.3742446899414   ratio = 0.77262491762895

flat prop - map_intarray_to_prop

pdflatex average time   old = 4.7424964904785   new = 163.32824707031   ratio = 34.43929740343
xelatex average time    old = 4.8482513427734   new = 167.75849914551   ratio = 34.601856893323
lualatex average time   old = 5.6224708557129   new = 116.71787261963   ratio = 20.759177880137

linked prop - map_intarray_to_prop

pdflatex average time   old = 4.8002471923828   new = 3.1875038146973   ratio = 0.66402909828379
xelatex average time    old = 4.9862480163574   new = 3.3210029602051   ratio = 0.6660324455002
lualatex average time   old = 5.6324348449707   new = 3.9444580078125   ratio = 0.70031134249774
```
It turns out that linked property lists are faster (but not that much) than integer arrays.

**Comment by lvjr** [comment]
But I didn't turn on `\g__tblr_use_linked_prop_bool` in above commits, because the following tests failed:
```
library-014, library-016, library-017, table-002, table-003
```

**Comment by muzimuzhi** [comment]
> Now intarrays are deprecated with latest `l3kernel`.

The latest `l3kernel` or `tabularray`?

**Comment by lvjr** [comment]
Deprecated when both are latest.

**Comment by lvjr** [comment]
Deprecated when both of them are latest.

**Comment by lvjr** [comment]
In above commit, I enabled mapping from spec to prop. Now the running speed is increased further:
```
flat prop - default

pdflatex average time   old = 4.9162483215332   new = 3.6152496337891   ratio = 0.73536758059072
xelatex average time    old = 4.9034996032715   new = 3.763744354248    ratio = 0.76756289563825
lualatex average time   old = 5.6615371704102   new = 4.3742446899414   ratio = 0.77262491762895

linked prop - data_to_prop

pdflatex average time   old = 4.8002471923828   new = 3.1875038146973   ratio = 0.66402909828379
xelatex average time    old = 4.9862480163574   new = 3.3210029602051   ratio = 0.6660324455002
lualatex average time   old = 5.6324348449707   new = 3.9444580078125   ratio = 0.70031134249774

linked prop - data_to_prop & spec_to_prop

pdflatex average time   old = 4.7674980163574   new = 2.9189949035645   ratio = 0.61226976782146
xelatex average time    old = 4.854248046875    new = 3.0415000915527   ratio = 0.62656462178746
lualatex average time   old = 5.6762504577637   new = 3.8069381713867   ratio = 0.67067832889223
```
<img width="769" alt="image" src="https://github.com/user-attachments/assets/0d777278-ec60-4171-a4cb-52208538bdd0" />

**Comment by lvjr** [comment]
Data structures based on token lists (which contains `\__tblr_spec_xxx` functions) in `tabularray` are deprecated and will be removed several years later.

**Comment by lvjr** [comment]
But test `library-017` for `tikz` library failed (the node of multispan cells shrink on the right). Need to fix it,

**Comment by lvjr** [comment]
> Possible to [get around it](https://github.com/muzimuzhi/tabularray-dev/blob/355b90dd3f1308787d5540de7865f3f980801327/zutil/zutil-debug.code.tex#L54-L69) in user-level code.

Thank you. Done.

**Comment by lvjr** [comment]
Ooh, it seems the benchmark test entered an infinite loop in texlive 2023. Let's try plan B: backporting `\prop_item:Nn` fix.

**Comment by lvjr** [comment]
Plan B works. Now the running time decreases in TeX Live 2023 too.

<img width="760" alt="image" src="https://github.com/user-attachments/assets/f82399e9-b561-45a3-90ae-1ba57d4d66a4" />
