### ISSUE TITLE
Clean up key tree

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#547]
We can clean up key tree, putting all keys under `tabularray` module:

```
tabularray/package/option (new)
tabularray/table/inner (from tblr)
tabularray/table/delimiter (from tblr-delimiter)
tabularray/table/outer (from tblr-outer)
tabularray/template/element (from tblr-element)
tabularray/template/style (from tblr-style)
tabularray/template/def (from tblr-def-template)
tabularray/template/set (from tblr-set-template)
tabularray/tracing/set (from tblr-set-tracing)
tabularray/tracing/log (from tblr-log-tracing)
tabularray/column/inner (from tblr-column)
tabularray/row/inner (from tblr-row)
tabularray/cell/inner (from tblr-cell-spec)
tabularray/cell/outer (from tblr-cell-span) (we may set cell borders with keys under it)
tabularray/hline/inner (from tblr-hline)
tabularray/vline/inner (from tblr-vline)
tabularray/hborder/inner (from tblr-hborder)
tabularray/vborder/inner (from tblr-vborder)
```

**Comment by muzimuzhi** [comment]
Coincides with 69de316 (refactor: sub-divide l3keys modules, 2024-03-12), except `tblr/__<submodule>` was used there to avoid naming conflicts (for example, when in the future there are user interfaces to define new ounter/inner (meta) options).

**Comment by lvjr** [comment]
My plan is to make these paths as (experimental) public interfaces, so `_` or `@` is not a good choice. Might have a look at other packages first.

**Comment by lvjr** [comment]
> ... except `tblr/__<submodule>` was used there to avoid naming conflicts (for example, when in the future there are user interfaces to define new ounter/inner (meta) options).

We can avoid this by using `\keys_if_exist` function.

But still users can overwrite existing keys with `\keys_define`. So it may be a bad idea to make key paths public.

**Comment by lvjr** [comment]
I really could not enjoy ugly `_` or `@` characters in tree paths, so I will keep them public, warn in the manual that they are experimental interefaces, and trust users not to break their own documents.

I will add a new chapter "Experimental Interfaces" in the manual, which describes tree paths, hook paths and public variables (see #197).

PS: I think it is useful to add `\keys_new:nn` in `l3keys` (also `\NewKeys` in `ltkeys`).

**Comment by lvjr** [comment]
Furthermore, `ltkeys` was added in 2022-06-01 release of LaTeX2e, so we could safely use `\ProcessKeyOptions` in next release.  We can put all keys for package options under tree path `tblr/option`.

Yes, there are no package options in `tabularray` at present, but still we could allow some brave users to add their own options before loading `tabularray`. (I guess it will work.)

**Comment by muzimuzhi** [comment]
> I really could not enjoy ugly `_` or `@` characters in tree paths

No problem. My previous comment https://github.com/lvjr/tabularray/issues/547#issuecomment-2524742835 was just a FYI, and does not constitute any suggestion.

**Comment by lvjr** [comment]
Now that the key paths are long, we can create two new helper commands `\DeclareTblrKeys` and `\SetTblrKeys`.
