### ISSUE TITLE
Add cell nodes and table nodes with TikZ

### ISSUE THREAD

**Issue by xrf786** [lvjr/tabularray#552]
I recently encountered [this question](https://tex.stackexchange.com/q/732475/318574) about adding markers, and it made me realize that there was no easy way of adding markers with the tabularray package as of yet. After talking with some people who have way more knowledge of LaTeX than I, Jasper came up with [this detailed solution](https://tex.stackexchange.com/a/732641/318574) using the tabularray package. I was wondering if you could integrate a macro for this purpose into the package, perhaps optimizing and refining Jasper's example code?

**Comment by jasperhabicht** [comment]
This is likely a sub-issue of https://github.com/lvjr/tabularray/issues/29 . Still, a nice suggestion!

**Comment by lvjr** [comment]
It may be a good idea to provide an experimental corner hook to users before we implement `pgf` library for `tabularray` in the future.
```latex
\AddToHook{tabularray/coordinate/corner}{%
  // create tikz coordinate node "hv-i-j" with rownum and colnum counters
}
\AddToHookNext{env/tblr/after}{%
  \begin{tikzpicture}[remember picture, overlay]
    \fill [red] (hv-i-j) circle (1mm) ; 
  \end{tikzpicture}%
}
```
No time for this hook at present. But I have created a new `pgf` branch, so you can make a pull request to this branch if you would like to help.

**Comment by lvjr** [comment]
I guess the hook can be added somewhere in the code for building hline or vline segments.

**Comment by jasperhabicht** [comment]
The question would be: should there just be a coordinate at the lower left of each cell or should there be a (phantom) node that covers the whole cell? The latter would make it easier to access all four corners, but it would probably more complicated to add. 

In the end, if another set of coordinates is placed above the first row and after the last column, every cell intersection would as well be reachable.

**Comment by lvjr** [comment]
> The question would be: should there just be a coordinate at the lower left of each cell or should there be a (phantom) node that covers the whole cell? The latter would make it easier to access all four corners, but it would probably more complicated to add.
> 
> In the end, if another set of coordinates is placed above the first row and after the last column, every cell intersection would as well be reachable.
> 
> But also, starting from the lower left corner, it is at least possible to reach the other corners when knowing the size of the cell box (which is known). So, for starters just a hook at the lower left corner should be sufficient.

In fact, `nicematrix` provides both cell nodes and corner nodes (see https://github.com/lvjr/tabularray/issues/29#issuecomment-1382648663). In this sub-issue we may focus on corner nodes only, avoiding touching table cells. (`tabularray` typesets each cell several times, so I guess it is more complicated to add hooks in it.)

If a table has m×n corners, it is enough to create only coordinate nodes at corners (1,1), (1,2), ..., (1,n), (2,1), ... ,(m,1), and get coordinate nodes of other corners with intersection syntax (`-|` and `|-`) of tikz.

**Comment by jasperhabicht** [comment]
One idea would be to just make use of the existing hook `tabularray/cell/before`. I am unsure where exactly to place the corner hook, but I would think that it would need some shift anyways, so maybe it would also be okay just to use the hook at the beginning at the cell. A `tikzmark` library could then look like follows:

```tex
\NewTblrLibrary { tikzmark }
  {
    \UseTblrLibrary { hook }
    \RequirePackage { tikz }
    \usetikzlibrary { tikzmark }
    \AddToHook { tabularray/cell/before } {
        \hbox_set:Nn \l_tmpa_box { 
          \tikzmark{cell-\arabic{colnum}-\arabic{rownum}} 
        }
        \box_set_trim:Nnnnn \l_tmpa_box 
            { 0.5\rulewidth }
            { 0.5\rulewidth }
            { -0.5\rulewidth }
            { -0.5\rulewidth }
        \box_move_down:nn { \dim_eval:n { \l__tblr_row_dp_dim } }
            { \box_use:N \l_tmpa_box }
    }
  }
```

Full MWE:

```tex
\documentclass{article}
\usepackage{tabularray}

\ExplSyntaxOn

\NewTblrLibrary { tikzmark }
  {
    \UseTblrLibrary { hook }
    \RequirePackage { tikz }
    \usetikzlibrary { tikzmark }
    \AddToHook { tabularray/cell/before } {
        \hbox_set:Nn \l_tmpa_box { 
          \tikzmark{cell-\arabic{colnum}-\arabic{rownum}} 
        }
        \box_set_trim:Nnnnn \l_tmpa_box 
            { 0.5\rulewidth }
            { 0.5\rulewidth }
            { -0.5\rulewidth }
            { -0.5\rulewidth }
        \box_move_down:nn { \dim_eval:n { \l__tblr_row_dp_dim } }
            { \box_use:N \l_tmpa_box }
    }
  }

\ExplSyntaxOff

\UseTblrLibrary{tikzmark}

\begin{document}
\begin{tblr}{
    hlines, vlines, 
    colspec={ l l l }
}
    1 & 2 & 3 \\
    4 & 5 & 6 
\end{tblr}

\begin{tikzpicture}[remember picture, overlay]
    \draw[red] (pic cs:cell-3-2) circle[radius=1pt];
    \draw[blue] (pic cs:cell-1-1) -| (pic cs:cell-2-2);
\end{tikzpicture}
\end{document}
```

![image](https://github.com/user-attachments/assets/f5d46df0-246f-44d3-890d-61872952d3ea)

**Comment by lvjr** [comment]
Great progress. Maybe we need to consider  the case when widths of hline and vline are different, and the case when there are multiple hlines or vlines at the corner.

**Comment by lvjr** [comment]
We can still call them corner marks even if we use cell hooks. But corners at the first hline and the last vline are still missing. For the first hline, we have `\l__tblr_row_ht_dim`. And for the last vline, Maybe we need to use `cell/after` hook.

BTW, why `colnum` is before `rownum` in the node name?

**Comment by lvjr** [comment]
Also we can just call the key `name` instead of `tikzmark prefix`, we will need it in other situations. Since a table can have subtables, we can not just store the `name` value to a local variable.

**Comment by jasperhabicht** [comment]
> We can still call them corner marks even if we use cell hooks. But corners at the first hline and the last vline are still missing. For the first hline, we have `\l__tblr_row_ht_dim`. And for the last vline, Maybe we need to use `cell/after` hook.
> 
> 
> 
> BTW, why is `colnum` before `rownum` in the node name?

After thinking about this again, I would think that we should not name the lower left corner of the first cell `-1-1`, but either the upper left corner or the lower right corner. The reason is that otherwise we have no symmetry with row and column numbering. I would prefer to name the upper left corner of the whole table `-0-0`.

Sure, we can (and probably should) first use the rownum in the coordinate name.

**Comment by jasperhabicht** [comment]
Improved version which adds another set of tikzmarks for the first row and the first column, `-0-0` being the upper left corner and `-1-1` the lower right corner of the first cell:

```tex
\tl_new:N \l__tblr_tikzmark_prefix_tl
\box_new:N \l__tblr_tikzmark_box

\NewTblrLibrary { tikzmark }
  {
    %\keys_define:nn { tblr }
    \__tblr_keys_define:nn { table / inner }
        { 
            tikzmark ~ prefix .code:n = {
                \tl_set:Nn \l__tblr_tikzmark_prefix_tl { ##1 - } 
            } 
        }
    \UseTblrLibrary { hook }
    \RequirePackage { tikz }
    \usetikzlibrary { tikzmark }
    \AddToHook { tabularray/cell/before } {
        \int_compare:nNnT { \arabic{rownum} } = { 1 } {
            \int_compare:nNnT { \arabic{rownum} } = { 1 } {
                \hbox_set:Nn \l__tblr_tikzmark_box { 
                  \tikzmark{ \l__tblr_tikzmark_prefix_tl tblr - 
                    \int_eval:n { \arabic{rownum} - 1 } -
                    \int_eval:n { \arabic{colnum} - 1 }
                  } 
                }
                \box_set_trim:Nnnnn \l__tblr_tikzmark_box 
                    { 0.5\rulewidth }
                    { -0.5\rulewidth }
                    { -0.5\rulewidth }
                    { 0.5\rulewidth }
                \box_move_up:nn { \dim_eval:n { \l__tblr_row_ht_dim } }
                    { \box_use:N \l__tblr_tikzmark_box }
            }
            \hbox_set:Nn \l__tblr_tikzmark_box { 
              \tikzmark{ \l__tblr_tikzmark_prefix_tl tblr - 
                \arabic{rownum} - 
                \int_eval:n { \arabic{colnum} - 1 }
              } 
            }
            \box_set_trim:Nnnnn \l__tblr_tikzmark_box 
                { 0.5\rulewidth }
                { 0.5\rulewidth }
                { -0.5\rulewidth }
                { -0.5\rulewidth }
            \box_move_down:nn { \dim_eval:n { \l__tblr_row_dp_dim } }
                { \box_use:N \l__tblr_tikzmark_box }
        }
    }
    \AddToHook { tabularray/cell/after } {
        \int_compare:nNnT { \arabic{rownum} } = { 1 } {
            \hbox_set:Nn \l__tblr_tikzmark_box { 
              \tikzmark{ \l__tblr_tikzmark_prefix_tl tblr - 
                \int_eval:n { \arabic{rownum} - 1 } -
                \int_eval:n { \arabic{colnum} }
              } 
            }
            \box_set_trim:Nnnnn \l__tblr_tikzmark_box 
                { -0.5\rulewidth }
                { -0.5\rulewidth }
                { 0.5\rulewidth }
                { 0.5\rulewidth }
            \box_move_up:nn { \dim_eval:n { \l__tblr_row_ht_dim } }
                { \box_use:N \l__tblr_tikzmark_box }
        }
        \hbox_set:Nn \l__tblr_tikzmark_box { 
          \tikzmark{ \l__tblr_tikzmark_prefix_tl tblr - 
            \arabic{rownum} - 
            \arabic{colnum}
          } 
        }
        \box_set_trim:Nnnnn \l__tblr_tikzmark_box 
            { -0.5\rulewidth }
            { 0.5\rulewidth }
            { 0.5\rulewidth }
            { -0.5\rulewidth }
        \box_move_down:nn { \dim_eval:n { \l__tblr_row_dp_dim } }
            { \box_use:N \l__tblr_tikzmark_box }
    }
  }
```

I am unsure how to proceed with the `name` key. Next step would be to look at variable thickness and number of borders.

**Comment by lvjr** [comment]
> I am unsure how to proceed with the `name` key. 

That is not that important. I can do it at the end.

**Comment by jasperhabicht** [comment]
Another, maybe better approach would be not to use coordinates, but just place (phantom) nodes over the cells that have the same size as the cells. This way, one could refer to the corners of each cell using the Ti*k*Z anchors `north east`, `south west` etc.

The benefit of this approach is that we don't need to calculate the coordinates in cases where there are two or more `hlines` or `vlines`. The node is just as large as the cell. I would actually prefer this solution over the other: 

```tex 
\tl_new:N \l__tblr_tikzmark_prefix_tl
\dim_new:N \l__tblr_cell_inner_wd_dim
\dim_new:N \l__tblr_cell_hcenter_dim
\dim_new:N \l__tblr_cell_vcenter_dim
\box_new:N \l__tblr_tikzmark_box

\NewTblrLibrary { tikzmark } % maybe really name this library `pgf`?
  {
    \keys_define:nn { tblr }
    %\__tblr_keys_define:nn { table / inner }
        { 
            tikzmark ~ prefix .code:n = {
                \tl_set:Nn \l__tblr_tikzmark_prefix_tl { ##1 - } 
            } 
        }
    \UseTblrLibrary { hook }
    \RequirePackage { tikz }
    \usetikzlibrary { tikzmark }
    \AddToHook { tabularray/cell/after } {
        \dim_set:Nn \l__tblr_cell_inner_wd_dim { 
            \l__tblr_x_tl + \l__tblr_y_tl + 
            \l__tblr_cell_wd_dim
        }
        \hbox_set:Nn \l__tblr_tikzmark_box { 
          \begin{tikzpicture}[remember ~ picture, overlay]
              \node[
                rectangle ,
                inner ~ sep = 0pt ,
                draw = none ,
                fill = none , 
                text ~ width = \l__tblr_cell_inner_wd_dim ,
                text ~ height = \l__tblr_row_ht_dim , 
                text ~ depth = \l__tblr_row_dp_dim 
              ] (
                \l__tblr_tikzmark_prefix_tl 
                tblr - 
                \int_use:N \c@rownum - 
                \int_use:N \c@colnum
              ) at (0,0) {}; 
          \end{tikzpicture}
        }
        \dim_set:Nn \l__tblr_cell_hcenter_dim { 
            0.5 \l__tblr_cell_inner_wd_dim 
        }
        \dim_set:Nn \l__tblr_cell_vcenter_dim {
            0.5 \l__tblr_row_dp_dim -
            0.5 \l__tblr_row_ht_dim 
        }
        \box_set_trim:Nnnnn \l__tblr_tikzmark_box  
            { \l__tblr_cell_hcenter_dim }
            { \l__tblr_cell_vcenter_dim }
            { -\l__tblr_cell_hcenter_dim } 
            { -\l__tblr_cell_vcenter_dim }
        \box_use:N \l__tblr_tikzmark_box
    }
  }
```

Full MWE: 

```tex
\documentclass{article}
\usepackage{tabularray}

\UseTblrLibrary{tikzmark}

\begin{document}
\begin{tblr}{
    hlines, vlines, 
    colspec={ l l l },
    tikzmark prefix={a},
    hline{1} = {1}{2pt},
    vline{1} = {1}{2pt},
    vline{2} = {2}{-}{1pt}
}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    7 & 8 & 9 
\end{tblr}

\begin{tikzpicture}[remember picture, overlay]
    \draw[green] (a-tblr-1-1.north west) circle[radius=1pt];
    \draw[green] (a-tblr-1-1.north east) circle[radius=1pt];
    \draw[green] (a-tblr-1-1.south west) circle[radius=1pt];
    \draw[green] (a-tblr-1-1.south east) circle[radius=1pt];

    \draw[red] (a-tblr-1-2.north west) circle[radius=1pt];
    \draw[red] (a-tblr-1-2.north east) circle[radius=1pt];
    \draw[red] (a-tblr-1-2.south west) circle[radius=1pt];
    \draw[red] (a-tblr-1-2.south east) circle[radius=1pt];

    \draw[blue] (a-tblr-3-1.north west) circle[radius=1pt];
    \draw[blue] (a-tblr-3-1.north east) circle[radius=1pt];
    \draw[blue] (a-tblr-3-1.south west) circle[radius=1pt];
    \draw[blue] (a-tblr-3-1.south east) circle[radius=1pt];
\end{tikzpicture}
\end{document}
```

![image](https://github.com/user-attachments/assets/6f9fa300-0eb9-4c2a-8539-3331caf694ba)

**Comment by lvjr** [comment]
It's definitely a better approach. If you could port the code to `pgf`, it would be called `pgf` library instead of `tikz` library.

**Comment by lvjr** [comment]
Now that we have all cell nodes, maybe we can add a hook to `tabularray/table/after`, using them to make corner nodes which are not at the border of the whole table. But these outermost corner nodes might be made if we use also row boxes and the table box similarly. There is a table box for a short table, and we need not to consider long tables at this time.

**Comment by lvjr** [comment]
> If you could port the code to `pgf`, it would be called `pgf` library instead of `tikz` library.

Not need to do this. I think `tikz` library is just fine.

**Comment by lvjr** [comment]
We can also create a helper environment `tblrtikz` adding `name prefix` key of tikz:
```tex
\NewDocumentEnvironment{tblrtikz}{O{}}{
  \begin{tikzpicture}[name prefix=<the name value in previous table>, #1]
}{
  \end{tikzpicture}
}
```

**Comment by lvjr** [comment]
We can also create a helper environment `tblrtikz` adding `name prefix` key of tikz:
```tex
\NewDocumentEnvironment{tblrtikz}{O{}}{
  \begin{tikzpicture}[name prefix=<the name value in previous table>, #1]
}{
  \end{tikzpicture}
}
```
Then it is easily to do drawing on tblr tables.

**Comment by lvjr** [comment]
Furthermore we can add a global integer for counting all `tblr` tables. Then every `tblr` table has a unique name such as `tblr1234`. In this way users don't need to specify `name` key most of the time.

```tex
\begin{tblr}{hlines, vlines} % it has a default `name = tblr1234`
   1 & 2 & 3 \\
   4 & 5 & 6 \\
   7 & 8 & 9 
\end{tblr}
\begin{tblrtikz} % `remember picture, overlay, name prefix = tblr1234` has been specified
  \draw (i-j) circle[radius=1pt]; % for cell node
  \draw (c-i-j) circle[radius=1pt]; % for corner-node
\end{tblrtikz}
```

**Comment by muzimuzhi** [comment]
> We can also create a helper environment `tblrtikz` adding `name prefix` key (and `remember picture, overlay`) of tikz:
> 
> ```
> \NewDocumentEnvironment{tblrtikz}{O{}}{
>   \begin{tikzpicture}[remember picture, overlay, name prefix=<the name value in previous table>, #1]
> }{
>   \end{tikzpicture}
> }
> ```
> 
> Then it is easier to do drawing on `tblr` tables.

Note that document environments (`ltcmd` envs) with non-`m` argument(s) are relatively slow.

**Comment by jasperhabicht** [comment]
> Now that we have all cell nodes, maybe we can add a hook to `tabularray/table/after`, using them to make corner nodes which are not at the border of the whole table. But these outermost corner nodes might be made if we use also row boxes and the table box similarly. There is a table box for a short table, and we need not to consider long tables at this time.

As for long labels, the draw commands need to be on the same page. But one could place them in the footer of a long table part of the relevant page ... but yes, this is something for later.

**Comment by jasperhabicht** [comment]
> > We can also create a helper environment `tblrtikz` adding `name prefix` key (and `remember picture, overlay`) of tikz:
> 
> > 
> 
> > ```
> 
> > \NewDocumentEnvironment{tblrtikz}{O{}}{
> 
> >   \begin{tikzpicture}[remember picture, overlay, name prefix=<the name value in previous table>, #1]
> 
> > }{
> 
> >   \end{tikzpicture}
> 
> > }
> 
> > ```
> 
> > 
> 
> > Then it is easier to do drawing on `tblr` tables.
> 
> 
> 
> Note that document environments (`ltcmd` envs) with non-`m` argument(s) are relatively slow.

We can make use of regular Ti*k*Z keys which are than taken into account here instead of giving an optional parameter.

**Comment by lvjr** [comment]
> > > We can also create a helper environment `tblrtikz` adding `name prefix` key (and `remember picture, overlay`) of tikz:
> > > \NewDocumentEnvironment{tblrtikz}{O{}}{
> > >   \begin{tikzpicture}[remember picture, overlay, name prefix=, #1]
> > > }{
> > >   \end{tikzpicture}
> > > }
> > > Then it is easier to do drawing on `tblr` tables.
> > 
> > Note that document environments (`ltcmd` envs) with non-`m` argument(s) are relatively slow.
> 
> We can make use of regular Ti_k_Z keys which are than taken into account here instead of giving an optional parameter.

Not need to worry it at this time. I guess it is faster than drawing a tikz path.

**Comment by lvjr** [comment]
>\hbox_set:Nn \l__tblr_tikzmark_box { 
>  \begin{tikzpicture}[remember ~ picture, overlay]
>      \node[
>        rectangle ,
>        inner ~ sep = 0pt ,
>        draw = none ,
>        fill = none , 
>        text ~ width = \l__tblr_cell_inner_wd_dim ,
>        text ~ height = \l__tblr_row_ht_dim , 
>        text ~ depth = \l__tblr_row_dp_dim 
>      ] (
>        \l__tblr_tikzmark_prefix_tl 
>        tblr - 
>        \int_use:N \c@rownum - 
>        \int_use:N \c@colnum
>      ) at (0,0) {}; 
>  \end{tikzpicture}
>}

Another idea came to my mind: should we set `inner sep` to the values of `\leftsep`/`\rightsep`/`\abovesep`/`\belowsep`? Or shrink the box and set
`outer sep` to those dimensions?

Actually `nicematrix` provides both `i-j-large` and `i-j-medium` cell nodes. I'm not sure what `tabularray` should do. I seldom do drawing on tables in my LaTeX documents.

**Comment by jasperhabicht** [comment]
> Now that we have all cell nodes, maybe we can add a hook to `tabularray/table/after`, using them to make corner nodes which are not at the border of the whole table. But these outermost corner nodes might be made if we use also row boxes and the table box similarly. There is a table box for a short table, and we need not to consider long tables at this time.

I need some help with this one, because I don't fully understand from the code how the height and depth of the table box is set. I need these two parameters at the hook somehow. But the problem seems that due to scoping, there is no direct way to access the table box at the hook `tabularray/table/after`. Some ideas?

**Comment by lvjr** [comment]
We can add some private hooks for it, since it is a builtin library. Can this solve the problem?

**Comment by lvjr** [comment]
We can add some private hooks for it, since it is a builtin library. Can this solve the problem?

**Comment by lvjr** [comment]
We can add some private hooks for it, since it is a builtin library. Can this solve the problem?

**Comment by jasperhabicht** [comment]
I got it working by placing the "super-node" for the whole table in the last cell and shifting it. Updated code, see PR.

The coordinates don't work yet for multicolumn/multirow cells. I have to look into this.

**Comment by lvjr** [comment]
You are right, we don't need row boxes to get positions of all outermost corners - using the table box is enough.

**Comment by lvjr** [comment]
Today I tried to draw a fancy background for a table by putting `tblrtikz` before `tblr` and setting correct `name prefix`. But it caused an error of unknown shape name, even if it produced correct result. I may consider this feature after the PR.

**Comment by jasperhabicht** [comment]
> Today I tried to draw a fancy background for a table by putting `tblrtikz` before `tblr` and setting correct `name prefix`. But it caused an error of unknown shape name, even if it produced correct result. I may consider this feature again after the PR.

This is because the `tblr` sets the `name prefix`, so the value is only available afterwards. But right, we should consider this as well.

**Comment by lvjr** [comment]
> This is probably because the `tblr` sets the `name prefix`, so the value is only available afterwards. Ti_k_Z has no problem with that, because it does multiple runs anyways (at least this is what I think the reason is that the output was still right). But right, we should consider this as well.
> 
> Currently, the idea is that the `tblrtikz` environment automatically uses the `name prefix` set by the previous `tblr` environment. This might not be the best approach.
 
Probably we need to add another `tblrtikzbefore` environment and rename `tblrtikz` as `tblrtikzafter` later.

**Comment by lvjr** [comment]
BTW, do you have more examples for this library? I want to add them to manual and test files.

**Comment by jasperhabicht** [comment]
> > I now got the code working for multicolumn/multirow cells and also made use of some existing functions in the code to avoid code reduplication. Finally, I reformatted the code to adhere to the proper syntax.
> 
> Then can I merge the PR (and make some small adjustments) now?

Yes, sure. It should be ready for merging. The only open question is how to exactly implement the `name prefix` which can be done later, I think.

As for examples, I used the following for testing, but it is far from a real-life example I gues:
 
```tex
\documentclass{article}
\usepackage{tabularray}

\UseTblrLibrary{tikz}

\begin{document}
x \begin{tblr}{
    hlines, vlines, 
    colspec={ l l l l },
    tikz prefix={a},
    hline{1} = {2pt},
    vline{1} = {1}{2pt},
    vline{2} = {2}{-}{1pt},
    hline{Z} = {2pt},
    cell{2}{2} = {r=2, c=2}{c}
}
    1 & 2 & 3 & 5 \\
    4 & foo bar baz & 6 \\
    7 & 8 & 9 & 10 
\end{tblr} x

\begin{tblrtikz}
    \draw[green] (tblr-1-1.north west) circle[radius=1pt];
    \draw[green] (tblr-1-1.north east) circle[radius=1pt];
    \draw[green] (tblr-1-1.south west) circle[radius=1pt];
    \draw[green] (tblr-1-1.south east) circle[radius=1pt];

    \draw[red] (tblr-2-2.north west) circle[radius=1pt];
    \draw[red] (tblr-2-2.north east) circle[radius=1pt];
    \draw[red] (tblr-2-2.south west) circle[radius=1pt];
    \draw[red] (tblr-2-2.south east) circle[radius=1pt];

    \draw[blue] (tblr-3-1.north west) circle[radius=1pt];
    \draw[blue] (tblr-3-1.north east) circle[radius=1pt];
    \draw[blue] (tblr-3-1.south west) circle[radius=1pt];
    \draw[blue] (tblr-3-1.south east) circle[radius=1pt];

    \draw[yellow] (tblr.north west) circle[radius=1pt];
    \draw[yellow] (tblr.north east) circle[radius=1pt];
    \draw[yellow] (tblr.south west) circle[radius=1pt];
    \draw[yellow] (tblr.south east) circle[radius=1pt];
\end{tblrtikz}
\end{document}
```

![image](https://github.com/user-attachments/assets/6f827a27-b184-43b4-8ea4-10988659391c)

**Comment by lvjr** [comment]
Thank you for your contribution! Merged. Further improvements can be discussed in issue #29 .
