### ISSUE TITLE
Replace x-type expansions with e-type expansions

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#560]
See https://www.texdev.net/2023/10/10/get-the-jag-from-x-type-to-e-type .

Note that TeX Live 2022 doesn't have e-type variants of many functions, so we need to create them.

**Comment by muzimuzhi** [comment]
I made the exact change in my fork before but didn't submit it for fear of rejection. Now it will probably fail to merge due to conflicts...

39d3756 (refactor: convert x- to e-type expansion, 2024-03-12)

**Comment by lvjr** [comment]
Sorry for being slow to accept new changes. I think now the policies are basically clear and precise (support three old texlive releases; only make noticeable breaking changes every several year).

It would be a better approach to create an issue for discussion before making a pull request. I can not promise quick responses to all issues, but I will eventually deal with each of them.

**Comment by lvjr** [comment]
> I made the exact change in my fork before but didn't submit it for fear of rejection. Now it will probably fail to merge due to conflicts...
> 
> [39d3756](https://github.com/lvjr/tabularray/commit/39d37568bfb5e51355952ca58474d9849ae75408) (refactor: convert x- to e-type expansion, 2024-03-12)

Thank you! I have added your change and merged it to main branch.

**Comment by lvjr** [comment]
It seems from benchmark charts that there is no significant improvement with this change. (I am not against the thange. Just record the result here.)
