### ISSUE TITLE
Permit the use of different list for different theme

### ISSUE THREAD

**Issue by sadao-massago** [lvjr/tabularray#567]
Is nice, if permit to use different listing file (other than "lot") using specific theme.
For example, specific theme will listed in the file different of "lot" used by rest of tables.
The attached code does not compile because trying to set "caption-lot" inside theme using

    \SetTblrTemplate{ caption-lot }{ quadro }

raise error:

    Use of \??? doesn't match its definition.
    <argument> \???
    ! LaTeX Error: Erroneous variable \l__tblr_template_caption-lot_default_t

The testing code:

    \documentclass[12pt,oneside]{book}
    
    \usepackage{float}
    \usepackage{tabularray}
    \UseTblrLibrary{booktabs}
    
    % quadros
    %--------
    \newcommand{\quadroname}{Quadro}
    \newcommand{\listofquadrosname}{Lista de quadros}
    \newfloat{quadro}{tbp}{loq}%[chapter]
    \floatname{quadro}{Quadro}
    %\counterwithout{quadro}{chapter}
    \newcommand{\listadequadros}{\listof{quadro}{\listofquadrosname}}
    
    \ExplSyntaxOn
    \DefTblrTemplate { caption-lot } { quadro }
    {
      \addtocounter{table}{-1} % don't count as table
      \stepcounter{quadro}% count as "quadro"
      \tl_if_empty:NTF \lTblrEntryTl
        { \tl_set_eq:NN \l__tblr_caption_short_tl \lTblrCaptionTl }
        { \tl_set_eq:NN \l__tblr_caption_short_tl \lTblrEntryTl }
      %\addcontentsline { lot } { table }
      %  { \protect\numberline { \thetable } { \l__tblr_caption_short_tl } }
      \addcontentsline { loq } { quadro }
        { \protect\numberline { \thequadro } { \l__tblr_caption_short_tl } }
    }
    \ExplSyntaxOff
    
    \DefTblrTemplate { caption-tag } { quadro } { \quadroname\hspace{0.25em}\thequadro }
    
    \NewTblrTheme{quadro}{
      \SetTblrTemplate{ caption-tag } { quadro }
      \SetTblrTemplate{ caption-lot }{ quadro }% it raise error when use theme:
      % Use of \??? doesn't match its definition.
      % <argument> \???
      %! LaTeX Error: Erroneous variable \l__tblr_template_caption-lot_default_t
      % 
    }
    
    \begin{document}
    
    \listadequadros
    
    \listoftables
    
    \chapter{First chapter}
    
    Table (that contents is numerical data)
    \begin{longtblr}
    [
      caption={Long table},
      label={tab:longo},
    ]
    {
      colspec = {XX},
    }
    linha 1 & 1 \\
    linha 2 & 2 \\
    linha 3 & 3 \\
    linha 4 & 4 \\
    linha 5 & 5 \\
    linha 6 & 6 \\
    linha 7 & 7 \\
    linha 8 & 8 \\
    linha 9 & 9 \\
    linha 10 & 10 \\ 
    \end{longtblr}
    
    Quadro (table that contents is text)
    \begin{longtblr}
    [
      theme=quadro,
      caption={Test of ``quadro''},
      label={quadro:longo},
    ]
    {
      colspec = {XX},
      vlines,hlines,
    }
    linha 1 & coluna 2 \\
    linha 2 & coluna 2 \\
    linha 3 & coluna 2 \\
    linha 4 & coluna 2 \\
    linha 5 & coluna 2 \\
    linha 6 & coluna 2 \\
    linha 7 & coluna 2 \\
    linha 8 & coluna 2 \\
    linha 9 & coluna 2 \\
    linha 10 & coluna 2 \\ 
    \end{longtblr}
    
    \end{document}

**Comment by lvjr** [comment]
You need to remove superfluous spaces:
```tex
\DefTblrTemplate{caption-tag}{quadro}{\quadroname\hspace{0.25em}\thequadro}

\NewTblrTheme{quadro}{
  \SetTblrTemplate{caption-tag}{quadro}
  \SetTblrTemplate{caption-lot}{quadro}
}
```

**Comment by sadao-massago** [comment]
Thanks. Now, working.
