### ISSUE TITLE
Once you have set a cmd for a column, there is no way to disable it for a single row

### ISSUE THREAD

**Issue by callegar** [lvjr/tabularray#57]
Suppose that you have a table where column 3 should be made of images. So you set `cmd=\includegraphids` for `column{3}`, so that you only have to type in the file name. Now, obviously, the table header(the 1st row) should have regular text in column 3. However there seems to be no way to get rid of the default command defined before. For instance `row{1}={cmd={}}` does not help.

**Comment by lvjr** [comment]
You can use `cell{2-Z}{3}={cmd=\includegraphids}`.

**Comment by callegar** [comment]
Thanks, this works!  May I suggest adding some documentation about the fact that cmds placed in colspecs cannot be reset and that if you need commands to be placed only in some rows, you need to do that explicitly?

**Comment by lvjr** [comment]
Maybe later I will make `cmd` option revisable, just as `fg` option (see #53).

**Comment by cdacl** [comment]
The same as `hlines` / `vlines`. When I described the `hlines` in mandatory arguments, I can't remove the hline between special rows. I only can use the `hline{i}` to draw lines on rows I wanted.

**Comment by lvjr** [comment]
@cdacl Please create a new issue for `hline/vline` option, since they are different from `cmd` option.

**Comment by lvjr** [comment]
Here is a bug due to the `cmd` option:

https://tex.stackexchange.com/questions/614686/situnitx-tabularray-sisetupmode-match-returns-an-error

We set `cmd=\TblrNum` first but a later `cmd=\TblrUnit` doesn't overwrite the former.
