### ISSUE TITLE
tabularray and shortverb |

### ISSUE THREAD

**Issue by u-fischer** [lvjr/tabularray#58]
The doc package (also also the fancyvrb package) allows to define `|`  as a short hand for the `\verb` command. 

This is used quite a lot e.g. in the LaTeX documentation.  

If the array package is used this doesn't disturb uses of ` | ` in tabular preambles, but tblr errors:

~~~~latex
\documentclass{article}
\usepackage{doc,array}
\usepackage{tabularray}
\begin{document}

\MakeShortVerb| %from doc package

|\section|

\begin{tabular}{|l} %works
abc\\
\end{tabular}


\begin{tblr}{|l} %errors
abc \\
\end{tblr}

\end{document}
~~~~

**Comment by lvjr** [comment]
Thanks for your reporting. I will see what I can do for these active characters later.
