### ISSUE TITLE
Previous 'bg' setting of cells can be replaced by later 'bg' setting, but 'fg' can't.

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#62]
### Discussed in https://github.com/lvjr/tabularray/discussions/53

<div type='discussions-op-text'>

<sup>Originally posted by **cdacl** August  4, 2021</sup>
The sample codes:

```
\begin{tblr}{hlines,vlines,
	cells	= {fg=white,black},
	cell{2}{2} = {fg=green3,blue3},
	}
	A & B \\
	C & D \\
\end{tblr}
```

The output:
![1](https://user-images.githubusercontent.com/87848848/128130720-9e5c85e0-9367-48b3-893a-34791eb92a75.png)

</div>

**Comment by lvjr** [comment]
### Discussed in https://github.com/lvjr/tabularray/discussions/56

<div type='discussions-op-text'>

<sup>Originally posted by **cdacl** August  6, 2021</sup>
The sample codes:

```
\begin{tblr}{hlines,vlines,
 cell{1}{1}={preto=A,appto=Z}
}
 o \\
\end{tblr}

\begin{tblr}{hlines,vlines,
 cell{1}{1}={preto=A,appto=Z,black,fg=white}
}
 o \\
\end{tblr}

\begin{tblr}{hlines,vlines,
 cell{1}{1}={fg=white,preto=A,appto=Z,black}
}
 o \\
\end{tblr}

```

The output:
![2](https://user-images.githubusercontent.com/87848848/128484177-fa3c431d-f25c-41fb-aaf8-26e83e483f53.png)
</div>

**Comment by lvjr** [comment]
@cdacl This bug has been fixed.

**Comment by cdacl** [comment]
Thank you very much!
