### ISSUE TITLE
Incorrect automatic page breaks in long table

### ISSUE THREAD

**Issue by callegar** [lvjr/tabularray#67]
This seems to be triggered by the use of multirow cells.  I see it with a case where I have
```
____________
|    |  D  |
| A  |  D  |
|    |  D  |
-----|  D  |
|    |  D  |
| B  |  D  |
|    |  D  |
|----|  D  |
|    |  D  |
| C  |  D  |
|    |  D  |
------------
```
where the `D` element is tall (and I am using `even` vspan, even if I do not know if this is relevant).

In this case, I see the table being built in such a way that it is too long for the page and the *continuation text* overlapping column `D`.

If needed I'll try to build a test case (unfortunately I cannot base it on my current document).

**Comment by lvjr** [comment]
Minimal working example is needed.  Is it related to #63?
