### ISSUE TITLE
Some lines disappeared around colored cells in Adobe Acrobat.

### ISSUE THREAD

**Issue by cdacl** [lvjr/tabularray#76]
The sample codes:

```
%! TeX TS-program = lualatex
\documentclass{article}
\usepackage{xcolor}
\usepackage{fontspec}
\setmainfont{Times new roman}
\usepackage{array}
\usepackage{tabularray}
\usepackage{nicematrix}
\begin{document}
tblr environment

\vspace{1ex}

\begin{tblr}{
 hlines,vlines,
 row{1} = {black!10},
}
 a & b\\
 c & d\\
\end{tblr}

\vspace{1cm}

NiceTabular environment

\vspace{1ex}

\begin{NiceTabular}{ll}[hvlines]
\CodeBefore
\rowcolor{black!10}{1}
\Body
 a & b \\
 c & d \\
\end{NiceTabular}
\end{document}
```

The  `nicematrix` package has solved this issue. The outputs of `tblr` environment and `NiceTabular` environment:
![1](https://user-images.githubusercontent.com/87848848/130016675-5294bc62-5af7-4c01-808a-12ca7e90ff47.png)

Acoording to the document of `nicematrix` package (P12):

> This is because many PDF viewers give priority to graphical
> element drawn posteriorly (which is in the spirit of the “painting model” of PostScript and
> PDF). Concerning this problem, MuPDF (which is used, for instance, by SumatraPDF)
> gives better results than Adobe Reader).

**Comment by lvjr** [comment]
Maybe it is bettet for `tabularray` to draw all cells first before drawing hlines/vlines.

**Comment by lvjr** [comment]
This bug has been fixed. Now all hlines and vlines appear in Adobe Reader.

![image](https://user-images.githubusercontent.com/4239949/130317174-db675ad4-f400-4f4e-8a79-c891e0c449fc.png)
