### ISSUE TITLE
longblr footnote without tag

### ISSUE THREAD

**Issue by mhabets** [lvjr/tabularray#78]
![image](https://user-images.githubusercontent.com/2016449/130155629-d7930438-f96d-43a5-92d2-4865edff394e.png)

Is there a way to produce a 3rd type of footnote which doesn't have any tag or space (=simple text as in the example highlighted above)?
`note{} = {text}` is not correctly left aligned because of an added space.

**Comment by lvjr** [comment]
There is a `more` option in `tabularray`, and you can use it like this:

````latex
\documentclass{article}

\usepackage{tabularray}
\DefTblrTemplate{lastfoot}{default}{
  \InsertTblrMore{term}\par
  \UseTblrTemplate{note}{default}
  \UseTblrTemplate{remark}{default}
}

\begin{document}

\noindent
\begin{talltblr}[
  caption = {Table Title},
  more{term} = {ND: not determined; *: $P<0.05$; **: $P<0.01$ (with some long long text).},  
  note{a} = {First Footnote.},
  note{b} = {Second Footnote.},
  remark{Source} = {Something noteworthy.},
]{hlines,colspec={XXXX}}
 Alpha   & Beta  & Gamma   & Delta \\
 Epsilon & Zeta  & Eta     & Theta \\
 Epsilon & Zeta  & Eta     & Theta \\
 Iota    & Kappa & Lambda  & Mu    \\
\end{talltblr}

\end{document} 
````

![image](https://user-images.githubusercontent.com/4239949/130162545-e4a27298-0eea-4b43-b7d3-5f401ea7349a.png)

**Comment by mhabets** [comment]
Wonderful! Thank you a lot.
Enhancement suggestion: `note` or `note*` with an empty tag (`note*{} = {text}`) should skip `note-sep`.

**Comment by lvjr** [comment]
You can add another `more{empty} = {text}` and use it like the above example.
