### ISSUE TITLE
Implementation of booktabs neglects different vertical spaces below and above rules

### ISSUE THREAD

**Issue by fredrikpaues** [lvjr/tabularray#79]
As far as I can see, the implementation of [`booktabs`](https://www.ctan.org/pkg/booktabs) in `tabulararray` neglects that `booktabs` does more than just diversifying the widths of the rules it introduces. `booktabs` also defines different vertical space above and below the new rules: `\belowrulesep=.65ex`, `\belowbottomrulesep=0pt`, `\aboverulesep=.4ex`, `\abovetoprulesep=0pt` and `\cmidrulesep=\doublerulesep`.

Would it be very hard to implement this in `tabularray`?

**Comment by lvjr** [comment]
Not hard. It will add them later.

**Comment by lvjr** [comment]
I have added a new `booktabs` environment which uses `\aboverulesep` and `\belowrulesep`, but with `rowsep=0pt`.

````latex
\documentclass{article}

\usepackage{tabularray}
\UseTblrLibrary{booktabs}

\begin{document}

\begin{tabular}{lll}
\toprule
 Alpha   & Beta  & Gamma   \\
\cmidrule(lr){1-2}
 Epsilon & Zeta  & Eta     \\
\midrule
 Iota    & Kappa & Lambda  \\
\cmidrule(lr){2-3}
 Nu      & Xi    & Omicron \\
\bottomrule
\end{tabular}
\quad
\begin{booktabs}{lll}
\toprule
 Alpha   & Beta  & Gamma   \\
\cmidrule[lr]{1-2}
 Epsilon & Zeta  & Eta     \\
\midrule
 Iota    & Kappa & Lambda  \\
\cmidrule[lr]{2-3}
 Nu      & Xi    & Omicron \\
\bottomrule
\end{booktabs}
\quad
\begin{tblr}{llll}
\toprule
 Alpha   & Beta  & Gamma   \\
\cmidrule[lr]{1-2}
 Epsilon & Zeta  & Eta     \\
\midrule
 Iota    & Kappa & Lambda  \\
\cmidrule[lr]{2-3}
 Nu      & Xi    & Omicron \\
\bottomrule
\end{tblr}

\end{document}
````
![image](https://user-images.githubusercontent.com/4239949/130460496-7ed9b658-d1b7-43aa-8a54-0af8127a2b7c.png)

**Comment by fredrikpaues** [comment]
Looks great! When can I expect to find it [over on CTAN](https://ctan.org/pkg/tabularray)?

**Comment by lvjr** [comment]
You may download the latest package file from
https://github.com/lvjr/tabularray/raw/main/tabularray.sty
or wait for version 2021N scheduled on September 1st.

**Comment by fredrikpaues** [comment]
Is it correct that we can't use remarks and notes in the new `booktabs` environment? If so, will it be possible in the near future?

**Comment by lvjr** [comment]
Add outer specification `tall` or `long` to `booktabs` environment:
```latex
\begin{booktabs}[tall]{lcr}
  ...
\end{booktabs}
```

**Comment by lvjr** [comment]
Maybe later I can provide `talltabs` and `longtabs` environments for them.
