### ISSUE TITLE
Do calculation in tables

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#81]
There are several package (`spreadtab`, `calctab`, `tabularcalc`) on doing calculation in tables. But it would be faster if 
 tabularray does calculation all by itself, because tabularray alreadly collects all cell text before building the whole table (see discussion #68).

As the first step, we need to design nice interfaces for table calculation. Here are some ideas of mine:

- Add a new key `text{i}{j}`. If we write `text{i}{j} = {Some Text}`, we do nothing but save or modify the cell text. But if the value starts with `@`, such as `text{i}{j} = @{Add{Cell{1}{2}}{Cell{4}{3}}}`, we do calculation by executing the functions inside.

- Each function has zero or more arguments, and each argument must be enclosed with braces. Nesting functions are executed from inner to outer.

- Obviously, we need some programming functions such as `If`, `For`, `IntCompare`, `FpCompare`, `IntEval`, `FpEval`. Try to map them to  existing `expl3` functions.

- It is very hard to write fully expandable function. Therefore a function may save its return value into `\result` macro.

- Also support putting calculation expressions directly in the table body.

**Comment by marvlg** [comment]
I don't know if calculation in tables within LaTeX is such a usefull feature. In my opinion, this should be done in Excel (or similar).

However, I think it would be very nice to have something like conditional formatting, e.g for cells with positive or negative values. More advanced features could be something like highlighting the biggest value of a row.

**Comment by lvjr** [comment]
Now that we have [functional](https://ctan.org/pkg/functional) package, it would be easier to provide `functional` library and do calculation based on this package:
```latex
\begin{tblr}{func=\SomeFunc}
1 & 2 & 3
\end{tblr}
```
Also conditional formatting is possible with this library.

**Comment by lvjr** [comment]
With the above commit, we can write the following code:
```latex
\documentclass{article}
\usepackage{tabularray}
\UseTblrLibrary{functional}
\IgnoreSpacesOn
\PrgNewFunction \SomeFunc {} {
  \IntStepInline { 1 } { 1 } { \arabic{colcount} } {
    \IntZero \lTmpaInt
    \IntStepInline { 1 } { 1 } { \arabic{rowcount} - 1 }
      {
        \IntAdd \lTmpaInt { \CellGetText {####1} {##1} }
      }
    \CellSetText {\Expand{\arabic{rowcount}}} {##1} {\IntUse\lTmpaInt}
  }
}
\IgnoreSpacesOff
\begin{document}
\begin{tblr}{colspec={rrr},func=\SomeFunc}
\hline
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9 \\
\hline
    &   &   \\
\hline
\end{tblr}
\end{document}
```
![image](https://user-images.githubusercontent.com/4239949/164195128-a732c485-b272-4c55-ab9c-45b40782d155.png)

**Comment by lvjr** [comment]
With the above commit, we can write the following code to color background of cells depending on its content:
```latex
\documentclass{article}
\usepackage{tabularray}
\usepackage{ninecolors}
\UseTblrLibrary{functional}
\IgnoreSpacesOn
\PrgNewFunction \SomeFunc {} {
  \IntStepInline {1} {1} {\arabic{rowcount}} {
    \IntStepInline {1} {1} {\arabic{colcount}} {
      \IntSet \lTmpaInt {\CellGetText {##1} {####1}}
      \IntCompareTF {\lTmpaInt} > {0}
        {\CellSetStyle {##1} {####1} {bg=purple8}}
        {\CellSetStyle {##1} {####1} {bg=olive8}}
    }
  }
}
\IgnoreSpacesOff
\begin{document}
\begin{tblr}{hlines,vlines,colspec={rrr},func=\SomeFunc}
  -1 &  2 &  3 \\
   4 &  5 & -6 \\
   7 & -8 &  9 \\
\end{tblr}
\end{document}
```
![image](https://user-images.githubusercontent.com/4239949/164229560-d4188d45-c597-48a3-a6e8-a1520da61336.png)

**Comment by lvjr** [comment]
With the above commit, we can write the following code to conditionally color background of rows:
```
\documentclass{article}
\usepackage{tabularray}
\usepackage{ninecolors}
\UseTblrLibrary{functional}
\IgnoreSpacesOn
\PrgNewFunction \SomeFunc {} {
  \IntStepInline {1} {1} {\arabic{rowcount}} {
    \IntCompareT {\IntMathMod {##1} {3}} = {0}
      {\RowSetStyle {##1} {bg=blue8}}
  }
}
\IgnoreSpacesOff
\begin{document}
\begin{tblr}{hlines,func=\SomeFunc}
  Row1 & 1 \\
  Row2 & 2 \\
  Row3 & 3 \\
  Row1 & 4 \\
  Row2 & 5 \\
  Row3 & 6 \\
\end{tblr}
\end{document}
```
<img width="337" alt="image" src="https://user-images.githubusercontent.com/4239949/164234821-feca9593-dc3c-420d-80bb-fb7e14352149.png">

**Comment by lvjr** [comment]
I have renamed inner specification `func` as `process`.

**Comment by lvjr** [comment]
With outer spec `evaluate`, we can evaluate every occurrence of a specified **protected** function (defined with `\PrgNewFunction`) and replace it with the return value before splitting the table:
```latex
\documentclass{article}
\usepackage{tabularray}
\UseTblrLibrary{functional}
\IgnoreSpacesOn
\PrgNewFunction \SomeFunc {m} {
  \Return {#1 & #1 \\}
}
\PrgNewFunction \OtherFunc {} {
  \Return {Other & Other \\}
}
\IgnoreSpacesOff
\begin{document}
\begin{tblr}[evaluate=\SomeFunc]{hlines}
  Row1 & 1 \\
  Row2 & 2 \\
  \SomeFunc{Text}
  Row3 & 3 \\
  Row4 & 4 \\
  \SomeFunc{Text}
  Row5 & 5 \\
  Row6 & 6 \\
\end{tblr}
\begin{tblr}[evaluate=\OtherFunc]{hlines}
  Row1 & 1 \\
  Row2 & 2 \\
  \OtherFunc
  Row3 & 3 \\
  Row4 & 4 \\
  \OtherFunc
  Row5 & 5 \\
  Row6 & 6 \\
\end{tblr}
\end{document}
```
<img width="397" alt="image" src="https://user-images.githubusercontent.com/4239949/164574722-0ace2dc4-14a2-4244-a81a-4a228ec0af03.png">

**Comment by lvjr** [comment]
With the latest `functional` package, it is possible to input files inside `tabularray` tables: 
```latex
\documentclass{article}
\usepackage{tabularray}
\UseTblrLibrary{functional}
\begin{filecontents*}[overwrite]{test1.tex}
Some & Some \\
\end{filecontents*}
\begin{filecontents*}[overwrite]{test2.tex}
Other & Other \\
\end{filecontents*}
\begin{document}
\begin{tblr}[evaluate=\FileInput]{hlines}
  Row1 & 1 \\
  Row2 & 2 \\
  \FileInput{test1}
  Row3 & 3 \\
  Row4 & 4 \\
  \FileInput{test2}
  Row5 & 5 \\
  Row6 & 6 \\
\end{tblr}
\end{document}
```
<img width="368" alt="image" src="https://user-images.githubusercontent.com/4239949/164583096-19362925-3136-4c9f-8fa1-84497b27fcac.png">

**Comment by lvjr** [comment]
Here is an example showing how to generate an empty table with `evaluate` option:

```
\documentclass{article}
\usepackage{tabularray}
\UseTblrLibrary{functional}
\IgnoreSpacesOn
\PrgNewFunction \MakeEmptyTable {mm}  {
  \TlSet \lTmpaTl {\IntReplicate {\IntEval{#2-1}} {&}}
  \TlPutRight \lTmpaTl {\\}
  \IntReplicate {#1} {\TlUse \lTmpaTl}
}
\IgnoreSpacesOff
\begin{document}
\begin{tblr}[evaluate=\MakeEmptyTable]{hlines,vlines}
  \MakeEmptyTable{3}{7}
\end{tblr}
\end{document}
```
<img width="237" alt="image" src="https://user-images.githubusercontent.com/4239949/165879304-dd776710-1706-4f05-897b-107be654bc02.png">
