### ISSUE TITLE
Lost lines in colored tables of long tables

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#88]
From https://tex.stackexchange.com/questions/612332/lost-lines-in-colored-tables-of-tabularray

````latex
\documentclass[12pt,a4paper]{article}

\usepackage{tabularray}
\usepackage{xcolor}
\colorlet{titleblue}{blue!70!black}

\begin{document}

\begin{tblr}{
    colspec = {lXX}, width = \textwidth,
    rowhead = 1,
    hlines, vlines,
    row{2} = {bg=titleblue!15},
    cell{2,3}{2} = {c=2}{l},
}
    Head  & Head          & Head \\
    1     & Combined text &  \\
    1.1   & Sub text      &  \\
    1.1.1 & Text          & Normal row \\
\end{tblr}

\end{document}
````

A long table in a page consists of three parts: head, body and foot. In this example, the second hline is in the head, while the second row is in the body. Therefore the hline may be covered by the row in some cases in PDF readers.

To solve this problem, I need to modify the code of long table typesetting, drawing table body before table head.

**Comment by lvjr** [comment]
@u-fischer Will it break table tagging (in the future) if I typeset table body before table head?

**Comment by u-fischer** [comment]
structure commands can rearrange things back if there are sensible hooks. Also in the case of longtable one probably want to suppress "continuation" headers from the structure as artifacts anyway.
