### ISSUE TITLE
Counter manipulation within table

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#89]
### Discussed in https://github.com/lvjr/tabularray/discussions/83

<div type='discussions-op-text'>

<sup>Originally posted by **JiriSrubar** August 27, 2021</sup>
The code

```latex
\newcounter{ca}
\arabic{ca}

\begin{tblr}{hlines,vlines}
	\stepcounter{ca}\arabic{ca}	&
	\stepcounter{ca}\arabic{ca}	&
	\stepcounter{ca}\arabic{ca}	
\end{tblr}

\arabic{ca}
```
results in

![image](https://user-images.githubusercontent.com/89645260/131133386-0ddc6ace-b599-4278-a465-df68a3f60a2f.png)

I would expect another numbers ... 

Am I missing something?</div>

**Comment by lvjr** [comment]
Also in a question "[tabularray with inserted subfloats: why counter “subfigure” doesn't start from “1” (or “a”)](https://tex.stackexchange.com/questions/612334/tabularray-with-inserted-subfloats-why-counter-subfigure-doesnt-start-from)" of tex.se.

**Comment by lvjr** [comment]
Since using private macros are kind of dangerous, I decide to put counter resetting code into a new `counter` library, in case the whole package is broken by some change in the kernel in the future.

**Comment by lvjr** [comment]
Using the code from `tabularx` package, we can define ` \__tblr_reset_counters:` command:
```latex
\cs_new_protected:Npn \__tblr_save_counters:
  {
    \def\@elt##1{\global\value{##1}=\the\value{##1}\relax}
    \edef\__tblr_reset_counters:{\cl@@ckpt}
    \let\@elt=\relax
  }
```
But using it directly will break `tabularray` tables. The reason is that there are  two important counters `rownum` and `colnum` used in building the cells.

We need to protect these two counters when we are resetting counters.

**Comment by lvjr** [comment]
Rather than defining these counters with `\newcounter` command
```latex
\newcounter{rownum}
\newcounter{colnum}
\newcounter{rowcount}
\newcounter{colcount}
```
We'd better define them with `\int_new:N` command:
```latex
\int_new:N \c@rownum
\int_new:N \c@colnum
\int_new:N \c@rowcount
\int_new:N \c@colcount
```
With this way, LaTeX kernel will not know of them and not reset them.

**Comment by FrankMittelbach** [comment]
> We'd better define them with `\int_new:N` command:
> 
> ```
> \int_new:N \c@rownum
> ```

I guess I would rather define them as `\g_..._int` and use that name within the code for manipulation and also add
```
\cs_new_eq:NN  \c@rownum \g_...
```
as a 2e interface to them.

**Comment by lvjr** [comment]
In fact, `tabularray` uses them as local counters. And modifying one of them inside a cell with `\setcounter` will probably break the whole table.  I need to warn users in the manual that these counters are **read-only**.

**Comment by FrankMittelbach** [comment]
if you expose them for use with the 2e counter interfaces then I think they shouldn't be local counters. That is bound to produce havoc. In that case better use global counters and implement a simple save and restore so that tables can be nested

**Comment by lvjr** [comment]
The real problem is LaTeX2e doesn't support local counters. Any way, maybe in some future release I will separate these public counters from private counters. It is not a good choice to let a user easily break the package.
