### ISSUE TITLE
Centering a table containing multi line headers in siunitx's S type columns fails

### ISSUE THREAD

**Issue by Sonja-K** [lvjr/tabularray#90]
As soon as I add `\centering` to the `table` environment of the following MWE, I end up with the error message shown below. Commenting out the `\centering` commands leads to a compilable document and the expected output. (Tested using version 2021M.)

```latex
\documentclass{article}
\usepackage{tabularray}
\UseTblrLibrary{siunitx}

\begin{document}

\begin{table}
%\centering
\caption{caption text}
\begin{tblr}{colspec={l S[table-format=2] S[table-format=2]}}
{two line \\ column header} & {{{column header}}} & {{{two line \\ column header}}}\\
\end{tblr}
\end{table}

\begin{table}
%\centering
\caption{caption text}
\begin{tblr}{colspec={l Q[si={table-format=2}] Q[si={table-format=2}]}}
{two line \\ column header} & {{{column header}}} & {{{two line \\ column header}}}\\
\end{tblr}
\end{table}

\end{document}
```

Error message:

```
! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.20 \end
         {tblr}
```

**Comment by lvjr** [comment]
It seems `\centering` breaks multiline cells in `S` columns. As a workaround, we can add an `\arraybackslash` after `\centering`:

````latex
\documentclass{article}
\usepackage{tabularray}
\UseTblrLibrary{siunitx}

\begin{document}

\begin{table}
\centering\arraybackslash
\caption{caption text}
\begin{tblr}{colspec={l S[table-format=2] S[table-format=2]}}
{two line \\ column header} & {{{column header}}} & {{{two line \\ column header}}} \\
\end{tblr}
\end{table}

\begin{table}
\centering\arraybackslash
\caption{caption text}
\begin{tblr}{colspec={l Q[si={table-format=2}] Q[si={table-format=2}]}}
{two line \\ column header} & {{{column header}}} & {{{two line \\ column header}}}\\
\end{tblr}
\end{table}

\end{document}
````
![image](https://user-images.githubusercontent.com/4239949/131313194-3466dfd4-55f4-49a2-a51e-ff7c89b206d7.png)

I will fix this bug after version `2021N` (scheduled on September 1st).

**Comment by lvjr** [comment]
The real problem is we can not have more than two pairs of braces for multiline cells when there is `\centering` before the table.
```latex
\documentclass{article}

\usepackage{tabularray}

\begin{document}

%% Correct

\begin{table}
\centering
\begin{tblr}{ll}
{{{one line cell}}} & {{two line \\ text}} \\
\end{tblr}
\end{table}

%% Error

\begin{table}
\centering
\begin{tblr}{ll}
{{{one line cell}}} & {{{two line \\ text}}} \\
\end{tblr}
\end{table}

\end{document}
```

**Comment by lvjr** [comment]
It seems this issue is a little tricky and may need a breaking change. I decided to fix it in version 2022.

**Comment by lvjr** [comment]
A related question: should we do `\let\\=\@normalcr` at the begining of `tabularray` environments? Macro `\@normalcr` is used in justifying cells, but not in cells with left/center/right alignments.

**Comment by mikkelee** [comment]
Hi

Unless I have misunderstood, it appears that the comment "when the cell text is guarded by a pair of curly braces, we unbrace it and ignore cmd option of the cell" in the commit dcc08ad is inaccurate — the cell text does indeed become unbraced, but the `cmd` is not ignored. I had hoped to either detect the braces inside the cmd or have the cmd skipped and the text output as-is.

```latex
\documentclass{article}

\usepackage{tabularray}

\ExplSyntaxOn

\NewColumnType {Z} { Q[r, cmd=\test_tblr_cell:n] }

\cs_new_protected:Nn \test_tblr_cell:n
  { #1 ~ is ~ \tl_if_head_is_group:nTF { #1 } { braced } { unbraced } }

\ExplSyntaxOff

\begin{document}

\begin{tblr}{Z}
	a \\
	{b} \\
	{{c}} \\
\end{tblr}

\end{document}
```

Gives the output

```
a is unbraced
b is unbraced
c is unbraced
```

**Comment by muzimuzhi** [comment]
@mikkelee More pairs of braces (than expected) are stripped in earlier steps and I've filed #501.
