### ISSUE TITLE
expand=\foo does not work if \foo defined with \New[Expandable]DocumentCommand

### ISSUE THREAD

**Issue by dahosek** [lvjr/tabularray#92]
This is likely a tough one to fix (if not impossible), because of the way that xparse definitions work: 

```
\NewDocumentCommand{\foo}{}{a&b}
\begin{tblr}[expand=\foo]{cc}
\foo
\end{tblr}
```

Changing to `\NewExpandableDocumentCommand` doesn't resolve the issue, but using `\newcommand`¹ or `\def` to define the command will work. I'm thinking this probably will get marked as “won’t fix” but should be documented.

---

1. As long as a definition with `\newcommand` doesn't have an optional argument.

**Comment by lvjr** [comment]
Yes, I should document it. In fact, \foo is a variable, not a command or function. Therefore, it is natural to defined it with `\def` in LaTeX2 or with `\tl_set` in LaTeX3.
