### ISSUE TITLE
tabularray and threeparttable

### ISSUE THREAD

**Issue by vikasrawal** [lvjr/tabularray#93]
Is there a possibility that tabularray would support the threeparttable syntax for table notes? I use org-mode and threeparttable syntax works very well. I can use tabularx or tabu inside a threeparttable, but not tabularray.

Something like the following works very well with tabularx. If one could use tabularray inside threeparttable, it would be much better than using tabularx.

#+NAME: 
#+CAPTION: 
#+ATTR_LATEX: :float t
#+begin_table*
#+begin_threeparttable
#+ATTR_LATEX: :environment tabularx :width 0.9\textwidth
#+ATTR_LATEX: :align @{}@{}
#+ATTR_LATEX: :center :booktabs t

[INSERT TABLE HERE]
#+attr_latex: :options [flushleft]
#+begin_tablenotes
#+begin_footnotesize
+ Notes: :: \mbox{}
     +
     +
+ Sources: :: \mbox{}
     1.
     2.
#+end_footnotesize
#+end_tablenotes
#+end_threeparttable
#+end_table*

**Comment by lvjr** [comment]
Tabularray provide `talltblr` environment for tables with notes. But the syntax is different. I think maybe you need to open a feature request in `org-mode` project.

**Comment by vikasrawal** [comment]
I find the threeparttable way of having the notes at the bottom more elegant. talltblr syntax is okay for short notes but would become clumsy if you want detailed notes at the bottom of the table. Is there a possibility that tblr would become compatible with threeparttable?

**Comment by lvjr** [comment]
If `tabularray` doesn't work well inside `threeparttable`, you may suggest the maintainer of `threeparttable` package to support `tabularray` package. Sorry for your inconvenience, but I think you are going in the wrong direction.

**Comment by vikasrawal** [comment]
A org-mode-based solution for the problem: https://lists.gnu.org/archive/html/emacs-orgmode/2021-09/msg00017.html
