### ISSUE TITLE
Repeating column specification multiple times

### ISSUE THREAD

**Issue by vikasrawal** [lvjr/tabularray#94]
tblr does not seem to support the following syntax for column specification

*{12}{X}

It is a convenient shorthand in tabularx to say have 12 columns of X type.

Am I doing something wrong?

**Comment by lvjr** [comment]
Yes, maybe you are using an old version of `tabularray`.  Please update it.

````latex
\documentclass{article}

\usepackage{tabularray}

\begin{document}

\begin{tblr}{*{12}{X}}
\hline
 1 & 2 & 3 & 4 & 1 & 2 & 3 & 4 & 1 & 2 & 3 & 4 \\
 1 & 2 & 3 & 4 & 1 & 2 & 3 & 4 & 1 & 2 & 3 & 4 \\
\hline
\end{tblr}

\end{document} 
````
![image](https://user-images.githubusercontent.com/4239949/131666184-9deb60fe-3e37-43a0-a8fa-8e918665ffbf.png)
