### ISSUE TITLE
No changelog

### ISSUE THREAD

**Issue by JDMCreator** [lvjr/tabularray#95]
This package is frequently updated and needs a changelog inside the documentation so we can follow what changed since the last version.

**Comment by lvjr** [comment]
You can find the changelog from CTAN announcements page:
https://ctan.org/ctan-ann/pkg/tabularray

Also you may have a look at the milestones page for upcoming changes:
https://github.com/lvjr/tabularray/milestones

**Comment by dbitouze** [comment]
Maybe it is worth:

- having a dedicated CHANGELOG file (https://keepachangelog.com/),
- following semantic versionning (https://semver.org/).

**Comment by lvjr** [comment]
The change will be updated here:
https://github.com/lvjr/tabularray/wiki/ChangeLog
